using PharmaAccess.Application.MachineLearning;
using Xunit;
namespace PharmaAccess.Llm.Tests;
public sealed class HistoricalReplayExplanationTests
{
 [Fact]public async Task Explanation_reconstructs_replay_and_grounds_only_safe_structured_output(){var replay=new ReplayStub();var model=new ModelStub();var service=new HistoricalReplayExplanationService(replay,model,new FixedTime());var response=await service.ExplainAsync(new(291,20244));Assert.Equal(new HistoricalReplayRequest(291,20244),replay.Request);Assert.Equal("StructuredPredictionOnly",response.GroundingMode);Assert.Contains("\"Probability\":0.234",model.Prompt);Assert.Contains("\"Rank\":1",model.Prompt);Assert.Contains("Texas",model.Prompt);Assert.Contains("historical research replay",model.Prompt,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("\"Features\":",model.Prompt,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("ObservedPrescriptionCount",model.Prompt,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("LabelNextQuarterEntry",model.Prompt,StringComparison.OrdinalIgnoreCase);}
 [Fact]public async Task Unavailable_Gemini_does_not_prevent_scoring_and_explanation_fails_separately(){var replay=new ReplayStub();var score=await replay.ReplayAsync(new(291,20244));Assert.Single(score.RankedStates);var service=new HistoricalReplayExplanationService(replay,new ModelStub{Available=false},TimeProvider.System);await Assert.ThrowsAsync<InvalidOperationException>(()=>service.ExplainAsync(new(291,20244)));Assert.Equal(.234f,score.RankedStates[0].Probability);}
 [Fact]public async Task Invalid_selection_cannot_explain(){var service=new HistoricalReplayExplanationService(new ReplayStub{Reject=true},new ModelStub(),TimeProvider.System);await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.ExplainAsync(new(999,20244)));}
 private sealed class ReplayStub:IHistoricalPredictionReplayService{public HistoricalReplayRequest? Request;public bool Reject;public Task<IReadOnlyList<HistoricalReplayLaunch>> GetLaunchesAsync(CancellationToken t=default)=>throw new NotSupportedException();public Task<IReadOnlyList<int>> GetQuartersAsync(int id,CancellationToken t=default)=>throw new NotSupportedException();public Task<HistoricalReplayResponse> ReplayAsync(HistoricalReplayRequest request,CancellationToken t=default){Request=request;if(Reject)throw new KeyNotFoundException();return Task.FromResult(new HistoricalReplayResponse(HistoricalReplayMode.Name,291,"Generic launch 291",20244,20251,"version","hash","dataset",2,"features",1,.08,1,[new(48,"TX","Texas",.234f,true,1)],["warning"],ModelApprovalStatus.ValidationSelected,false,false));}}
 private sealed class ModelStub:ILanguageModelClient{public bool Available=true;public string Prompt="";public string Provider=>"Fake Gemini";public string Model=>"fake";public bool IsAvailable=>Available;public Task<string> GenerateAsync(string prompt,CancellationToken t=default){Prompt=prompt;return Task.FromResult("Safe explanation");}}
 private sealed class FixedTime:TimeProvider{public override DateTimeOffset GetUtcNow()=>new(2026,8,14,0,0,0,TimeSpan.Zero);}
}
