using PharmaAccess.Application.MachineLearning;
using Xunit;
namespace PharmaAccess.Llm.Tests;
public sealed class HistoricalReplayExplanationTests
{
 [Fact]public async Task Explanation_reconstructs_replay_and_grounds_only_safe_structured_output(){var replay=new ReplayStub();var model=new ModelStub{Response="Texas is the highest-ranked jurisdiction. This is research output, not a recommendation."};var service=new HistoricalReplayExplanationService(replay,model,new FixedTime());var response=await service.ExplainAsync(new(291,20244));Assert.Equal(model.Response,response.Explanation);Assert.Equal(new HistoricalReplayRequest(291,20244),replay.Request);Assert.Equal("StructuredPredictionOnly",response.GroundingMode);Assert.Contains("readable natural-language prose only",model.Prompt);Assert.Contains("Do not return JSON",model.Prompt);Assert.Contains("\"Probability\":0.234",model.Prompt);Assert.Contains("\"Rank\":1",model.Prompt);Assert.Contains("Texas",model.Prompt);Assert.DoesNotContain("\"Features\":",model.Prompt,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("ObservedPrescriptionCount",model.Prompt,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("LabelNextQuarterEntry",model.Prompt,StringComparison.OrdinalIgnoreCase);}
 [Theory][InlineData("{\"explanation_type\":\"historical research replay\",\"jurisdiction_probabilities\":[]}")][InlineData("```json\n{\"rank\":1}\n```")][InlineData("")][InlineData("   ")]public async Task Invalid_or_empty_Gemini_format_uses_verified_deterministic_prose(string invalid){var model=new ModelStub{Response=invalid};var response=await new HistoricalReplayExplanationService(new ReplayStub(),model,new FixedTime()).ExplainAsync(new(291,20244));Assert.DoesNotContain("explanation_type",response.Explanation);Assert.DoesNotContain("```",response.Explanation);Assert.DoesNotContain("{\"",response.Explanation);Assert.Contains("Texas is the highest-ranked jurisdiction",response.Explanation);Assert.Contains("23.40%",response.Explanation);Assert.Contains("selected research threshold of 8.00%",response.Explanation);Assert.Contains("ValidationSelected",response.Explanation);Assert.Contains("not production approved",response.Explanation);Assert.Contains("not assigned Champion",response.Explanation);Assert.DoesNotContain("Feature",response.Explanation,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("Label",response.Explanation,StringComparison.OrdinalIgnoreCase);}
 [Fact]public async Task Unavailable_Gemini_uses_fallback_without_changing_verified_prediction(){var replay=new ReplayStub();var score=await replay.ReplayAsync(new(291,20244));var service=new HistoricalReplayExplanationService(replay,new ModelStub{Available=false},TimeProvider.System);var response=await service.ExplainAsync(new(291,20244));Assert.Equal(.234f,score.RankedStates[0].Probability);Assert.Equal(1,score.RankedStates[0].Rank);Assert.Equal(ModelApprovalStatus.ValidationSelected,score.GovernanceStatus);Assert.False(score.ProductionApproved);Assert.False(score.Champion);Assert.Contains("23.40%",response.Explanation);Assert.Contains("Texas",response.Explanation);}
 [Fact]public async Task Gemini_failure_uses_fallback_and_prediction_remains_available(){var replay=new ReplayStub();var service=new HistoricalReplayExplanationService(replay,new ModelStub{Failure=new HttpRequestException("429 private response")},TimeProvider.System);var response=await service.ExplainAsync(new(291,20244));Assert.Contains("Texas is the highest-ranked",response.Explanation);Assert.Single((await replay.ReplayAsync(new(291,20244))).RankedStates);Assert.DoesNotContain("429",response.Explanation);}
 [Fact]public async Task Invalid_selection_cannot_explain(){var service=new HistoricalReplayExplanationService(new ReplayStub{Reject=true},new ModelStub(),TimeProvider.System);await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.ExplainAsync(new(999,20244)));}
 private sealed class ReplayStub:IHistoricalPredictionReplayService{public HistoricalReplayRequest? Request;public bool Reject;public Task<IReadOnlyList<HistoricalReplayLaunch>> GetLaunchesAsync(CancellationToken t=default)=>throw new NotSupportedException();public Task<IReadOnlyList<int>> GetQuartersAsync(int id,CancellationToken t=default)=>throw new NotSupportedException();public Task<HistoricalReplayResponse> ReplayAsync(HistoricalReplayRequest request,CancellationToken t=default){Request=request;if(Reject)throw new KeyNotFoundException();return Task.FromResult(new HistoricalReplayResponse(HistoricalReplayMode.Name,291,"Generic launch 291",20244,20251,"version","hash","dataset",2,"features",1,.08,1,[new(48,"TX","Texas",.234f,true,1)],["warning"],ModelApprovalStatus.ValidationSelected,false,false));}}
 private sealed class ModelStub:ILanguageModelClient{public bool Available=true;public string Prompt="";public string Response="Safe explanation";public Exception? Failure;public string Provider=>"Fake Gemini";public string Model=>"fake";public bool IsAvailable=>Available;public Task<string> GenerateAsync(string prompt,CancellationToken t=default){Prompt=prompt;if(Failure is not null)throw Failure;return Task.FromResult(Response);}}
 private sealed class FixedTime:TimeProvider{public override DateTimeOffset GetUtcNow()=>new(2026,8,14,0,0,0,TimeSpan.Zero);}
}
