using PharmaAccess.Application.MachineLearning;
using Xunit;

namespace PharmaAccess.Llm.Tests;

public sealed class HistoricalReplayExplanationTests
{
 [Fact]public async Task Complete_grounding_contains_all_states_layers_product_and_outcome(){var replay=new ReplayStub();var model=new ModelStub{Available=false};var response=await new HistoricalReplayExplanationService(replay,Doubles.Composer(model)).ExplainAsync(new(291,20244));Assert.NotNull(response.Analysis);Assert.NotEqual(Guid.Empty,response.SessionId);Assert.Equal("CompleteStructuredExplorerAnalysis",response.GroundingMode);Assert.Equal(new(291,20244),replay.Request);var report=response.Analysis!;Assert.InRange(report.WhatYouShouldKnow.Count,3,5);Assert.InRange(report.WhatStandsOut.Count,4,6);Assert.InRange(report.SuggestedQuestions.Count,5,7);Assert.Contains("10 states entered",report.ModelOutcomeAssessment);Assert.Contains("Historical participation",string.Join('|',report.HowToUse),StringComparison.OrdinalIgnoreCase);}
 [Fact]public async Task Gemini_prompt_sends_complete_safe_grounding_without_private_material(){var model=new ModelStub{Response="invalid"};await new HistoricalReplayExplanationService(new ReplayStub(),Doubles.Composer(model)).ExplainAsync(new(291,20244));Assert.Contains(ExplorerBusinessAnalysisComposer.SystemInstruction,model.Prompt);Assert.Contains("\"GenericLaunchId\":291",model.Prompt);Assert.Contains("\"CandidateStateCount\":2",model.Prompt);Assert.Contains("\"StateCode\":\"TX\"",model.Prompt);Assert.Contains("\"StateCode\":\"CA\"",model.Prompt);Assert.Contains("\"MarketSizeScore\":90",model.Prompt);Assert.Contains("\"HistoricalParticipationRate\":0.4",model.Prompt);Assert.Contains("\"StateName\":\"California\",\"EntryRank\":2,\"EntryProbability\":0.02,\"AboveSelectedThreshold\":false,\"RecentMarketVolume\":null",model.Prompt);Assert.Contains("\"ActualObservedEntryCount\":10",model.Prompt);Assert.DoesNotContain("LabelNextQuarterEntry",model.Prompt,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("PharmaAccessCausalIntelligence_ResearchDev",model.Prompt,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("D:\\",model.Prompt,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("connection",model.Prompt,StringComparison.OrdinalIgnoreCase);}
 [Fact]public async Task Gemini_failure_returns_structured_fallback_without_changing_replay(){var replay=new ReplayStub();var response=await new HistoricalReplayExplanationService(replay,Doubles.Composer(new ModelStub{Failure=new HttpRequestException("private 429")})).ExplainAsync(new(291,20244));Assert.NotNull(response.Analysis);Assert.Contains("Texas",response.Explanation);Assert.Equal(.0275f,(await replay.ReplayAsync(new(291,20244))).RankedStates[0].Probability);Assert.DoesNotContain("429",response.Explanation);}
 [Fact]public async Task Chat_retains_session_and_safely_reframes_unsupported_questions(){var store=new ExplorerAnalysisSessionStore();var model=new ModelStub{Available=false};var response=await new HistoricalReplayExplanationService(new ReplayStub(),Doubles.Composer(model,store)).ExplainAsync(new(291,20244));var chat=new ExplorerAnalysisChatService(store,model,TimeProvider.System);Assert.Contains("not a future-entry probability",(await chat.AskAsync(new(response.SessionId,"Does 40% participation mean a 40% probability?"))).Answer);Assert.Contains("does not support a commercial targeting",(await chat.AskAsync(new(response.SessionId,"Which state should we target?"))).Answer);Assert.Contains("cannot estimate revenue",(await chat.AskAsync(new(response.SessionId,"Estimate revenue"))).Answer);Assert.Contains("not selected-drug demand",(await chat.AskAsync(new(response.SessionId,"Market score 100 means highest demand?"))).Answer);Assert.Contains("not absolute market size",(await chat.AskAsync(new(response.SessionId,"Growth score 100 means biggest market?"))).Answer);await Assert.ThrowsAsync<KeyNotFoundException>(()=>chat.AskAsync(new(Guid.NewGuid(),"Why Texas?")));}
 [Fact]public async Task Invalid_selection_cannot_explain(){await Assert.ThrowsAsync<KeyNotFoundException>(()=>new HistoricalReplayExplanationService(new ReplayStub{Reject=true},Doubles.Composer(new ModelStub())).ExplainAsync(new(999,20244)));}

 private sealed class ReplayStub:IHistoricalPredictionReplayService{public HistoricalReplayRequest? Request;public bool Reject;public Task<IReadOnlyList<HistoricalReplayLaunch>> GetLaunchesAsync(CancellationToken t=default)=>throw new NotSupportedException();public Task<IReadOnlyList<int>> GetQuartersAsync(int id,CancellationToken t=default)=>throw new NotSupportedException();public Task<HistoricalReplayResponse> ReplayAsync(HistoricalReplayRequest request,CancellationToken t=default){Request=request;if(Reject)throw new KeyNotFoundException();return Task.FromResult(new HistoricalReplayResponse(HistoricalReplayMode.Name,291,"Prucalopride Succinate",20244,20251,"version","hash","dataset",2,"features",1,.08,2,[new(48,"TX","Texas",.0275f,false,1),new(6,"CA","California",.02f,false,2)],[],ModelApprovalStatus.ValidationSelected,false,false){ActualObservedEntryCount=10,ActualObservedStates=[new(4,39,"OH","Ohio")],BestActualObservedRank=4,TopPredictedStateActuallyEntered=false,ThresholdDecisionCorrect=false,HistoricalOutcomeSummary="10 states entered"});}}
}

internal static class Doubles
{
 public static ExplorerBusinessAnalysisComposer Composer(ModelStub model,ExplorerAnalysisSessionStore? store=null)=>new(new Catalog(),new Market(),new Readiness(),model,store??new());
 sealed class Catalog:IResearchLaunchCatalogService{public Task<IReadOnlyList<HistoricalReplayLaunch>> GetLaunchesAsync(CancellationToken t=default)=>Task.FromResult<IReadOnlyList<HistoricalReplayLaunch>>([new(291,"Prucalopride Succinate",Anda:"218492",ApprovalDate:new(2024,2,12)){DrugNames=["Prucalopride Succinate"],ActiveIngredients=["Prucalopride"],Forms=["Tablet"]},new(7,"Launch 7")]);}
 sealed class Market:IStateMarketContextService{public Task<StateMarketContextResponse> GetAsync(StateMarketContextRequest r,CancellationToken t=default)=>Task.FromResult(new StateMarketContextResponse(r.GenericLaunchId,r.AsOfQuarter,51,[new(48,"TX","Texas",r.AsOfQuarter,1000,90,900,.04m,-.2m,0,1000,1200,8,1,MarketDataSupport.High,"Large & Established")],[]));}
 sealed class Readiness:IStateReadinessContextService{public Task<StateReadinessContextResponse> GetAsync(StateReadinessContextRequest r,CancellationToken t=default)=>Task.FromResult(new StateReadinessContextResponse(r.GenericLaunchId,r.AsOfQuarter,[new(48,"TX","Texas",r.AsOfQuarter,.4m,10,4,2,4,0,3)],[]));}
}
internal sealed class ModelStub:ILanguageModelClient{public bool Available=true;public string Prompt="";public string Response="invalid";public Exception? Failure;public string Provider=>"Fake Gemini";public string Model=>"fake";public bool IsAvailable=>Available;public Task<string> GenerateAsync(string prompt,CancellationToken t=default){Prompt=prompt;if(Failure is not null)throw Failure;return Task.FromResult(Response);}}
