using System.Security.Cryptography;
using System.Text;
using PharmaAccess.Application.Research;
using PharmaAccess.Domain.Research;
using Xunit;

namespace PharmaAccess.Application.Tests;

public sealed class MilestoneEightResearchFreezeTests
{
    [Fact] public void Source_registration_hashes_and_detects_modification() { var root = Local(); try { var path = Path.Combine(root, "source.csv"); File.WriteAllText(path, "a,b\n1,2\n"); var service = new ResearchSourceRegistryService(); var source = service.Register(root, path, "source", ResearchSourceType.FdaFirstGenericApproval, "FDA", "fixture", "local://fixture", "v1", true, "tester", Now); service.ValidateUnmodified(source, root); File.AppendAllText(path, "3,4\n"); Assert.Throws<InvalidOperationException>(() => service.ValidateUnmodified(source, root)); } finally { Directory.Delete(root, true); } }
    [Fact] public void Source_registration_rejects_path_traversal_and_extension() { var root = Local(); try { var outside = Path.Combine(Path.GetDirectoryName(root)!, "outside.exe"); File.WriteAllText(outside, "x"); var service = new ResearchSourceRegistryService(); Assert.Throws<ArgumentException>(() => service.Register(root, outside, "x", ResearchSourceType.ManuallyCuratedMapping, "a", "d", "local://x", "v1", true, "u", Now)); var bad = Path.Combine(root, "bad.exe"); File.WriteAllText(bad, "x"); Assert.Throws<InvalidOperationException>(() => service.Register(root, bad, "x", ResearchSourceType.ManuallyCuratedMapping, "a", "d", "local://x", "v1", true, "u", Now)); File.Delete(outside); } finally { Directory.Delete(root, true); } }
    [Fact] public void Duplicate_source_codes_are_rejected() { var hash = new string('A', 64); var a = new ResearchSourceRegistration("x", ResearchSourceType.StateTerritoryReference, "a", "d", "d", "local://x", Now, null, null, "n", "v", "x.csv", "x.csv", hash, 1, "utf-8", ",", true, "u", Now); Assert.Throws<InvalidOperationException>(() => ResearchSourceRegistryService.RejectDuplicates([a, a])); }
    [Fact] public void Quality_gates_detect_requested_failures() { var bad = Row() with { AnalyticalKey = 1, QuarterId = 20219, PrescriptionCount = -1, IsMissing = true, NextQuarterLabel = true, Q4Complete = false, Treatment = null, HasBlockingLeakage = true, SelectedFeatures = ["LabelNextQuarterEntry"], TreatmentQuarterId = 20212, OutcomeQuarterId = 20212 }; var findings = new ResearchFreezeQualityGate().Evaluate([bad, bad], splitOverlap: true, chronologicalSplit: false); var codes = findings.Select(x => x.Code).ToHashSet(); Assert.Contains("NoDuplicateAnalyticalKey", codes); Assert.Contains("ValidCalendarQuarter", codes); Assert.Contains("NonnegativePrescription", codes); Assert.Contains("CensoredLabelsNull", codes); Assert.Contains("NoProhibitedFeature", codes); Assert.Contains("NoPredictiveGroupOverlap", codes); Assert.Contains("ChronologicalPredictiveSplit", codes); Assert.Contains("TreatmentPrecedesOutcome", codes); Assert.Contains("TreatedAndControlPresent", codes); Assert.All(findings, x => Assert.Equal(ResearchFindingSeverity.Blocking, x.Severity)); }
    [Fact] public void Missing_suppressed_and_zero_are_distinct() { var missing = Row() with { IsMissing = true, PrescriptionCount = 0 }; var suppressed = Row() with { AnalyticalKey = 2, IsSuppressed = true, PrescriptionCount = 0 }; var codes = new ResearchFreezeQualityGate().Evaluate([missing, suppressed]).Select(x => x.Code); Assert.Contains("MissingDistinctFromZero", codes); Assert.Contains("SuppressedDistinctFromZero", codes); }
    [Fact] public void Cohort_hash_is_deterministic_and_changes_with_rules() { var rows = new[] { Row(), Row() with { AnalyticalKey = 2, Treatment = false } }; var service = new ResearchCohortService(); Assert.Equal(service.Build(rows, "v1").CohortHash, service.Build(rows, "v1").CohortHash); Assert.NotEqual(service.Build(rows, "v1").CohortHash, service.Build(rows, "v2").CohortHash); }
    [Fact] public void Git_safety_reports_paths_without_reading_contents() { var unsafePaths = new[] { "data/raw/fda.csv", ".env", "artifacts/models/model.bin", "samples/data/feature/synthetic_feature_observations.csv" }; var found = new ResearchGitSafetyService().FindUnsafeTrackedPaths(".", unsafePaths); Assert.Contains("data/raw/fda.csv", found); Assert.Contains(".env", found); Assert.DoesNotContain("samples/data/feature/synthetic_feature_observations.csv", found); }
    [Fact] public void Synthetic_workflow_is_reproducible_complete_and_hash_verified() { var root = Local(); var other = Local(); try { var workflow = new SyntheticResearchFreezeWorkflow(); var a = workflow.Run(root, "m8-synthetic", "lock", "packages"); var first = Directory.GetFiles(a.ArtifactRoot).ToDictionary(p => Path.GetFileName(p)!, File.ReadAllBytes); Assert.Throws<InvalidOperationException>(() => workflow.Run(root, "m8-synthetic", "lock", "packages")); var b = workflow.Run(other, "m8-synthetic", "lock", "packages"); Assert.Equal(ResearchFreezeStatus.ReadyForAnalysis, b.Status); Assert.Equal(a.ReproducibilityHash, b.ReproducibilityHash); Assert.Equal(24, b.Files.Count); Assert.All(Directory.GetFiles(b.ArtifactRoot, "*.md"), p => Assert.Contains(ResearchFreezePackageWriter.Notice, File.ReadAllText(p))); new ResearchFreezePackageWriter().Verify(b.ArtifactRoot); Assert.Equal(first["freeze_manifest.json"], File.ReadAllBytes(Path.Combine(b.ArtifactRoot, "freeze_manifest.json"))); } finally { Directory.Delete(root, true); Directory.Delete(other, true); } }
    private static ResearchObservation Row() => new(1, 1, 1, "TX", 20211, 20211, 1, 1, false, false, true, true, true, 20210, 20211, 20212, false, ["QuarterSinceApproval"]); private static readonly DateTime Now = new(2026, 7, 21, 0, 0, 0, DateTimeKind.Utc); private static string Local() { var p = Path.Combine(Path.GetTempPath(), $"pa-m8-{Guid.NewGuid():N}"); Directory.CreateDirectory(p); return p; }
}
