using PharmaAccess.Application.Research;
using Xunit;

namespace PharmaAccess.Application.Tests;

public sealed class ResearchImportPersistenceTests
{
    [Fact] public async Task Coordinator_orders_canonical_sources_reconciles_and_never_finalizes_or_trains()
    {
        var store=new FakeStore();var sources=new[]{Source("z.csv",ImportSourceKind.Medicaid,true),Source("archive.csv",ImportSourceKind.Fda,false),Source("a.csv",ImportSourceKind.Fda,true)};var init=new ImportInitialization("real-v1",1,"corr",new string('A',64),sources,"commit");var completion=await new ResearchImportCoordinator(store).ExecuteAsync(init,Batches(sources),2,default);Assert.Equal(["a.csv","z.csv"],store.Initialized!.Sources.Select(x=>x.RelativePath));Assert.Equal(8,completion.Registered);Assert.Equal(2,completion.Accepted);Assert.Equal(2,completion.Rejected);Assert.Equal(2,completion.Duplicate);Assert.Equal(2,completion.ExplicitlyExcluded);Assert.True(store.Completed);Assert.False(store.DatasetFinalized);Assert.False(store.ModelTrainingStarted);Assert.False(store.CausalEstimationStarted);
    }
    [Fact] public async Task Failure_stops_without_false_completion(){var store=new FakeStore{FailBatch=2};var source=Source("a.csv",ImportSourceKind.Fda,true);await Assert.ThrowsAsync<InvalidOperationException>(()=>new ResearchImportCoordinator(store).ExecuteAsync(new("v",1,"c",new string('A',64),[source],"g"),Batches([source]),2,default));Assert.False(store.Completed);}
    [Fact] public void Protocol_template_contains_resolved_reviewed_decisions(){var path=FindRoot();var text=File.ReadAllText(Path.Combine(path,"config","research-protocols","approval-to-access-real-1.0.json"));Assert.DoesNotContain("HUMAN_DECISION_REQUIRED",text);Assert.Contains("2021-01-01 through 2022-12-31",text);Assert.Contains("minimum eligible-peer count 2",text);Assert.Contains("minimum counts 1 and 3",text);Assert.Contains("Ambiguous/Unresolved",text);Assert.Contains("FdaConvertedContinuationFragmentV1",text);Assert.Contains("unknown-not-zero",text);}
    private static ImportSourceRegistration Source(string path,ImportSourceKind kind,bool canonical)=>new(path,new string(char.ToUpperInvariant(path[0]),64),10,"v1",kind,2,canonical);
    private static async IAsyncEnumerable<(ImportSourceRegistration Source,IReadOnlyList<RawImportRow> Rows)> Batches(IEnumerable<ImportSourceRegistration> sources){foreach(var s in sources){await Task.Yield();yield return(s,[Row(1,ImportRowDisposition.Accepted),Row(2,ImportRowDisposition.Rejected),Row(3,ImportRowDisposition.Duplicate),Row(4,ImportRowDisposition.ExplicitlyExcluded)]);}}
    private static RawImportRow Row(long n,ImportRowDisposition d)=>new(n,d,new Dictionary<string,string?>(),d==ImportRowDisposition.Accepted?null:d.ToString());
    private static string FindRoot(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d is not null&&!File.Exists(Path.Combine(d.FullName,"PharmaAccess.sln")))d=d.Parent;return d?.FullName??throw new InvalidOperationException();}
    private sealed class FakeStore:IResearchImportPersistence{public ImportInitialization? Initialized;public bool Completed;public bool DatasetFinalized{get;set;}public bool ModelTrainingStarted{get;set;}public bool CausalEstimationStarted{get;set;}public int? FailBatch;public Task<ImportSession> InitializeAsync(ImportInitialization r,CancellationToken c){Initialized=r;return Task.FromResult(new ImportSession(1,1,r.Sources.ToDictionary(x=>x.Sha256,_=>1)));}public Task<ImportBatchResult> PersistBatchAsync(ImportSession s,ImportBatch b,CancellationToken c){if(FailBatch==b.BatchNumber)throw new InvalidOperationException("synthetic rollback");return Task.FromResult(new ImportBatchResult(b.Rows.Count(x=>x.Disposition==ImportRowDisposition.Accepted),b.Rows.Count(x=>x.Disposition==ImportRowDisposition.Rejected),b.Rows.Count(x=>x.Disposition==ImportRowDisposition.Duplicate),b.Rows.Count(x=>x.Disposition==ImportRowDisposition.ExplicitlyExcluded),b.Rows.Max(x=>x.SourceRowNumber)));}public Task CompleteAsync(ImportSession s,ImportCompletion c,CancellationToken t){Completed=true;return Task.CompletedTask;}public Task<ImportCheckpoint?> GetCheckpointAsync(long r,string h,CancellationToken c)=>Task.FromResult<ImportCheckpoint?>(null);}
}
