using System.Globalization;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace PharmaAccess.Application.Research;

public sealed record SourceRowExclusion(string RelativePath, long SourceRecordNumber, string RuleCode, string Evidence);
public sealed record RealSourceFileReport(string RelativePath, RealSourceCategory? Category, bool CanonicalForImport, long ByteSize, string Sha256, string SchemaProfile, string Encoding, string Delimiter, IReadOnlyList<string> Headers, long TotalRows, long AcceptedRows, long RejectedRows, long ExplicitlyExcludedRows, long WarningCount, long ErrorCount, bool SchemaMatch, NdcQualityReport? NdcQuality, IReadOnlyList<string> UnresolvedFields, IReadOnlyList<string> BlockingFindings, IReadOnlyList<string> Warnings, IReadOnlyList<SourceRowExclusion> Exclusions);
public sealed record RealSourceExecutionReport(IReadOnlyList<RealSourceFileReport> Files, long TotalRows, long AcceptedRows, long RejectedRows, long ExplicitlyExcludedRows, long WarningCount, long ErrorCount, IReadOnlyList<string> BlockingFindings, IReadOnlyList<string> CanonicalFdaSources, IReadOnlyList<string> ProvenanceOnlyFdaSources);

public sealed class MilestoneNineRealSourceWorkflow
{
    private readonly PrivatePathPolicy paths = new();
    private static readonly JsonSerializerOptions Json = new() { WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

    public ResearchSourceManifest DiscoverAndWriteManifest(string privateRoot, string manifestPath, string discoveryReportPath)
    {
        var root = paths.ResolveRoot(privateRoot); var assignments = new List<SourceAssignment>(); var reports = new List<object>();
        foreach (var file in Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories).Order(StringComparer.OrdinalIgnoreCase))
        {
            var relative = Path.GetRelativePath(root, file).Replace('\\', '/'); var info = new FileInfo(file); using var stream = File.OpenRead(file); var hash = Convert.ToHexString(SHA256.HashData(stream)); var classification = Classify(relative);
            reports.Add(new { relativePath = relative, info.Length, sha256 = hash, category = classification.Category?.ToString(), profileCandidate = classification.Profile, recognized = classification.Category.HasValue, warning = classification.Warning });
            if (classification.Category.HasValue) assignments.Add(new(relative, classification.Category.Value, hash, classification.Profile, Coverage(relative, true), Coverage(relative, false), Path.GetExtension(relative).Equals(".zip", StringComparison.OrdinalIgnoreCase) || Path.GetExtension(relative).Equals(".gz", StringComparison.OrdinalIgnoreCase), classification.Category == RealSourceCategory.FdaFirstGeneric && relative.EndsWith(".zip", StringComparison.OrdinalIgnoreCase) ? "inspect-in-place-no-nested-archives" : "none"));
        }
        var manifest = new ResearchSourceManifest("real-source-assignment-v1", assignments); EnsurePrivateOutput(root, manifestPath); File.WriteAllText(manifestPath, JsonSerializer.Serialize(manifest, Json), new UTF8Encoding(false)); WriteSanitized(discoveryReportPath, new { files = reports, recognized = assignments.Count, unrecognized = reports.Count - assignments.Count, duplicateAssignments = assignments.GroupBy(x => x.RelativePath, StringComparer.OrdinalIgnoreCase).Where(x => x.Count() > 1).Select(x => x.Key).ToArray(), missingRequiredCategories = RequiredMissing(assignments) }); return manifest;
    }

    public RealSourceExecutionReport Validate(string privateRoot, string manifestPath, string outputPath, CancellationToken cancellationToken = default)
    {
        var root = paths.ResolveRoot(privateRoot); var manifest = JsonSerializer.Deserialize<ResearchSourceManifest>(File.ReadAllText(manifestPath), new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? throw new InvalidOperationException("Private manifest is invalid."); var manifestFindings = new ResearchSourceManifestValidator().Validate(manifest, root); var results = new List<RealSourceFileReport>();
        foreach (var assignment in manifest.Assignments) { cancellationToken.ThrowIfCancellationRequested(); var file = paths.ResolveFile(root, assignment.RelativePath); results.Add(ValidateOne(root, file, assignment, cancellationToken)); }
        var blockers = manifestFindings.Concat(results.SelectMany(x => x.BlockingFindings.Select(y => $"{x.RelativePath}:{y}"))).ToArray(); var canonical = results.Where(x => x.CanonicalForImport).ToArray(); var fda = results.Where(x => x.Category == RealSourceCategory.FdaFirstGeneric).ToArray(); var report = new RealSourceExecutionReport(results, canonical.Sum(x => x.TotalRows), canonical.Sum(x => x.AcceptedRows), canonical.Sum(x => x.RejectedRows), canonical.Sum(x => x.ExplicitlyExcludedRows), results.Sum(x => x.WarningCount), results.Sum(x => x.ErrorCount), blockers, fda.Where(x => x.CanonicalForImport).Select(x => x.RelativePath).ToArray(), fda.Where(x => !x.CanonicalForImport).Select(x => x.RelativePath).ToArray()); WriteSanitized(outputPath, report); return report;
    }

    private RealSourceFileReport ValidateOne(string root, string file, SourceAssignment assignment, CancellationToken token)
    {
        var relative = Path.GetRelativePath(root, file).Replace('\\', '/'); var info = new FileInfo(file); var blockers = new List<string>(); var warnings = new List<string>(); if (info.Length == 0) blockers.Add("ZeroLengthFile"); using (var stream = File.OpenRead(file)) if (!Convert.ToHexString(SHA256.HashData(stream)).Equals(assignment.Sha256, StringComparison.OrdinalIgnoreCase)) blockers.Add("SourceHashMismatch");
        var extension = Path.GetExtension(file).ToLowerInvariant(); if (extension == ".xlsx") return ValidateXlsx(relative, info, assignment, blockers, warnings); if (extension == ".zip") return ValidateZip(relative, info, assignment, blockers, warnings, token);
        var delimiter = relative.EndsWith("county_adjacency_2025.txt", StringComparison.OrdinalIgnoreCase) ? '|' : ','; return ValidateDelimited(relative, info, assignment, delimiter, blockers, warnings, token);
    }

    private static RealSourceFileReport ValidateDelimited(string relative, FileInfo info, SourceAssignment assignment, char delimiter, List<string> blockers, List<string> warnings, CancellationToken token)
    {
        using var stream = File.OpenRead(info.FullName); using var reader = new StreamReader(stream, DetectTextEncoding(info.FullName), true, 1 << 20); using var csv = new CsvRecordReader(reader, delimiter); var headers = csv.ReadRecord() ?? []; var duplicateHeaders = headers.GroupBy(x => x, StringComparer.OrdinalIgnoreCase).Where(x => x.Count() > 1).Select(x => x.Key).ToArray(); if (duplicateHeaders.Length != 0) blockers.Add("DuplicateHeaders:" + string.Join(',', duplicateHeaders)); var required = RequiredHeaders(assignment.SchemaProfileVersion); var missing = required.Where(x => !headers.Contains(x, StringComparer.OrdinalIgnoreCase)).ToArray(); if (missing.Length != 0) blockers.Add("MissingRequiredHeaders:" + string.Join(',', missing));
        var indexes = headers.Select((x, i) => (x, i)).GroupBy(x => x.x, StringComparer.OrdinalIgnoreCase).ToDictionary(x => x.Key, x => x.First().i, StringComparer.OrdinalIgnoreCase); long total = 0, accepted = 0, rejected = 0, excluded = 0, warningCount = 0, errorCount = 0; var ndc = new NdcAccumulator(); var rowHashes = new HashSet<ulong>(); var exclusions = new List<SourceRowExclusion>(); string[]? row;
        while ((row = csv.ReadRecord()) is not null) { token.ThrowIfCancellationRequested(); total++; var errors = 0; if (row.Length != headers.Length) { if (assignment.SchemaProfileVersion == "medicaid-dictionary-csv-v1") warningCount++; else errors++; } if (errors == 0 && assignment.Category == RealSourceCategory.FdaFirstGeneric && TryClassifyFdaExclusion(row, indexes, relative, total, out var exclusion)) { excluded++; exclusions.Add(exclusion!); continue; } if (errors == 0 && assignment.Category == RealSourceCategory.FdaFirstGeneric) errors += ValidateFda(row, indexes, relative, ref warningCount); if (errors == 0 && assignment.Category == RealSourceCategory.MedicaidUtilization && assignment.SchemaProfileVersion.StartsWith("medicaid-data", StringComparison.Ordinal)) errors += ValidateMedicaid(row, indexes, relative, ndc, ref warningCount); if (errors == 0 && assignment.Category == RealSourceCategory.StateReference) errors += ValidateStateReference(row, indexes); if (errors == 0 && assignment.Category == RealSourceCategory.StateAdjacency) errors += ValidateAdjacency(row, indexes, ref warningCount); var hash = Fnv(row); if (!rowHashes.Add(hash)) warningCount++; if (errors == 0) accepted++; else { rejected++; errorCount += errors; } }
        if (rejected != 0) blockers.Add("RejectedRowsPresent"); if (warningCount != 0) warnings.Add("Warnings include duplicates, ambiguous NDCs, corrections, suppression, or declared-year differences; inspect file report counts."); var canonical = IsCanonicalImportSource(relative, assignment); return new(relative, assignment.Category, canonical, info.Length, assignment.Sha256, assignment.SchemaProfileVersion, reader.CurrentEncoding.WebName, delimiter.ToString(), headers, total, accepted, rejected, excluded, warningCount, errorCount, missing.Length == 0 && duplicateHeaders.Length == 0, ndc.HasValues ? ndc.Report() : null, missing, blockers, warnings, exclusions);
    }

    internal static bool TryClassifyFdaExclusion(string[] row, Dictionary<string, int> ix, string relative, long sourceRecordNumber, out SourceRowExclusion? exclusion)
    {
        exclusion = null; Try(row, ix, "ANDA Number", out var anda); Try(row, ix, "Generic Name", out var generic); Try(row, ix, "ANDA Applicant", out var applicant); Try(row, ix, "Brand Name", out var brand); Try(row, ix, "ANDA Approval Date", out var date); Try(row, ix, "ANDA Indication", out var indication); Try(row, ix, "SourceYear", out var year);
        var continuationShape = string.IsNullOrWhiteSpace(anda) && !string.IsNullOrWhiteSpace(generic) && string.IsNullOrWhiteSpace(applicant) && string.IsNullOrWhiteSpace(brand) && string.IsNullOrWhiteSpace(date) && string.IsNullOrWhiteSpace(indication) && int.TryParse(year, out var sourceYear) && YearFromPath(relative) == sourceYear;
        if (!continuationShape) return false;
        exclusion = new(relative, sourceRecordNumber, "FdaConvertedContinuationFragmentV1", "Only Generic Name and the matching SourceYear are populated; all approval identity/date fields are blank. Preserve as an excluded conversion fragment; do not fabricate or merge fields."); return true;
    }

    private static int ValidateFda(string[] row, Dictionary<string, int> ix, string relative, ref long warnings)
    {
        var errors = 0; if (!Try(row, ix, "ANDA Number", out var anda) || string.IsNullOrWhiteSpace(anda)) errors++; if (!Try(row, ix, "Generic Name", out var generic) || string.IsNullOrWhiteSpace(generic)) errors++; if (!Try(row, ix, "ANDA Approval Date", out var date) || !DateTime.TryParse(date, CultureInfo.InvariantCulture, DateTimeStyles.AllowWhiteSpaces, out _)) errors++; if (Try(row, ix, "SourceYear", out var year) && YearFromPath(relative) is int expected && (!int.TryParse(year, out var actual) || actual != expected)) warnings++; return errors;
    }
    private static int ValidateMedicaid(string[] row, Dictionary<string, int> ix, string relative, NdcAccumulator ndc, ref long warnings)
    {
        var errors = 0; if (!Try(row, ix, "State", out var state) || state.Length != 2 || !state.All(char.IsLetter)) errors++; if (!Try(row, ix, "Year", out var year) || !int.TryParse(year, out var y) || y is < 1990 or > 2100) errors++; else if (YearFromPath(relative) is int expected && y != expected) warnings++; if (!Try(row, ix, "Quarter", out var quarter) || !int.TryParse(quarter, out var q) || q is < 1 or > 4) errors++; Try(row, ix, "Suppression Used", out var suppressed); var isSuppressed = suppressed.Equals("true", StringComparison.OrdinalIgnoreCase) || suppressed == "1"; if (string.IsNullOrWhiteSpace(suppressed) || suppressed is not "true" and not "false" and not "True" and not "False" and not "0" and not "1") warnings++; if (!Try(row, ix, "Number of Prescriptions", out var rx) || string.IsNullOrWhiteSpace(rx)) { if (isSuppressed) warnings++; else errors++; } else if (!decimal.TryParse(rx, NumberStyles.Number | NumberStyles.AllowCurrencySymbol, CultureInfo.InvariantCulture, out var prescriptions)) errors++; else if (prescriptions < 0) warnings++; if (!Try(row, ix, "Total Amount Reimbursed", out var reimb) || string.IsNullOrWhiteSpace(reimb)) { if (isSuppressed) warnings++; else errors++; } else if (!decimal.TryParse(reimb, NumberStyles.Number | NumberStyles.AllowCurrencySymbol, CultureInfo.InvariantCulture, out var reimbursement)) errors++; else if (reimbursement < 0) warnings++; Try(row, ix, "NDC", out var value); ndc.Add(value); if (value.Length != 11 || !value.All(char.IsDigit)) warnings++; return errors;
    }
    private static int ValidateStateReference(string[] row, Dictionary<string, int> ix) => !Try(row, ix, "State (FIPS)", out var fips) || fips.Length != 2 || !fips.All(char.IsDigit) || !Try(row, ix, "Name", out var name) || string.IsNullOrWhiteSpace(name) ? 1 : 0;
    private static int ValidateAdjacency(string[] row, Dictionary<string, int> ix, ref long warnings) { if (!Try(row, ix, "County GEOID", out var a) || a.Length != 5 || !a.All(char.IsDigit) || !Try(row, ix, "Neighbor GEOID", out var b)) return 1; if (string.IsNullOrWhiteSpace(b)) { warnings++; return 0; } return b.Length == 5 && b.All(char.IsDigit) ? 0 : 1; }

    private static RealSourceFileReport ValidateXlsx(string relative, FileInfo info, SourceAssignment assignment, List<string> blockers, List<string> warnings)
    {
        using var zip = ZipFile.OpenRead(info.FullName); var names = zip.Entries.Select(x => x.FullName).ToHashSet(StringComparer.OrdinalIgnoreCase); if (!names.Contains("[Content_Types].xml") || !names.Any(x => x.StartsWith("xl/worksheets/sheet", StringComparison.OrdinalIgnoreCase))) blockers.Add("InvalidXlsxStructure"); warnings.Add("Archival XLSX validated structurally; its converted CSV is the row-validation source."); return new(relative, assignment.Category, false, info.Length, assignment.Sha256, assignment.SchemaProfileVersion, "binary", "n/a", [], 0, 0, 0, 0, warnings.Count, blockers.Count, blockers.Count == 0, null, [], blockers, warnings, []);
    }
    private static RealSourceFileReport ValidateZip(string relative, FileInfo info, SourceAssignment assignment, List<string> blockers, List<string> warnings, CancellationToken token)
    {
        using var zip = ZipFile.OpenRead(info.FullName); long rows = 0, accepted = 0, rejected = 0, expanded = 0; foreach (var entry in zip.Entries) { token.ThrowIfCancellationRequested(); expanded += entry.Length; if (entry.FullName.Contains("..", StringComparison.Ordinal) || Path.IsPathRooted(entry.FullName)) blockers.Add("ArchiveTraversal"); if (entry.FullName.EndsWith(".zip", StringComparison.OrdinalIgnoreCase) || entry.FullName.EndsWith(".gz", StringComparison.OrdinalIgnoreCase)) blockers.Add("NestedArchive"); if (expanded > 500_000_000) blockers.Add("ArchiveExpandedSizeExceeded"); using var reader = new StreamReader(entry.Open(), Encoding.Latin1, true); string? line; while ((line = reader.ReadLine()) is not null) { rows++; if (line.Length == 0) rejected++; else accepted++; } } if (rejected != 0) warnings.Add("Archive contains empty records."); return new(relative, assignment.Category, false, info.Length, assignment.Sha256, assignment.SchemaProfileVersion, "archive-entry-detected", "entry-specific", zip.Entries.Select(x => x.FullName).ToArray(), rows, accepted, rejected, 0, warnings.Count, blockers.Count, blockers.Count == 0, null, [], blockers, warnings, []);
    }

    private static bool IsCanonicalImportSource(string relative, SourceAssignment assignment) => assignment.Category switch
    {
        RealSourceCategory.FdaFirstGeneric => relative.StartsWith("fda/converted/", StringComparison.OrdinalIgnoreCase) && relative.EndsWith(".csv", StringComparison.OrdinalIgnoreCase),
        RealSourceCategory.MedicaidUtilization => assignment.SchemaProfileVersion == "medicaid-data-csv-v1",
        RealSourceCategory.StateReference => relative.EndsWith(".csv", StringComparison.OrdinalIgnoreCase),
        RealSourceCategory.StateAdjacency or RealSourceCategory.RxNormMapping or RealSourceCategory.ManualMapping => true,
        _ => false
    };

    private static (RealSourceCategory? Category, string Profile, string? Warning) Classify(string relative)
    {
        var p = relative.Replace('\\', '/'); if (p.Equals("download_hashes.csv", StringComparison.OrdinalIgnoreCase)) return (null, "audit-ledger-v1", "Audit metadata is not a research source assignment."); if (p.StartsWith("fda/converted/", StringComparison.OrdinalIgnoreCase) && p.EndsWith(".csv", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.FdaFirstGeneric, "fda-first-generic-csv-v1", null); if (p.StartsWith("fda/original/", StringComparison.OrdinalIgnoreCase) && p.EndsWith(".csv", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.FdaFirstGeneric, "fda-first-generic-original-csv-v1", "Duplicate-format archival source; mapping must not double count converted rows."); if (p.StartsWith("fda/original/", StringComparison.OrdinalIgnoreCase) && p.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.FdaFirstGeneric, "fda-first-generic-archival-xlsx-v1", null); if (p.Contains("orange-book", StringComparison.OrdinalIgnoreCase) && p.EndsWith(".zip", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.FdaFirstGeneric, "fda-orange-book-archive-v1", null); if (p.StartsWith("medicaid/original/", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.MedicaidUtilization, "medicaid-data-csv-v1", null); if (p.StartsWith("medicaid/dictionaries/", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.MedicaidUtilization, "medicaid-dictionary-csv-v1", null); if (p.Contains("census_region", StringComparison.OrdinalIgnoreCase) && p.EndsWith(".csv", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.StateReference, "census-region-state-csv-v1", null); if (p.Contains("census_region", StringComparison.OrdinalIgnoreCase) && p.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.StateReference, "census-region-state-archival-xlsx-v1", null); if (p.Contains("adjacency", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.StateAdjacency, "county-adjacency-pipe-v1", null); if (p.StartsWith("mappings/rxnorm/", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.RxNormMapping, "rxnorm-local-v1", null); if (p.StartsWith("mappings/manual/", StringComparison.OrdinalIgnoreCase)) return (RealSourceCategory.ManualMapping, "manual-mapping-v1", null); return (null, "unrecognized", "No source profile candidate.");
    }
    private static string[] RequiredHeaders(string profile) => profile switch { "fda-first-generic-csv-v1" or "fda-first-generic-original-csv-v1" => ["ANDA Number", "Generic Name", "ANDA Applicant", "ANDA Approval Date", "SourceYear"], "medicaid-data-csv-v1" => ["Utilization Type", "State", "NDC", "Package Size", "Year", "Quarter", "Suppression Used", "Product Name", "Number of Prescriptions", "Total Amount Reimbursed"], "medicaid-dictionary-csv-v1" => ["name", "title", "type", "format", "description"], "census-region-state-csv-v1" => ["Region", "Division", "State (FIPS)", "Name"], "county-adjacency-pipe-v1" => ["County Name", "County GEOID", "Neighbor Name", "Neighbor GEOID", "Length"], _ => [] };
    private static bool Try(string[] row, Dictionary<string, int> ix, string name, out string value) { value = string.Empty; if (!ix.TryGetValue(name, out var index) || index >= row.Length) return false; value = row[index].Trim(); return true; }
    private static DateOnly? Coverage(string path, bool start) => YearFromPath(path) is int year ? new DateOnly(year, start ? 1 : 12, start ? 1 : 31) : null;
    private static int? YearFromPath(string path) { var name = Path.GetFileNameWithoutExtension(path); for (var year = 1990; year <= 2100; year++) if (name.Contains(year.ToString(CultureInfo.InvariantCulture), StringComparison.Ordinal)) return year; return null; }
    private static string[] RequiredMissing(IEnumerable<SourceAssignment> items) { var categories = items.Select(x => x.Category).ToHashSet(); return new[] { RealSourceCategory.FdaFirstGeneric, RealSourceCategory.MedicaidUtilization, RealSourceCategory.StateReference, RealSourceCategory.StateAdjacency }.Where(x => !categories.Contains(x)).Select(x => x.ToString()).ToArray(); }
    private static void EnsurePrivateOutput(string root, string output) { var full = Path.GetFullPath(output); if (!full.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase)) throw new ArgumentException("Private manifest must remain below the private root."); Directory.CreateDirectory(Path.GetDirectoryName(full)!); }
    private static void WriteSanitized(string output, object value) { Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!); var json = JsonSerializer.Serialize(value, Json); if (json.Contains(":\\", StringComparison.Ordinal)) throw new InvalidOperationException("Public report contains an absolute path."); File.WriteAllText(output, json, new UTF8Encoding(false)); }
    private static Encoding DetectTextEncoding(string file) { var bytes = new byte[Math.Min(1_048_576, checked((int)Math.Min(new FileInfo(file).Length, int.MaxValue)))]; using var stream = File.OpenRead(file); var count = stream.Read(bytes, 0, bytes.Length); if (count >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF) return new UTF8Encoding(true, true); try { _ = new UTF8Encoding(false, true).GetString(bytes, 0, count); return new UTF8Encoding(false, true); } catch (DecoderFallbackException) { return Encoding.Latin1; } }
    private static ulong Fnv(IEnumerable<string> values) { const ulong offset = 14695981039346656037, prime = 1099511628211; var hash = offset; foreach (var value in values) foreach (var c in value) { hash ^= c; hash *= prime; } return hash; }

    private sealed class NdcAccumulator { private long valid, safe, normalized, ambiguous, invalid, missing; private readonly HashSet<string> originals = [], outputs = []; public bool HasValues => valid + safe + ambiguous + invalid + missing > 0; public void Add(string? value) { if (string.IsNullOrWhiteSpace(value)) { missing++; return; } value = value.Trim(); originals.Add(value); if (value.Length == 11 && value.All(char.IsDigit)) { valid++; normalized++; outputs.Add(value); } else if (value.Count(char.IsDigit) == 10 && value.Contains('-')) safe++; else if (value.Count(char.IsDigit) == 10) ambiguous++; else invalid++; } public NdcQualityReport Report() => new(valid, safe, normalized, ambiguous, invalid, missing, originals.Count, outputs.Count, outputs.Count, originals.Count - outputs.Count); }
}

internal sealed class CsvRecordReader(TextReader reader, char delimiter) : IDisposable
{
    public string[]? ReadRecord() { var fields = new List<string>(); var value = new StringBuilder(); var quoted = false; var any = false; while (true) { var next = reader.Read(); if (next < 0) { if (!any && value.Length == 0 && fields.Count == 0) return null; fields.Add(value.ToString()); return fields.ToArray(); } any = true; var c = (char)next; if (quoted) { if (c == '"') { if (reader.Peek() == '"') { reader.Read(); value.Append('"'); } else quoted = false; } else value.Append(c); } else if (c == '"' && value.Length == 0) quoted = true; else if (c == delimiter) { fields.Add(value.ToString()); value.Clear(); } else if (c == '\n') { fields.Add(value.ToString().TrimEnd('\r')); return fields.ToArray(); } else value.Append(c); } }
    public void Dispose() => reader.Dispose();
}
