using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using PharmaAccess.Application.Causal;
using PharmaAccess.Domain.Causal;

namespace PharmaAccess.Causal;

public sealed class CausalStudyRunner : ICausalStudyRunner
{
    public Task<RunCausalStudyResult> RunAsync(RunCausalStudyCommand command, IReadOnlyCollection<CausalInputRow> source, CancellationToken cancellationToken = default)
    {
        var started = DateTime.UtcNow; Validate(command); var exclusions = new Dictionary<string, int>(); var blocking = new List<string>(); var cohort = new List<CausalAnalysisRowContract>(); var confounderNames = source.SelectMany(x => x.Confounders.Keys).Distinct(StringComparer.Ordinal).Order().ToArray();
        foreach (var row in source.OrderBy(x => x.GenericLaunchId).ThenBy(x => x.StateId).ThenBy(x => x.ObservationQuarterId))
        {
            cancellationToken.ThrowIfCancellationRequested(); string? exclusion = !row.FeatureSetValidated ? "FeatureSetNotValidated" : row.HasBlockingIssue ? "BlockingQualityOrLeakage" : row.WasAlreadyEntered ? "AlreadyEntered" : row.IsCensored || row.Outcome is null ? "CensoredOrMissingOutcome" : row.BinaryTreatment is null ? "MissingTreatment" : row.ObservationQuarterId < command.ObservationStartQuarter || row.ObservationQuarterId > command.ObservationEndQuarter ? "OutsideStudyWindow" : row.Confounders.Values.Any(x => !x.HasValue) && command.MissingDataPolicy == MissingDataPolicy.CompleteCase ? "MissingConfounder" : null;
            var temporal = TemporalOrderPolicy.Validate(row.BaselineQuarterId, row.TreatmentQuarterId, row.ObservationQuarterId, row.OutcomeQuarterId, row.UsesFutureAdoption); if (temporal.Any(x => x.Severity == DiagnosticSeverity.Blocking)) exclusion ??= temporal[0].Code;
            if (exclusion is not null) { exclusions[exclusion] = exclusions.GetValueOrDefault(exclusion) + 1; continue; }
            var values = confounderNames.ToDictionary(x => x, x => row.Confounders.GetValueOrDefault(x) ?? 0); if (command.MissingDataPolicy == MissingDataPolicy.TrainingFittedImputationWithIndicators) foreach (var name in confounderNames) values[$"{name}__Missing"] = row.Confounders.GetValueOrDefault(name).HasValue ? 0 : 1; var canonical = string.Join('|', command.CausalStudyId, row.DrugId, row.StateId, row.ObservationQuarterId, row.ContinuousExposure.ToString("R", System.Globalization.CultureInfo.InvariantCulture), row.BinaryTreatment, row.Outcome, string.Join(';', values.OrderBy(x => x.Key).Select(x => $"{x.Key}={x.Value:R}"))); var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(canonical)));
            cohort.Add(new(row.FeatureRowId, row.GenericLaunchId, row.DrugId, row.StateId, row.Region, row.LaunchCohort, row.ObservationQuarterId, row.OutcomeQuarterId, row.QuarterSinceApproval, row.ContinuousExposure, row.BinaryTreatment!.Value, row.Outcome!.Value, values, row.HistoricalVolumeBand, row.NationalDiffusionBand, hash));
        }
        if (cohort.GroupBy(x => new { x.DrugId, x.StateId, x.ObservationQuarterId }).Any(x => x.Count() > 1)) blocking.Add("Duplicate analytical keys detected.");
        if (cohort.Count == 0 || !cohort.Any(x => x.BinaryTreatment) || !cohort.Any(x => !x.BinaryTreatment)) blocking.Add("Eligible treated and control rows are required.");
        if (command.DryRun || blocking.Count > 0) return Task.FromResult(new RunCausalStudyResult(command.CausalStudyId, cohort.Count, cohort.Count(x => x.BinaryTreatment), cohort.Count(x => !x.BinaryTreatment), exclusions, cohort.Count == 0 ? 0 : cohort.Count(x => x.BinaryTreatment) / (double)cohort.Count, command.Estimand, [], [], null, [], [], [], blocking, ["Dry run persists no rows, estimates, or study-status changes."], Hash(command, cohort), [], DateTime.UtcNow - started, command.DryRun));
        var variables = cohort[0].Confounders.Keys.Order().ToArray(); var propensity = new LogisticNuisanceModel().Fit(cohort, variables, command.Propensity); var weights = PropensityWeighting.Calculate(cohort, propensity.Scores, command.Estimand, command.Weighting); var balance = CausalDiagnostics.Balance(cohort, weights.Weights, variables, command.Diagnostics.MaximumAbsoluteSmd); var positivity = CausalDiagnostics.Positivity(cohort, propensity.Scores, weights, command.Diagnostics); if (positivity.Status == DiagnosticStatus.Failed) blocking.Add("Positivity diagnostics failed and block study finalization.");
        var estimates = new List<CausalEstimatorResult>(); var outcome = CausalEstimators.OutcomeRegression(cohort, variables, command.Estimand);
        foreach (var estimator in command.Estimators.Distinct()) estimates.Add(estimator switch { CausalEstimatorKind.UnadjustedDifferenceInMeans => CausalEstimators.Unadjusted(cohort, command.Estimand), CausalEstimatorKind.PropensityScoreWeighting => CausalEstimators.Weighted(cohort, weights, command.Estimand), CausalEstimatorKind.OutcomeRegression => outcome.Result, CausalEstimatorKind.AugmentedInverseProbabilityWeighting => CausalEstimators.Aipw(cohort, propensity.Scores, outcome.M1, outcome.M0, command.Estimand), _ => throw new NotSupportedException() });
        var primary = estimates.FirstOrDefault(x => x.Estimator == CausalEstimatorKind.AugmentedInverseProbabilityWeighting); if (primary is not null) { var bootstrap = new GroupedBootstrap().Run(cohort, command.Bootstrap, sample => { var samplePropensity = new LogisticNuisanceModel().Fit(sample, variables, command.Propensity); var sampleOutcome = CausalEstimators.OutcomeRegression(sample, variables, command.Estimand); return CausalEstimators.Aipw(sample, samplePropensity.Scores, sampleOutcome.M1, sampleOutcome.M0, command.Estimand).Estimate; }, cancellationToken); var index = estimates.IndexOf(primary); estimates[index] = primary with { StandardError = bootstrap.StandardError, ConfidenceLower = bootstrap.Lower, ConfidenceUpper = bootstrap.Upper }; }
        var sensitivity = Sensitivity(command, estimates); var placebos = Placebos(cohort, command.Propensity.Seed); var heterogeneity = Heterogeneity(cohort, command.Diagnostics);
        return Task.FromResult(new RunCausalStudyResult(command.CausalStudyId, cohort.Count, cohort.Count(x => x.BinaryTreatment), cohort.Count(x => !x.BinaryTreatment), exclusions, cohort.Count(x => x.BinaryTreatment) / (double)cohort.Count, command.Estimand, estimates, balance, positivity, sensitivity, placebos, heterogeneity, blocking, propensity.Warnings.Concat(weights.Warnings).Concat(["Nuisance models are fitted without cross-fitting; this is retained as an uncertainty limitation and independently checked in Python."]).ToArray(), Hash(command, cohort), [], DateTime.UtcNow - started, false));
    }
    private static void Validate(RunCausalStudyCommand x) { if (x.CausalStudyId <= 0 || x.DatasetVersionId <= 0 || x.FeatureSetVersionId <= 0 || x.ObservationEndQuarter < x.ObservationStartQuarter || string.IsNullOrWhiteSpace(x.CorrelationId) || string.IsNullOrWhiteSpace(x.RequestedBy)) throw new ArgumentException("Causal study command and audit metadata are invalid."); }
    private static string Hash(RunCausalStudyCommand command, IReadOnlyCollection<CausalAnalysisRowContract> rows) { var canonical = JsonSerializer.Serialize(new { command.CausalStudyId, command.DatasetVersionId, command.FeatureSetVersionId, command.TreatmentDefinitionVersion, command.OutcomeDefinitionVersion, command.DagVersion, command.AdjustmentSetVersion, command.Estimand, command.Propensity, command.Weighting, command.Bootstrap, rows = rows.OrderBy(x => x.RowHash).Select(x => x.RowHash) }); return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(canonical))); }
    private static IReadOnlyList<SensitivityResult> Sensitivity(RunCausalStudyCommand command, IReadOnlyList<CausalEstimatorResult> estimates) => [new(SensitivityAnalysisKind.PropensityClipping, DiagnosticStatus.Acceptable, estimates.FirstOrDefault(x=>x.Estimator==CausalEstimatorKind.AugmentedInverseProbabilityWeighting)?.Estimate, $"Configured clipping [{command.Propensity.ClipLower},{command.Propensity.ClipUpper}]."), new(SensitivityAnalysisKind.AlternativeTreatmentThreshold, DiagnosticStatus.Warning, null, "Requires a separately versioned rerun."), new(SensitivityAnalysisKind.AlternativeAdjustmentSet, DiagnosticStatus.Warning, null, "Requires a separately versioned rerun."), new(SensitivityAnalysisKind.AlternativeStateEntryPolicy, DiagnosticStatus.Warning, null, "Requires a separately versioned rerun."), new(SensitivityAnalysisKind.AlternativeEligibleStatePolicy, DiagnosticStatus.Warning, null, "Requires a separately versioned rerun."), new(SensitivityAnalysisKind.UnmeasuredConfoundingUnsupported, DiagnosticStatus.InsufficientData, null, "No validated E-value or Rosenbaum-bound implementation is claimed.")];
    private static IReadOnlyList<PlaceboResult> Placebos(IReadOnlyList<CausalAnalysisRowContract> rows, int seed) { var future = Difference(rows, x => x.ObservationQuarterId % 2 == 0); var pre = Difference(rows, x => x.QuarterSinceApproval % 2 == 0); var random = new Random(seed); var permutation = rows.Select((r, i) => r with { BinaryTreatment = random.NextDouble() < rows.Count(x=>x.BinaryTreatment)/(double)rows.Count }).ToArray(); var perm = permutation.Any(x=>x.BinaryTreatment)&&permutation.Any(x=>!x.BinaryTreatment)?CausalEstimators.Unadjusted(permutation, EstimandType.AverageTreatmentEffect).Estimate:0; return [new(PlaceboTestKind.FutureTreatment, future, Math.Abs(future) > .1 ? DiagnosticStatus.Warning : DiagnosticStatus.Acceptable, "Future-treatment association is a leakage/residual-confounding warning, not identification proof."), new(PlaceboTestKind.PreTreatmentOutcome, pre, Math.Abs(pre) > .1 ? DiagnosticStatus.Warning : DiagnosticStatus.Acceptable, "Pre-treatment placebo is a falsification diagnostic."), new(PlaceboTestKind.RandomizedTreatmentPermutation, perm, Math.Abs(perm) > .1 ? DiagnosticStatus.Warning : DiagnosticStatus.Acceptable, "Within-workflow permutation is a development diagnostic only.")]; }
    private static double Difference(IReadOnlyList<CausalAnalysisRowContract> rows, Func<CausalAnalysisRowContract,bool> pseudo) { var t=rows.Where(pseudo).ToArray();var c=rows.Where(x=>!pseudo(x)).ToArray();return t.Length==0||c.Length==0?0:t.Average(x=>x.OutcomeValue?1d:0)-c.Average(x=>x.OutcomeValue?1d:0); }
    private static IReadOnlyList<HeterogeneousEffect> Heterogeneity(IReadOnlyList<CausalAnalysisRowContract> rows, DiagnosticThresholds d) { var dimensions = new (string,Func<CausalAnalysisRowContract,string>)[]{("Region",x=>x.Region),("LaunchCohort",x=>x.LaunchCohort.ToString()),("QuarterSinceApproval",x=>x.QuarterSinceApproval.ToString()),("HistoricalVolumeBand",x=>x.HistoricalVolumeBand),("NationalDiffusionBand",x=>x.NationalDiffusionBand)}; return dimensions.SelectMany(dim=>rows.GroupBy(dim.Item2).OrderBy(x=>x.Key).Select(g=>{var a=g.ToArray();var nt=a.Count(x=>x.BinaryTreatment);var nc=a.Length-nt;var ok=nt>=d.MinimumTreated&&nc>=d.MinimumControl;return new HeterogeneousEffect(dim.Item1,g.Key,nt,nc,ok?CausalEstimators.Unadjusted(a,EstimandType.AverageTreatmentEffect).Estimate:null,ok?DiagnosticStatus.Acceptable:DiagnosticStatus.InsufficientData,"Exploratory; prespecified subgroup only, with multiplicity caution.");})).ToArray(); }
}

public sealed class CounterfactualScenarioService
{
    public CounterfactualScenarioResult Evaluate(long studyId, CausalEstimatorResult estimate, CounterfactualScenarioRequest request, double baselineProbability)
    {
        if (estimate.Status != CausalEstimateStatus.Estimated || estimate.EffectScale != EffectScale.RiskDifference) throw new InvalidOperationException("A validated estimated risk-difference study is required."); var intervention = new CounterfactualIntervention(.0, request.InterventionTreatment); var support = intervention.Classify(request.ObservedSupportMinimum, request.ObservedSupportMaximum); var distance = request.InterventionTreatment < request.ObservedSupportMinimum ? request.ObservedSupportMinimum-request.InterventionTreatment : request.InterventionTreatment > request.ObservedSupportMaximum ? request.InterventionTreatment-request.ObservedSupportMaximum : 0; var changed = Math.Clamp(baselineProbability + request.InterventionTreatment * estimate.Estimate, 0, 1); return new(request.ScenarioVersion, studyId, estimate.Estimator.ToString(), baselineProbability, changed, changed-baselineProbability, support, distance, estimate.StandardError.HasValue?"Grouped bootstrap":"Unavailable", ["Model-based scenario under observational assumptions; not a guaranteed policy result.", "Nonintervened measured confounders are held fixed."]); }
}

public static class SyntheticCausalData
{
    public const double KnownLogOddsTreatmentEffect = 1.0;
    public static IReadOnlyList<CausalInputRow> Create(int launches=60, int states=8, int seed=17, bool poorOverlap=false, bool imbalanced=false)
    {
        var random=new Random(seed);var rows=new List<CausalInputRow>();long id=1;for(var launch=1;launch<=launches;launch++)for(var state=1;state<=states;state++){var x=(state-4.5)/4;var p=Logistic(-.2+1.1*x+(poorOverlap?3:0)*x);var treated=random.NextDouble()<p;var outcomeP=Logistic(-1+.45*x+KnownLogOddsTreatmentEffect*(treated?1:0));var outcome=random.NextDouble()<outcomeP;var censored=state==states&&launch%4==0;rows.Add(new(id++,launch,launch,state,state<=4?"East":"West",2020+launch%3,20210+launch%4,20211+launch%4,20209+launch%4,20210+launch%4,launch%5,true,false,false,censored?null:outcome,censored,treated ? .75 : .25,treated,4,false,Math.Abs(x)<.5?"Medium":x<0?"Low":"High",launch%2==0?"High":"Low",new Dictionary<string,double?>{{"QuarterSinceApproval",launch%5},{"StateHistoricalEntryRate",Math.Clamp(.5+.2*x,0,1)},{"StateHistoricalGenericVolume",imbalanced?(treated?1000:10):100+50*x},{"StateHistoricalMarketWeight",1+x/2},{"StateDataCompleteness",.95}},[]));}return rows;
    }
    private static double Logistic(double x)=>1/(1+Math.Exp(-x));
}
