using System.Collections;
using System.Data.Common;
using System.Diagnostics;
using Microsoft.Data.SqlClient;

namespace PharmaAccess.Data.Research;

public sealed record BulkBenchmarkResult(int BatchSize,long Rows,double RowsPerSecond,TimeSpan Elapsed,double PeakMemoryMiB,int SqlCommandCount,int TransactionCount,long FinalRowCount,bool Reconciled);
public static class BulkImportBenchmark
{
    public static async Task<IReadOnlyList<BulkBenchmarkResult>> RunAsync(string connectionString,long rows,CancellationToken ct)
    {
        await using var connection=new SqlConnection(connectionString);await connection.OpenAsync(ct);await using(var create=connection.CreateCommand()){create.CommandText="CREATE TABLE #MedicaidBulkBenchmark(SourceFileId int NOT NULL,SourceRowNumber bigint NOT NULL,NdcRaw nvarchar(128) NULL,ParsedPrescriptionCount bigint NULL,ParsedReimbursementAmount decimal(19,4) NULL,ParseStatus nvarchar(32) NOT NULL,ImportedAtUtc datetime2 NOT NULL);";await create.ExecuteNonQueryAsync(ct);}var results=new List<BulkBenchmarkResult>();
        foreach(var size in new[]{20000,50000,100000}){await using(var truncate=connection.CreateCommand()){truncate.CommandText="TRUNCATE TABLE #MedicaidBulkBenchmark";await truncate.ExecuteNonQueryAsync(ct);}var sw=Stopwatch.StartNew();double peak=0;var transactions=0;for(long start=1;start<=rows;start+=size){var count=(int)Math.Min(size,rows-start+1);await using var tx=(SqlTransaction)await connection.BeginTransactionAsync(ct);using var reader=new SyntheticReader(start,count);using var bulk=new SqlBulkCopy(connection,SqlBulkCopyOptions.TableLock|SqlBulkCopyOptions.CheckConstraints,tx){DestinationTableName="#MedicaidBulkBenchmark",EnableStreaming=true,BatchSize=count,BulkCopyTimeout=0};foreach(var name in SyntheticReader.Columns)bulk.ColumnMappings.Add(name,name);await bulk.WriteToServerAsync(reader,ct);await tx.CommitAsync(ct);transactions++;peak=Math.Max(peak,Environment.WorkingSet/1048576d);}sw.Stop();long final;await using(var countCommand=connection.CreateCommand()){countCommand.CommandText="SELECT COUNT_BIG(*) FROM #MedicaidBulkBenchmark";final=(long)(await countCommand.ExecuteScalarAsync(ct))!;}results.Add(new(size,rows,rows/sw.Elapsed.TotalSeconds,sw.Elapsed,peak,transactions+2,transactions,final,final==rows));}return results;
    }
    private sealed class SyntheticReader(long start,int count):DbDataReader
    {public static readonly string[] Columns=["SourceFileId","SourceRowNumber","NdcRaw","ParsedPrescriptionCount","ParsedReimbursementAmount","ParseStatus","ImportedAtUtc"];private int index=-1;public override bool Read()=>++index<count;public override int FieldCount=>Columns.Length;public override object GetValue(int ordinal)=>ordinal switch{0=>1,1=>start+index,2=>"12345678901",3=>10L,4=>12.34m,5=>"Parsed",6=>DateTime.UnixEpoch,_=>DBNull.Value};public override string GetName(int i)=>Columns[i];public override int GetOrdinal(string n)=>Array.IndexOf(Columns,n);public override bool IsDBNull(int i)=>false;public override int GetValues(object[] v){for(var i=0;i<FieldCount;i++)v[i]=GetValue(i);return FieldCount;}public override Type GetFieldType(int i)=>GetValue(i).GetType();public override string GetDataTypeName(int i)=>GetFieldType(i).Name;public override bool HasRows=>count>0;public override int Depth=>0;public override bool IsClosed=>false;public override int RecordsAffected=>-1;public override object this[int i]=>GetValue(i);public override object this[string n]=>GetValue(GetOrdinal(n));public override bool NextResult()=>false;public override IEnumerator GetEnumerator()=>Enumerable.Range(0,count).GetEnumerator();public override bool GetBoolean(int i)=>(bool)GetValue(i);public override byte GetByte(int i)=>(byte)GetValue(i);public override long GetBytes(int i,long o,byte[]? b,int bo,int l)=>throw new NotSupportedException();public override char GetChar(int i)=>(char)GetValue(i);public override long GetChars(int i,long o,char[]? b,int bo,int l)=>throw new NotSupportedException();public override Guid GetGuid(int i)=>(Guid)GetValue(i);public override short GetInt16(int i)=>Convert.ToInt16(GetValue(i));public override int GetInt32(int i)=>Convert.ToInt32(GetValue(i));public override long GetInt64(int i)=>Convert.ToInt64(GetValue(i));public override float GetFloat(int i)=>Convert.ToSingle(GetValue(i));public override double GetDouble(int i)=>Convert.ToDouble(GetValue(i));public override string GetString(int i)=>(string)GetValue(i);public override decimal GetDecimal(int i)=>Convert.ToDecimal(GetValue(i));public override DateTime GetDateTime(int i)=>(DateTime)GetValue(i);}
}
