using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using PharmaAccess.Application.Research;
using PharmaAccess.Data.Entities;
using PharmaAccess.Domain.Entities;
using PharmaAccess.Domain.Research;
using PharmaAccess.Domain.ValueObjects;

namespace PharmaAccess.Data.Research;

public sealed class EfResearchImportPersistence(PharmaAccessDbContext db):IResearchImportPersistence
{
    public async Task<ImportSession> InitializeAsync(ImportInitialization r,CancellationToken ct)
    {
        var resumed=await db.ResearchImportRuns.AsNoTracking().SingleOrDefaultAsync(x=>x.CorrelationId==r.CorrelationId,ct);if(resumed is not null){if(resumed.SourceManifestHash!=r.ManifestHash||resumed.Status is not("Importing"or"Failed"))throw new InvalidOperationException("Existing import run is incompatible with resume.");var resumedSources=await db.SourceFiles.AsNoTracking().Where(x=>x.DatasetVersionId==resumed.DatasetVersionId).ToDictionaryAsync(x=>x.Sha256,x=>x.SourceFileId,StringComparer.OrdinalIgnoreCase,ct);return new(resumed.ResearchImportRunId,resumed.DatasetVersionId,resumedSources);}
        var at=DateTime.UtcNow;var plan=ResearchImportInitializationFactory.Build(r,at);
        await using var tx=await db.Database.BeginTransactionAsync(ct);try{var protocol=await db.ResearchProtocols.SingleOrDefaultAsync(x=>x.ResearchProtocolId==r.ProtocolId,ct)??throw new InvalidOperationException("Protocol not found.");if(protocol.Status!=ResearchProtocolStatus.Approved)throw new InvalidOperationException("An approved real protocol is required.");if(await db.DatasetVersions.AnyAsync(x=>x.VersionCode==new DatasetVersionCode(r.VersionCode),ct))throw new InvalidOperationException("Dataset version already exists.");
        db.DatasetVersions.Add(plan.Dataset);await db.SaveChangesAsync(ct);var ids=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);
        foreach(var item in plan.Sources){var s=item.Source;db.ResearchSourceRegistrations.Add(item.Registration);if(ids.ContainsKey(s.Sha256))continue;if(await db.SourceFiles.AnyAsync(x=>x.Sha256==s.Sha256,ct))throw new InvalidOperationException("Source hash is already registered to another dataset version.");var source=new SourceFile(plan.Dataset.DatasetVersionId,Type(s.Kind),item.File.OriginalFileName,s.Sha256,s.ByteSize,s.SchemaVersion,at,rowCount:s.ExpectedRows,reportingPeriod:item.File.ReportingPeriod,licenseNote:item.File.LicenseNote);db.SourceFiles.Add(source);await db.SaveChangesAsync(ct);ids[s.Sha256]=source.SourceFileId;}
        plan.Run.DatasetVersionId=plan.Dataset.DatasetVersionId;db.ResearchImportRuns.Add(plan.Run);await db.SaveChangesAsync(ct);plan.Audit.ResearchImportRunId=plan.Run.ResearchImportRunId;db.ResearchImportAuditEvents.Add(plan.Audit);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return new(plan.Run.ResearchImportRunId,plan.Dataset.DatasetVersionId,ids);}catch{await tx.RollbackAsync(CancellationToken.None);db.ChangeTracker.Clear();throw;}
    }

    public async Task<ImportBatchResult> PersistBatchAsync(ImportSession session,ImportBatch batch,CancellationToken ct)
    {
        if(!session.SourceFileIds.TryGetValue(batch.SourceSha256,out var sourceId))throw new InvalidOperationException("Unregistered source hash.");var existing=await db.ResearchImportCheckpoints.SingleOrDefaultAsync(x=>x.ResearchImportRunId==session.ImportRunId&&x.SourceFileId==sourceId,ct);if(existing is not null){if(existing.SourceSha256!=batch.SourceSha256)throw new InvalidOperationException("Source hash changed after checkpoint.");if(existing.LastCompletedBatch>=batch.BatchNumber)return Count(batch.Rows,existing.LastCompletedRow);}
        await using var tx=await db.Database.BeginTransactionAsync(ct);long accepted=0,rejected=0,duplicate=0,excluded=0,last=0;foreach(var row in batch.Rows.OrderBy(x=>x.SourceRowNumber)){ct.ThrowIfCancellationRequested();last=row.SourceRowNumber;switch(row.Disposition){case ImportRowDisposition.Accepted:AddRaw(batch.Kind,sourceId,row);accepted++;AddMappingIfNeeded(session.ImportRunId,sourceId,row);break;case ImportRowDisposition.Rejected:AddRejected(session.ImportRunId,sourceId,row,"Rejected");rejected++;break;case ImportRowDisposition.Duplicate:AddRejected(session.ImportRunId,sourceId,row,"Duplicate");duplicate++;break;case ImportRowDisposition.ExplicitlyExcluded:AddRejected(session.ImportRunId,sourceId,row,"ExplicitlyExcluded");excluded++;break;}}
        if(existing is null)db.ResearchImportCheckpoints.Add(new(){ResearchImportRunId=session.ImportRunId,SourceFileId=sourceId,SourceSha256=batch.SourceSha256,LastCompletedRow=last,LastCompletedBatch=batch.BatchNumber,AggregateHash=batch.AggregateHash,UpdatedAtUtc=DateTime.UtcNow});else{existing.LastCompletedRow=last;existing.LastCompletedBatch=batch.BatchNumber;existing.AggregateHash=batch.AggregateHash;existing.UpdatedAtUtc=DateTime.UtcNow;}db.ResearchImportAuditEvents.Add(new(){ResearchImportRunId=session.ImportRunId,EventType="BatchCommitted",DetailJson=JsonSerializer.Serialize(new{sourceId,batch.BatchNumber,last,accepted,rejected,duplicate,excluded}),CreatedAtUtc=DateTime.UtcNow});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return new(accepted,rejected,duplicate,excluded,last);
    }

    public async Task CompleteAsync(ImportSession session,ImportCompletion c,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(ct);var run=await db.ResearchImportRuns.SingleAsync(x=>x.ResearchImportRunId==session.ImportRunId,ct);run.Status="MappingReview";run.CompletedAtUtc=DateTime.UtcNow;var dataset=await db.DatasetVersions.SingleAsync(x=>x.DatasetVersionId==session.DatasetVersionId,ct);dataset.MarkValidating();db.ResearchImportAuditEvents.Add(new(){ResearchImportRunId=session.ImportRunId,EventType="ImportReconciled",DetailJson=JsonSerializer.Serialize(c),CreatedAtUtc=DateTime.UtcNow});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}
    public async Task<ImportCheckpoint?> GetCheckpointAsync(long runId,string hash,CancellationToken ct){var x=await db.ResearchImportCheckpoints.AsNoTracking().SingleOrDefaultAsync(y=>y.ResearchImportRunId==runId&&y.SourceSha256==hash,ct);return x is null?null:new(runId.ToString(CultureInfo.InvariantCulture),x.SourceSha256,x.LastCompletedRow,x.LastCompletedBatch,x.AggregateHash);}

    private void AddRaw(ImportSourceKind kind,int sourceId,RawImportRow r){string? V(string k)=>r.Values.TryGetValue(k,out var x)?x:null;var now=DateTime.UtcNow;if(kind==ImportSourceKind.Fda)db.FdaFirstGenericApprovalRawRecords.Add(new(sourceId,r.SourceRowNumber,V("ANDA Number"),V("Generic Name"),null,null,V("ANDA Applicant"),V("ANDA Approval Date"),DateTime.TryParse(V("ANDA Approval Date"),CultureInfo.InvariantCulture,out var d)?d:null,RawParseStatus.Parsed,null,null,now));else if(kind==ImportSourceKind.Medicaid){var suppressed=V("Suppression Used") is "true" or "True" or "1";long? rx=!suppressed&&long.TryParse(V("Number of Prescriptions"),out var p)?p:null;decimal? reimb=!suppressed&&decimal.TryParse(V("Total Amount Reimbursed"),NumberStyles.Number|NumberStyles.AllowCurrencySymbol,CultureInfo.InvariantCulture,out var a)?a:null;db.MedicaidStateDrugUtilizationRawRecords.Add(new(sourceId,r.SourceRowNumber,V("Utilization Type"),V("State"),V("NDC"),V("Product Name"),V("Package Size"),V("Year"),V("Quarter"),V("Number of Prescriptions"),V("Total Amount Reimbursed"),int.TryParse(V("Year"),out var y)?y:null,int.TryParse(V("Quarter"),out var q)?q:null,rx,reimb,RawParseStatus.Parsed,null,null,now));}else db.ResearchReferenceRawRecords.Add(new(){SourceFileId=sourceId,SourceRowNumber=r.SourceRowNumber,RawValuesJson=JsonSerializer.Serialize(r.Values),ImportedAtUtc=now});}
    private void AddRejected(long run,int source,RawImportRow row,string classification)=>db.ResearchRejectedRows.Add(new(){ResearchImportRunId=run,SourceFileId=source,SourceRowNumber=row.SourceRowNumber,Classification=classification,ReasonCode=row.ReasonCode??classification,EvidenceJson=row.EvidenceJson??"{}",RecordedAtUtc=DateTime.UtcNow});
    private void AddMappingIfNeeded(long run,int source,RawImportRow row){if(row.MappingStatus is not("Ambiguous"or"Invalid"))return;var value=row.Values.TryGetValue("NDC",out var ndc)?ndc??"": "";db.ResearchMappingReviews.Add(new(){ResearchImportRunId=run,SourceFileId=source,SourceRowNumber=row.SourceRowNumber,MappingType="NDC",Status=row.MappingStatus,SourceValueHash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))),EvidenceJson="{}",CreatedAtUtc=DateTime.UtcNow});}
    private static ImportBatchResult Count(IReadOnlyList<RawImportRow> rows,long last)=>new(rows.Count(x=>x.Disposition==ImportRowDisposition.Accepted),rows.Count(x=>x.Disposition==ImportRowDisposition.Rejected),rows.Count(x=>x.Disposition==ImportRowDisposition.Duplicate),rows.Count(x=>x.Disposition==ImportRowDisposition.ExplicitlyExcluded),last);
    private static SourceType Type(ImportSourceKind k)=>k switch{ImportSourceKind.Fda=>SourceType.FDAFirstGeneric,ImportSourceKind.Medicaid=>SourceType.MedicaidStateDrugUtilization,_=>SourceType.StateReference};
}
