using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Data.SqlClient;
using PharmaAccess.Application.Research;
using PharmaAccess.Data.Entities;
using PharmaAccess.Domain.Entities;
using PharmaAccess.Domain.Research;
using PharmaAccess.Domain.ValueObjects;

namespace PharmaAccess.Data.Research;

public sealed class EfResearchImportPersistence(PharmaAccessDbContext db):IResearchImportPersistence
{
    public async Task<ImportSession> InitializeAsync(ImportInitialization r,CancellationToken ct)
    {
        var resumed=await db.ResearchImportRuns.AsNoTracking().SingleOrDefaultAsync(x=>x.CorrelationId==r.CorrelationId,ct);if(resumed is not null){await ValidateResumeCoreAsync(r,resumed,ct);if(string.IsNullOrWhiteSpace(r.ResumeAuditId))throw new InvalidOperationException("A new resume audit ID is required.");await using var resumeTx=await db.Database.BeginTransactionAsync(ct);db.ResearchImportAuditEvents.Add(new(){ResearchImportRunId=resumed.ResearchImportRunId,EventType="ResumeStarted",DetailJson=JsonSerializer.Serialize(new{previousCorrelationId=r.CorrelationId,resumeAuditId=r.ResumeAuditId}),CreatedAtUtc=DateTime.UtcNow});await db.SaveChangesAsync(ct);await resumeTx.CommitAsync(ct);db.ChangeTracker.Clear();var resumedSources=await db.SourceFiles.AsNoTracking().Where(x=>x.DatasetVersionId==resumed.DatasetVersionId).ToDictionaryAsync(x=>x.Sha256,x=>x.SourceFileId,StringComparer.OrdinalIgnoreCase,ct);return new(resumed.ResearchImportRunId,resumed.DatasetVersionId,resumedSources);}
        var at=DateTime.UtcNow;var plan=ResearchImportInitializationFactory.Build(r,at);
        await using var tx=await db.Database.BeginTransactionAsync(ct);try{var protocol=await db.ResearchProtocols.SingleOrDefaultAsync(x=>x.ResearchProtocolId==r.ProtocolId,ct)??throw new InvalidOperationException("Protocol not found.");if(protocol.Status!=ResearchProtocolStatus.Approved)throw new InvalidOperationException("An approved real protocol is required.");if(await db.DatasetVersions.AnyAsync(x=>x.VersionCode==new DatasetVersionCode(r.VersionCode),ct))throw new InvalidOperationException("Dataset version already exists.");
        db.DatasetVersions.Add(plan.Dataset);await db.SaveChangesAsync(ct);var ids=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);
        foreach(var item in plan.Sources){var s=item.Source;db.ResearchSourceRegistrations.Add(item.Registration);if(ids.ContainsKey(s.Sha256))continue;if(await db.SourceFiles.AnyAsync(x=>x.Sha256==s.Sha256,ct))throw new InvalidOperationException("Source hash is already registered to another dataset version.");var source=new SourceFile(plan.Dataset.DatasetVersionId,Type(s.Kind),item.File.OriginalFileName,s.Sha256,s.ByteSize,s.SchemaVersion,at,rowCount:s.ExpectedRows,reportingPeriod:item.File.ReportingPeriod,licenseNote:item.File.LicenseNote);db.SourceFiles.Add(source);await db.SaveChangesAsync(ct);ids[s.Sha256]=source.SourceFileId;}
        plan.Run.DatasetVersionId=plan.Dataset.DatasetVersionId;db.ResearchImportRuns.Add(plan.Run);await db.SaveChangesAsync(ct);plan.Audit.ResearchImportRunId=plan.Run.ResearchImportRunId;db.ResearchImportAuditEvents.Add(plan.Audit);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return new(plan.Run.ResearchImportRunId,plan.Dataset.DatasetVersionId,ids);}catch{await tx.RollbackAsync(CancellationToken.None);db.ChangeTracker.Clear();throw;}
    }

    public async Task<(long RowsCommitted,string NextSource,long NextRow,long Remaining)> ValidateResumeAsync(ImportInitialization r,CancellationToken ct){var run=await db.ResearchImportRuns.AsNoTracking().SingleOrDefaultAsync(x=>x.CorrelationId==r.CorrelationId,ct)??throw new InvalidOperationException("Previous import correlation does not exist.");await ValidateResumeCoreAsync(r,run,ct);var files=await db.SourceFiles.AsNoTracking().Where(x=>x.DatasetVersionId==run.DatasetVersionId).ToArrayAsync(ct);var checkpoints=await db.ResearchImportCheckpoints.AsNoTracking().Where(x=>x.ResearchImportRunId==run.ResearchImportRunId).ToArrayAsync(ct);long committed=0;foreach(var source in r.Sources.Where(x=>x.Canonical)){var file=files.First(x=>x.Sha256==source.Sha256);committed+=checkpoints.FirstOrDefault(x=>x.SourceFileId==file.SourceFileId)?.LastCompletedRow??0;}var next=r.Sources.Where(x=>x.Canonical).Select(x=>(Source:x,Row:checkpoints.FirstOrDefault(c=>c.SourceFileId==files.First(f=>f.Sha256==x.Sha256).SourceFileId)?.LastCompletedRow??0)).FirstOrDefault(x=>x.Row<x.Source.ExpectedRows);var remaining=r.Sources.Where(x=>x.Canonical).Sum(x=>x.ExpectedRows)-committed;return(committed,next.Source?.RelativePath??"none",next.Row+1,remaining);}
    private async Task ValidateResumeCoreAsync(ImportInitialization r,ResearchImportRunEntity run,CancellationToken ct){var dataset=await db.DatasetVersions.AsNoTracking().SingleAsync(x=>x.DatasetVersionId==run.DatasetVersionId,ct);if(dataset.VersionCode!=new DatasetVersionCode(r.VersionCode))throw new InvalidOperationException("Resume dataset version mismatch.");if(run.ResearchProtocolId!=r.ProtocolId)throw new InvalidOperationException("Resume protocol mismatch.");if(run.SourceManifestHash!=r.ManifestHash||run.Status is not("Importing"or"Failed"))throw new InvalidOperationException("Existing import run is incompatible with resume.");var files=await db.SourceFiles.AsNoTracking().Where(x=>x.DatasetVersionId==run.DatasetVersionId).ToArrayAsync(ct);foreach(var source in r.Sources.Where(x=>x.Canonical)){var file=files.SingleOrDefault(x=>x.Sha256==source.Sha256)??throw new InvalidOperationException($"Resume source hash is not registered: {source.RelativePath}");if(file.SchemaVersion!=source.SchemaVersion)throw new InvalidOperationException($"Resume schema profile mismatch: {source.RelativePath}");var checkpoint=await db.ResearchImportCheckpoints.AsNoTracking().SingleOrDefaultAsync(x=>x.ResearchImportRunId==run.ResearchImportRunId&&x.SourceFileId==file.SourceFileId,ct);if(checkpoint is null)continue;if(checkpoint.SourceSha256!=source.Sha256)throw new InvalidOperationException($"Checkpoint/source mismatch: {source.RelativePath}");long? max=source.Kind switch{ImportSourceKind.Fda=>await db.FdaFirstGenericApprovalRawRecords.Where(x=>x.SourceFileId==file.SourceFileId).MaxAsync(x=>(long?)x.SourceRowNumber,ct),ImportSourceKind.Medicaid=>await db.MedicaidStateDrugUtilizationRawRecords.Where(x=>x.SourceFileId==file.SourceFileId).MaxAsync(x=>(long?)x.SourceRowNumber,ct),_=>await db.ResearchReferenceRawRecords.Where(x=>x.SourceFileId==file.SourceFileId).MaxAsync(x=>(long?)x.SourceRowNumber,ct)};if(max.HasValue&&max.Value>checkpoint.LastCompletedRow)throw new InvalidOperationException($"Raw row exists beyond checkpoint: {source.RelativePath}");if(checkpoint.LastCompletedRow>source.ExpectedRows)throw new InvalidOperationException($"Checkpoint exceeds validated source rows: {source.RelativePath}");}}

    public async Task<ImportBatchResult> PersistBatchAsync(ImportSession session,ImportBatch batch,CancellationToken ct)
    {
        if(!session.SourceFileIds.TryGetValue(batch.SourceSha256,out var sourceId))throw new InvalidOperationException("Unregistered source hash.");var existing=await db.ResearchImportCheckpoints.SingleOrDefaultAsync(x=>x.ResearchImportRunId==session.ImportRunId&&x.SourceFileId==sourceId,ct);if(existing is not null&&existing.SourceSha256!=batch.SourceSha256)throw new InvalidOperationException("Source hash changed after checkpoint.");var prior=existing?.LastCompletedRow??0;var all=batch.Rows.OrderBy(x=>x.SourceRowNumber).ToArray();var pending=all.Where(x=>x.SourceRowNumber>prior).ToArray();if(pending.Length==0)return Count(all,prior,existing?.ResearchImportCheckpointId??0);
        ct.ThrowIfCancellationRequested();await using var tx=await db.Database.BeginTransactionAsync(ct);try{var accepted=pending.LongCount(x=>x.Disposition==ImportRowDisposition.Accepted);var rejected=pending.LongCount(x=>x.Disposition==ImportRowDisposition.Rejected);var duplicate=pending.LongCount(x=>x.Disposition==ImportRowDisposition.Duplicate);var excluded=pending.LongCount(x=>x.Disposition==ImportRowDisposition.ExplicitlyExcluded);var last=pending[^1].SourceRowNumber;
        if(batch.Kind is ImportSourceKind.Fda or ImportSourceKind.Medicaid)await BulkRawAsync(batch.Kind,sourceId,pending,tx,ct);else foreach(var row in pending.Where(x=>x.Disposition==ImportRowDisposition.Accepted))AddRaw(batch.Kind,sourceId,row);
        foreach(var row in pending){switch(row.Disposition){case ImportRowDisposition.Accepted:AddMappingIfNeeded(session.ImportRunId,sourceId,row);break;case ImportRowDisposition.Rejected:AddRejected(session.ImportRunId,sourceId,row,"Rejected");break;case ImportRowDisposition.Duplicate:AddRejected(session.ImportRunId,sourceId,row,"Duplicate");break;case ImportRowDisposition.ExplicitlyExcluded:AddRejected(session.ImportRunId,sourceId,row,"ExplicitlyExcluded");break;}}
        if(existing is null){existing=new(){ResearchImportRunId=session.ImportRunId,SourceFileId=sourceId,SourceSha256=batch.SourceSha256};db.ResearchImportCheckpoints.Add(existing);}existing.LastCompletedRow=last;existing.LastCompletedBatch=batch.BatchNumber;existing.AggregateHash=batch.AggregateHash;existing.UpdatedAtUtc=DateTime.UtcNow;db.ResearchImportAuditEvents.Add(new(){ResearchImportRunId=session.ImportRunId,EventType="BulkBatchCommitted",DetailJson=JsonSerializer.Serialize(new{sourceId,batch.BatchNumber,last,accepted,rejected,duplicate,excluded,batchSize=pending.Length}),CreatedAtUtc=DateTime.UtcNow});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);var checkpointId=existing.ResearchImportCheckpointId;db.ChangeTracker.Clear();var full=Count(all,last,checkpointId);return full;}catch{await tx.RollbackAsync(CancellationToken.None);db.ChangeTracker.Clear();throw;}
    }

    private async Task BulkRawAsync(ImportSourceKind kind,int sourceId,IReadOnlyList<RawImportRow> rows,Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction efTransaction,CancellationToken ct)
    {
        var connection=(SqlConnection)db.Database.GetDbConnection();var transaction=(SqlTransaction)efTransaction.GetDbTransaction();using var reader=new RawImportBulkDataReader(kind,sourceId,rows,DateTime.UtcNow);if(!reader.HasRows)return;using var bulk=new SqlBulkCopy(connection,SqlBulkCopyOptions.TableLock|SqlBulkCopyOptions.CheckConstraints,transaction){DestinationTableName=kind==ImportSourceKind.Fda?"[raw].[FdaFirstGenericApprovalRaw]":"[raw].[MedicaidStateDrugUtilizationRaw]",EnableStreaming=true,BatchSize=rows.Count,BulkCopyTimeout=0,NotifyAfter=Math.Min(50000,rows.Count)};var columns=kind==ImportSourceKind.Fda?RawImportBulkDataReader.FdaColumns:RawImportBulkDataReader.MedicaidColumns;foreach(var column in columns)bulk.ColumnMappings.Add(column,column);await bulk.WriteToServerAsync(reader,ct);
    }

    public async Task CompleteAsync(ImportSession session,ImportCompletion c,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(ct);var run=await db.ResearchImportRuns.SingleAsync(x=>x.ResearchImportRunId==session.ImportRunId,ct);var sourceIds=session.SourceFileIds.Values.Distinct().ToArray();var registered=await db.ResearchImportCheckpoints.Where(x=>x.ResearchImportRunId==session.ImportRunId).SumAsync(x=>x.LastCompletedRow,ct);var accepted=await db.FdaFirstGenericApprovalRawRecords.LongCountAsync(x=>sourceIds.Contains(x.SourceFileId),ct)+await db.MedicaidStateDrugUtilizationRawRecords.LongCountAsync(x=>sourceIds.Contains(x.SourceFileId),ct)+await db.ResearchReferenceRawRecords.LongCountAsync(x=>sourceIds.Contains(x.SourceFileId),ct);var rejected=await db.ResearchRejectedRows.LongCountAsync(x=>x.ResearchImportRunId==session.ImportRunId&&x.Classification=="Rejected",ct);var duplicate=await db.ResearchRejectedRows.LongCountAsync(x=>x.ResearchImportRunId==session.ImportRunId&&x.Classification=="Duplicate",ct);var excluded=await db.ResearchRejectedRows.LongCountAsync(x=>x.ResearchImportRunId==session.ImportRunId&&x.Classification=="ExplicitlyExcluded",ct);if(registered!=accepted+rejected+duplicate+excluded)throw new InvalidOperationException("Database reconciliation identity failed; dataset remains non-final.");var actual=new ImportCompletion(registered,accepted,rejected,duplicate,excluded,ReconciliationHasher.Hash(registered,accepted,rejected,duplicate,excluded),c.ProfileJson);run.Status="MappingReview";run.CompletedAtUtc=DateTime.UtcNow;var dataset=await db.DatasetVersions.SingleAsync(x=>x.DatasetVersionId==session.DatasetVersionId,ct);dataset.MarkValidating();db.ResearchImportAuditEvents.Add(new(){ResearchImportRunId=session.ImportRunId,EventType="ImportReconciled",DetailJson=JsonSerializer.Serialize(actual),CreatedAtUtc=DateTime.UtcNow});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}
    public async Task<ImportCheckpoint?> GetCheckpointAsync(long runId,string hash,CancellationToken ct){var x=await db.ResearchImportCheckpoints.AsNoTracking().SingleOrDefaultAsync(y=>y.ResearchImportRunId==runId&&y.SourceSha256==hash,ct);return x is null?null:new(runId.ToString(CultureInfo.InvariantCulture),x.SourceSha256,x.LastCompletedRow,x.LastCompletedBatch,x.AggregateHash);}

    private void AddRaw(ImportSourceKind kind,int sourceId,RawImportRow r){if(kind is ImportSourceKind.Fda or ImportSourceKind.Medicaid)throw new InvalidOperationException("FDA and Medicaid raw rows must use SqlBulkCopy.");db.ResearchReferenceRawRecords.Add(new(){SourceFileId=sourceId,SourceRowNumber=r.SourceRowNumber,RawValuesJson=JsonSerializer.Serialize(r.Values),ImportedAtUtc=DateTime.UtcNow});}
    private void AddRejected(long run,int source,RawImportRow row,string classification)=>db.ResearchRejectedRows.Add(new(){ResearchImportRunId=run,SourceFileId=source,SourceRowNumber=row.SourceRowNumber,Classification=classification,ReasonCode=row.ReasonCode??classification,EvidenceJson=row.EvidenceJson??"{}",RecordedAtUtc=DateTime.UtcNow});
    private void AddMappingIfNeeded(long run,int source,RawImportRow row){if(row.MappingStatus is not("Ambiguous"or"Invalid"))return;var value=row.Values.TryGetValue("NDC",out var ndc)?ndc??"": "";db.ResearchMappingReviews.Add(new(){ResearchImportRunId=run,SourceFileId=source,SourceRowNumber=row.SourceRowNumber,MappingType="NDC",Status=row.MappingStatus,SourceValueHash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))),EvidenceJson="{}",CreatedAtUtc=DateTime.UtcNow});}
    private static ImportBatchResult Count(IReadOnlyList<RawImportRow> rows,long last,long checkpointId)=>new(rows.Count(x=>x.Disposition==ImportRowDisposition.Accepted),rows.Count(x=>x.Disposition==ImportRowDisposition.Rejected),rows.Count(x=>x.Disposition==ImportRowDisposition.Duplicate),rows.Count(x=>x.Disposition==ImportRowDisposition.ExplicitlyExcluded),last,checkpointId);
    private static SourceType Type(ImportSourceKind k)=>k switch{ImportSourceKind.Fda=>SourceType.FDAFirstGeneric,ImportSourceKind.Medicaid=>SourceType.MedicaidStateDrugUtilization,_=>SourceType.StateReference};
}
