using System.Data;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using PharmaAccess.Data.Entities;
using PharmaAccess.Domain.Research;

namespace PharmaAccess.Data.Research;

public sealed record FdaReferenceImportResult(long OrangeBookProducts,long DrugsFdaApplications,long DrugsFdaProducts,long DrugsFdaMarketingStatuses,long DrugsFdaTherapeuticEquivalences,long NdcProducts,long NdcPackages);

public sealed class FdaReferenceImportService(PharmaAccessDbContext db)
{
    private const int BatchSize=5000;
    public async Task<FdaReferenceImportResult> ImportAsync(string repositoryRoot,string snapshotCode,CancellationToken ct)
    {
        repositoryRoot=Path.GetFullPath(repositoryRoot);var root=Path.Combine(repositoryRoot,"data","private","reference",snapshotCode);
        var orangeZip=Path.Combine(root,"orange-book","EOBZIP_2026_06.zip");var orange=Path.Combine(root,"orange-book","EOBZIP_2026_06","products.txt");
        var drugsZip=Path.Combine(root,"drugs-at-fda","dafdata20260717.zip");var drugs=Path.Combine(root,"drugs-at-fda","dafdata20260717");
        var ndcZip=Path.Combine(root,"ndc-directory","drug-ndc-0001-of-0001.json.zip");var ndc=Directory.GetFiles(Path.Combine(root,"ndc-directory","drug-ndc-0001-of-0001.json"),"*.json").Single();
        foreach(var path in new[]{orangeZip,orange,drugsZip,ndcZip,ndc})if(!File.Exists(path))throw new FileNotFoundException("Required frozen reference asset is absent.",Path.GetFileName(path));
        var protocol=await db.ResearchProtocols.SingleAsync(x=>x.ProtocolCode=="approval-to-access-real"&&x.ProtocolVersion=="1.1",ct);if(protocol.Status!=ResearchProtocolStatus.Approved)throw new InvalidOperationException("Approved protocol 1.1 is required.");
        if(await db.OrangeBookSnapshots.AnyAsync(x=>x.SnapshotCode==snapshotCode+"-orange-book",ct))throw new InvalidOperationException("The immutable FDA reference snapshot is already imported.");
        await using var tx=await db.Database.BeginTransactionAsync(ct);
        var now=DateTime.UtcNow;
        var orangeReg=Registration("m9-orange-book-2026-06","FDA","Orange Book","FDA approval, product, RLD, RS and therapeutic-equivalence evidence.","https://www.fda.gov/drugs/drug-approvals-and-databases/orange-book-data-files","orange-book-v2026-06",orangeZip,repositoryRoot,now,"tilde");
        var drugsReg=Registration("m9-drugsfda-2026-07-17","FDA","Drugs@FDA","FDA application, product, marketing-status and therapeutic-equivalence evidence.","https://www.fda.gov/drugs/drug-approvals-and-databases/drugsfda-data-files","drugsfda-v2026-07-17",drugsZip,repositoryRoot,now,"tab");
        var ndcReg=Registration("m9-openfda-ndc-2026-07-22","FDA","FDA NDC Directory via openFDA","Dated FDA listing and application-linkage evidence; not approval evidence.","https://open.fda.gov/apis/drug/ndc/download/","openfda-ndc-v2026-07-22",ndcZip,repositoryRoot,now,"json");
        db.ResearchSourceRegistrations.AddRange(orangeReg,drugsReg,ndcReg);await db.SaveChangesAsync(ct);
        var os=new OrangeBookSnapshotEntity{SourceRegistryId=orangeReg.SourceRegistryId,SnapshotCode=snapshotCode+"-orange-book",ReleaseDate=new(2026,7,10),SourceSha256=Sha(orangeZip),RelativeArchivePath=Rel(repositoryRoot,orangeZip),RetrievedAtUtc=now};
        var ds=new DrugsFdaSnapshotEntity{SourceRegistryId=drugsReg.SourceRegistryId,SnapshotCode=snapshotCode+"-drugsfda",ReleaseDate=new(2026,7,17),SourceSha256=Sha(drugsZip),RelativeArchivePath=Rel(repositoryRoot,drugsZip),RetrievedAtUtc=now};
        var ns=new NdcDirectorySnapshotEntity{SourceRegistryId=ndcReg.SourceRegistryId,SnapshotCode=snapshotCode+"-ndc",ReleaseDate=new(2026,7,22),SourceSha256=Sha(ndcZip),RelativeArchivePath=Rel(repositoryRoot,ndcZip),RetrievedAtUtc=now,DatasetUpdateDate="2026-07-22",AggregateManifestSha256="7D5B702ED33B120BE85E36F99BC10847B5A1DFF36A7B64C014CBEF10EC9FE0F6"};
        db.AddRange(os,ds,ns);await db.SaveChangesAsync(ct);
        var connection=(SqlConnection)db.Database.GetDbConnection();var sqlTx=(SqlTransaction)tx.GetDbTransaction();
        long orangeRows=await OrangeAsync(connection,sqlTx,os.ReferenceSnapshotId,orange,ct);
        long apps=await DelimitedAsync(connection,sqlTx,ds.ReferenceSnapshotId,Path.Combine(drugs,"Applications.txt"),"[reference].[DrugsFdaApplication]",ApplicationTable,(v,n)=>new object?[]{n,v[0],App(v[0]),v[1],Null(v[3])},ct);
        long products=await DelimitedAsync(connection,sqlTx,ds.ReferenceSnapshotId,Path.Combine(drugs,"Products.txt"),"[reference].[DrugsFdaProduct]",ProductTable,(v,n)=>new object?[]{n,v[0],App(v[0]),v[1],Product(v[1]),Null(v[2]),Null(v[3]),Null(v[5]),Null(v[6]),Bool(v[4]),Bool(v[7])},ct);
        var lookup=File.ReadLines(Path.Combine(drugs,"MarketingStatus_Lookup.txt")).Skip(1).Select(x=>x.Split('\t')).Where(x=>x.Length>1).ToDictionary(x=>int.Parse(x[0],CultureInfo.InvariantCulture),x=>x[1]);
        long marketing=await DelimitedAsync(connection,sqlTx,ds.ReferenceSnapshotId,Path.Combine(drugs,"MarketingStatus.txt"),"[reference].[DrugsFdaMarketingStatus]",MarketingTable,(v,n)=>{var code=int.Parse(v[0],CultureInfo.InvariantCulture);return new object?[]{n,App(v[1]),Product(v[2]),code,lookup.GetValueOrDefault(code)};},ct);
        long te=await DelimitedAsync(connection,sqlTx,ds.ReferenceSnapshotId,Path.Combine(drugs,"TE.txt"),"[reference].[DrugsFdaTherapeuticEquivalence]",TeTable,(v,n)=>new object?[]{n,App(v[0]),Product(v[1]),v[3]},ct);
        var (ndcProducts,ndcPackages)=await NdcAsync(connection,sqlTx,ns.ReferenceSnapshotId,ndc,ct);
        os.RowCount=orangeRows;ds.RowCount=apps+products+marketing+te;ns.RowCount=ndcProducts;orangeReg.MarkValidated(orangeRows,[]);drugsReg.MarkValidated(ds.RowCount,[]);ndcReg.MarkValidated(ndcProducts,[]);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);
        return new(orangeRows,apps,products,marketing,te,ndcProducts,ndcPackages);
    }
    private static ResearchSourceRegistration Registration(string code,string authority,string name,string description,string official,string schema,string path,string root,DateTime now,string delimiter)=>new(code,ResearchSourceType.FdaFirstGenericApproval,authority,name,description,official,now,null,null,"Public FDA data; retain attribution and source lineage.",schema,Path.GetFileName(path),Rel(root,path),Sha(path),new FileInfo(path).Length,"UTF-8",delimiter,false,"PharmaAccess.Worker/fda-reference-import",now);
    private static async Task<long> OrangeAsync(SqlConnection c,SqlTransaction tx,long snapshot,string path,CancellationToken ct){var table=OrangeTable();long count=0,row=0;foreach(var line in File.ReadLines(path).Skip(1)){row++;var v=line.Split('~');if(v.Length<14)throw new InvalidDataException($"Orange Book row {row} has {v.Length} fields.");var fr=v[1].Split(';',2);table.Rows.Add(snapshot,row,v[0],Ingredients(v[0]),v[1],fr[0].Trim().ToUpperInvariant(),fr.Length>1?fr[1].Trim().ToUpperInvariant():null,v[2],v[3],v[4],Norm(v[4]),v[5],v[6],App(v[6]),v[7],Product(v[7]),Null(v[8]),v[9],Date(v[9]),Null(v[10]),Null(v[11]),v[12],Null(v[13]));count++;if(table.Rows.Count>=BatchSize){await Bulk(c,tx,"[reference].[OrangeBookProduct]",table,ct);table.Clear();}}if(table.Rows.Count>0)await Bulk(c,tx,"[reference].[OrangeBookProduct]",table,ct);return count;}
    private static async Task<long> DelimitedAsync(SqlConnection c,SqlTransaction tx,long snapshot,string path,string destination,Func<DataTable> make,Func<string[],long,object?[]> values,CancellationToken ct){var table=make();long count=0,row=0;foreach(var line in File.ReadLines(path).Skip(1)){row++;var v=line.Split('\t');var data=values(v,row);var all=new object?[data.Length+1];all[0]=snapshot;Array.Copy(data,0,all,1,data.Length);table.Rows.Add(all);count++;if(table.Rows.Count>=BatchSize){await Bulk(c,tx,destination,table,ct);table.Clear();}}if(table.Rows.Count>0)await Bulk(c,tx,destination,table,ct);return count;}
    private static async Task<(long products,long packages)> NdcAsync(SqlConnection c,SqlTransaction tx,long snapshot,string path,CancellationToken ct){var pt=NdcProductTable();var kt=NdcPackageTable();long products=0,packages=0;foreach(var json in ResultObjects(path)){using var doc=JsonDocument.Parse(json);var x=doc.RootElement;products++;string product=Get(x,"product_ndc")??"";string? app=Get(x,"application_number");pt.Rows.Add(snapshot,products,product,NdcProduct(product),Null(app),app is null?null:App(app),Null(Get(x,"generic_name")),Null(Get(x,"brand_name")),Null(Get(x,"dosage_form")),Null(GetArray(x,"route")),Null(Get(x,"marketing_category")),Null(Get(x,"labeler_name")),CompactDate(Get(x,"marketing_start_date")),CompactDate(Get(x,"marketing_end_date")));if(x.TryGetProperty("packaging",out var list))foreach(var p in list.EnumerateArray()){packages++;var package=Get(p,"package_ndc")??"";kt.Rows.Add(snapshot,packages,package,Ndc(package),product,Null(Get(p,"description")));if(kt.Rows.Count>=BatchSize){await Bulk(c,tx,"[reference].[NdcDirectoryPackage]",kt,ct);kt.Clear();}}if(pt.Rows.Count>=BatchSize){await Bulk(c,tx,"[reference].[NdcDirectoryProduct]",pt,ct);pt.Clear();}}if(pt.Rows.Count>0)await Bulk(c,tx,"[reference].[NdcDirectoryProduct]",pt,ct);if(kt.Rows.Count>0)await Bulk(c,tx,"[reference].[NdcDirectoryPackage]",kt,ct);return(products,packages);}
    private static IEnumerable<string> ResultObjects(string path){using var reader=new StreamReader(path);string? line;bool results=false,inString=false,escape=false;int depth=0;StringBuilder? item=null;while((line=reader.ReadLine())!=null){if(!results){if(line.TrimStart().StartsWith("\"results\": [",StringComparison.Ordinal))results=true;continue;}if(depth==0&&line.TrimStart().StartsWith(']'))yield break;foreach(char ch in line){if(item is null){if(ch!='{')continue;item=new();depth=0;inString=false;escape=false;}item.Append(ch);if(inString){if(escape)escape=false;else if(ch=='\\')escape=true;else if(ch=='\"')inString=false;}else if(ch=='\"')inString=true;else if(ch=='{')depth++;else if(ch=='}')depth--;if(item is not null&&depth==0){yield return item.ToString();item=null;}}if(item is not null)item.AppendLine();}}
    private static async Task Bulk(SqlConnection c,SqlTransaction tx,string destination,DataTable table,CancellationToken ct){using var b=new SqlBulkCopy(c,SqlBulkCopyOptions.TableLock|SqlBulkCopyOptions.CheckConstraints,tx){DestinationTableName=destination,EnableStreaming=true,BatchSize=table.Rows.Count,BulkCopyTimeout=0};foreach(DataColumn x in table.Columns)b.ColumnMappings.Add(x.ColumnName,x.ColumnName);await b.WriteToServerAsync(table,ct);Console.WriteLine($"{destination}: streamed batch {table.Rows.Count}");}
    private static DataTable T(params (string,Type)[] columns){var t=new DataTable();foreach(var x in columns)t.Columns.Add(x.Item1,x.Item2);return t;}
    private static DataTable OrangeTable()=>T(("OrangeBookSnapshotId",typeof(long)),("SourceRowNumber",typeof(long)),("IngredientRaw",typeof(string)),("NormalizedIngredientSet",typeof(string)),("DosageFormRouteRaw",typeof(string)),("DosageForm",typeof(string)),("Route",typeof(string)),("TradeNameRaw",typeof(string)),("ApplicantRaw",typeof(string)),("StrengthRaw",typeof(string)),("NormalizedStrength",typeof(string)),("ApplicationTypeRaw",typeof(string)),("ApplicationNumberRaw",typeof(string)),("NormalizedApplicationNumber",typeof(string)),("ProductNumberRaw",typeof(string)),("NormalizedProductNumber",typeof(string)),("TherapeuticEquivalenceCodeRaw",typeof(string)),("ApprovalDateRaw",typeof(string)),("ApprovalDate",typeof(DateTime)),("ReferenceListedDrugRaw",typeof(string)),("ReferenceStandardRaw",typeof(string)),("ProductTypeRaw",typeof(string)),("ApplicantFullNameRaw",typeof(string)));
    private static DataTable ApplicationTable()=>T(("DrugsFdaSnapshotId",typeof(long)),("SourceRowNumber",typeof(long)),("ApplicationNumberRaw",typeof(string)),("NormalizedApplicationNumber",typeof(string)),("ApplicationTypeRaw",typeof(string)),("SponsorNameRaw",typeof(string)));
    private static DataTable ProductTable()=>T(("DrugsFdaSnapshotId",typeof(long)),("SourceRowNumber",typeof(long)),("ApplicationNumberRaw",typeof(string)),("NormalizedApplicationNumber",typeof(string)),("ProductNumberRaw",typeof(string)),("NormalizedProductNumber",typeof(string)),("FormRaw",typeof(string)),("StrengthRaw",typeof(string)),("DrugNameRaw",typeof(string)),("ActiveIngredientRaw",typeof(string)),("ReferenceDrug",typeof(bool)),("ReferenceStandard",typeof(bool)));
    private static DataTable MarketingTable()=>T(("DrugsFdaSnapshotId",typeof(long)),("SourceRowNumber",typeof(long)),("NormalizedApplicationNumber",typeof(string)),("NormalizedProductNumber",typeof(string)),("MarketingStatusCode",typeof(int)),("MarketingStatusDescription",typeof(string)));
    private static DataTable TeTable()=>T(("DrugsFdaSnapshotId",typeof(long)),("SourceRowNumber",typeof(long)),("NormalizedApplicationNumber",typeof(string)),("NormalizedProductNumber",typeof(string)),("TherapeuticEquivalenceCode",typeof(string)));
    private static DataTable NdcProductTable()=>T(("NdcDirectorySnapshotId",typeof(long)),("SourceRowNumber",typeof(long)),("ProductNdcRaw",typeof(string)),("NormalizedProductNdc",typeof(string)),("ApplicationNumberRaw",typeof(string)),("NormalizedApplicationNumber",typeof(string)),("GenericNameRaw",typeof(string)),("BrandNameRaw",typeof(string)),("DosageFormRaw",typeof(string)),("RouteRaw",typeof(string)),("MarketingCategoryRaw",typeof(string)),("LabelerNameRaw",typeof(string)),("MarketingStartDate",typeof(DateTime)),("MarketingEndDate",typeof(DateTime)));
    private static DataTable NdcPackageTable()=>T(("NdcDirectorySnapshotId",typeof(long)),("SourceRowNumber",typeof(long)),("PackageNdcRaw",typeof(string)),("NormalizedPackageNdc",typeof(string)),("ProductNdcRaw",typeof(string)),("DescriptionRaw",typeof(string)));
    private static string Sha(string path)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path)));private static string Rel(string root,string path)=>Path.GetRelativePath(root,path).Replace('\\','/');
    private static object? Null(string? x)=>string.IsNullOrWhiteSpace(x)?DBNull.Value:x.Trim();private static object? Bool(string x)=>x=="1"?true:x=="0"?false:DBNull.Value;private static object? Date(string x)=>DateTime.TryParse(x,CultureInfo.InvariantCulture,DateTimeStyles.None,out var d)?d:DBNull.Value;private static object? CompactDate(string? x)=>DateTime.TryParseExact(x,"yyyyMMdd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var d)?d:DBNull.Value;
    private static string App(string x){var digits=new string(x.Where(char.IsDigit).ToArray());return digits.PadLeft(6,'0');}private static string Product(string x)=>new string(x.Where(char.IsDigit).ToArray()).PadLeft(3,'0');private static string Norm(string x)=>string.Join(' ',x.Trim().ToUpperInvariant().Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries));private static string Ingredients(string x)=>string.Join("|",x.Split(';',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Select(Norm).Order(StringComparer.Ordinal));
    private static string? Ndc(string x){var p=x.Split('-');if(p.Length==3){if(p[0].Length==4&&p[1].Length==4&&p[2].Length==2)return"0"+string.Concat(p);if(p[0].Length==5&&p[1].Length==3&&p[2].Length==2)return p[0]+"0"+p[1]+p[2];if(p[0].Length==5&&p[1].Length==4&&p[2].Length==1)return p[0]+p[1]+"0"+p[2];}var d=new string(x.Where(char.IsDigit).ToArray());return d.Length==11?d:null;}private static string? NdcProduct(string x){var d=new string(x.Where(char.IsDigit).ToArray());return d.Length is 8 or 9 or 10?d:null;}
    private static string? Get(JsonElement x,string name)=>x.TryGetProperty(name,out var p)&&p.ValueKind==JsonValueKind.String?p.GetString():null;private static string? GetArray(JsonElement x,string name)=>x.TryGetProperty(name,out var p)&&p.ValueKind==JsonValueKind.Array?string.Join(';',p.EnumerateArray().Select(v=>v.GetString())):null;
}
