using System.Collections;
using System.Data.Common;
using System.Globalization;
using PharmaAccess.Application.Research;

namespace PharmaAccess.Data.Research;

public sealed class RawImportBulkDataReader(ImportSourceKind kind,int sourceFileId,IReadOnlyList<RawImportRow> rows,DateTime importedAtUtc):DbDataReader
{
    private readonly RawImportRow[] accepted=rows.Where(x=>x.Disposition==ImportRowDisposition.Accepted).ToArray();
    private int index=-1;
    public static readonly string[] FdaColumns=["SourceFileId","SourceRowNumber","ApplicationNumberRaw","ProductNumberRaw","ActiveIngredientRaw","DosageFormRaw","StrengthRaw","ApplicantRaw","ApprovalDateRaw","ParsedApprovalDate","ParseStatus","ErrorCode","ErrorMessage","ImportedAtUtc"];
    public static readonly string[] MedicaidColumns=["SourceFileId","SourceRowNumber","UtilizationTypeRaw","StateCodeRaw","NdcRaw","ProductNameRaw","PackageSizeRaw","YearRaw","QuarterRaw","PrescriptionCountRaw","ReimbursementAmountRaw","ParsedYear","ParsedQuarter","ParsedPrescriptionCount","ParsedReimbursementAmount","ParseStatus","ErrorCode","ErrorMessage","ImportedAtUtc"];
    private string[] Columns=>kind==ImportSourceKind.Fda?FdaColumns:MedicaidColumns;
    public override bool Read()=>++index<accepted.Length;
    public override int FieldCount=>Columns.Length;
    public override object GetValue(int ordinal){var row=accepted[index];string? V(string key)=>row.Values.TryGetValue(key,out var value)?value:null;object? value=kind==ImportSourceKind.Fda?ordinal switch{0=>sourceFileId,1=>row.SourceRowNumber,2=>V("ANDA Number"),3=>null,4=>V("Generic Name"),5=>null,6=>null,7=>V("ANDA Applicant"),8=>V("ANDA Approval Date"),9=>DateTime.TryParse(V("ANDA Approval Date"),CultureInfo.InvariantCulture,out var date)?date:null,10=>"Parsed",11=>null,12=>null,13=>importedAtUtc,_=>null}:Medicaid(ordinal,row,V);return value??DBNull.Value;}
    private object? Medicaid(int ordinal,RawImportRow row,Func<string,string?> v){var suppressed=v("Suppression Used") is "true" or "True" or "1";return ordinal switch{0=>sourceFileId,1=>row.SourceRowNumber,2=>v("Utilization Type"),3=>v("State"),4=>v("NDC"),5=>v("Product Name"),6=>v("Package Size"),7=>v("Year"),8=>v("Quarter"),9=>v("Number of Prescriptions"),10=>v("Total Amount Reimbursed"),11=>int.TryParse(v("Year"),out var year)?year:null,12=>int.TryParse(v("Quarter"),out var quarter)?quarter:null,13=>!suppressed&&long.TryParse(v("Number of Prescriptions"),out var rx)?rx:null,14=>!suppressed&&decimal.TryParse(v("Total Amount Reimbursed"),NumberStyles.Number|NumberStyles.AllowCurrencySymbol,CultureInfo.InvariantCulture,out var amount)?amount:null,15=>"Parsed",16=>null,17=>null,18=>importedAtUtc,_=>null};}
    public override string GetName(int ordinal)=>Columns[ordinal];public override int GetOrdinal(string name)=>Array.IndexOf(Columns,name);public override bool IsDBNull(int ordinal)=>GetValue(ordinal)==DBNull.Value;public override int GetValues(object[] values){var count=Math.Min(values.Length,FieldCount);for(var i=0;i<count;i++)values[i]=GetValue(i);return count;}public override Type GetFieldType(int ordinal)=>typeof(object);public override string GetDataTypeName(int ordinal)=>GetFieldType(ordinal).Name;public override bool HasRows=>accepted.Length!=0;public override int Depth=>0;public override bool IsClosed=>false;public override int RecordsAffected=>-1;public override object this[int ordinal]=>GetValue(ordinal);public override object this[string name]=>GetValue(GetOrdinal(name));public override bool NextResult()=>false;public override IEnumerator GetEnumerator()=>accepted.GetEnumerator();
    public override bool GetBoolean(int ordinal)=>(bool)GetValue(ordinal);public override byte GetByte(int ordinal)=>(byte)GetValue(ordinal);public override long GetBytes(int ordinal,long dataOffset,byte[]? buffer,int bufferOffset,int length)=>throw new NotSupportedException();public override char GetChar(int ordinal)=>(char)GetValue(ordinal);public override long GetChars(int ordinal,long dataOffset,char[]? buffer,int bufferOffset,int length)=>throw new NotSupportedException();public override Guid GetGuid(int ordinal)=>(Guid)GetValue(ordinal);public override short GetInt16(int ordinal)=>Convert.ToInt16(GetValue(ordinal),CultureInfo.InvariantCulture);public override int GetInt32(int ordinal)=>Convert.ToInt32(GetValue(ordinal),CultureInfo.InvariantCulture);public override long GetInt64(int ordinal)=>Convert.ToInt64(GetValue(ordinal),CultureInfo.InvariantCulture);public override float GetFloat(int ordinal)=>Convert.ToSingle(GetValue(ordinal),CultureInfo.InvariantCulture);public override double GetDouble(int ordinal)=>Convert.ToDouble(GetValue(ordinal),CultureInfo.InvariantCulture);public override string GetString(int ordinal)=>(string)GetValue(ordinal);public override decimal GetDecimal(int ordinal)=>Convert.ToDecimal(GetValue(ordinal),CultureInfo.InvariantCulture);public override DateTime GetDateTime(int ordinal)=>(DateTime)GetValue(ordinal);
}
