using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PharmaAccess.Data.Entities;

namespace PharmaAccess.Data.Configurations;

public sealed class GovernanceDriftReportConfiguration : IEntityTypeConfiguration<GovernanceDriftReport>
{ public void Configure(EntityTypeBuilder<GovernanceDriftReport> b) { b.ToTable("DriftReport","ml"); b.HasKey(x=>x.DriftReportId); b.Property(x=>x.ChampionVersion).HasMaxLength(128).IsRequired(); b.Property(x=>x.EvaluationWindow).HasMaxLength(128).IsRequired(); b.Property(x=>x.Severity).HasConversion<string>().HasMaxLength(24); b.Property(x=>x.SubgroupWarningsJson).HasMaxLength(8000); b.Property(x=>x.GovernanceNotice).HasMaxLength(1000); b.HasIndex(x=>new{x.ChampionVersion,x.CreatedAtUtc}); } }
public sealed class GovernanceDriftFindingConfiguration : IEntityTypeConfiguration<GovernanceDriftFinding>
{ public void Configure(EntityTypeBuilder<GovernanceDriftFinding> b) { b.ToTable("DriftFinding","ml"); b.HasKey(x=>x.DriftFindingId); b.HasOne<GovernanceDriftReport>().WithMany(x=>x.Findings).HasForeignKey(x=>x.DriftReportId).OnDelete(DeleteBehavior.Restrict); foreach(var p in new[]{nameof(GovernanceDriftFinding.Scope),nameof(GovernanceDriftFinding.Name),nameof(GovernanceDriftFinding.Statistic)}) b.Property(p).HasMaxLength(128).IsRequired(); b.Property(x=>x.Severity).HasConversion<string>().HasMaxLength(24); b.Property(x=>x.Formula).HasMaxLength(500); b.HasIndex(x=>new{x.DriftReportId,x.Scope,x.Name,x.Statistic}).IsUnique(); } }
public sealed class GovernanceComparisonConfiguration : IEntityTypeConfiguration<GovernanceComparison>
{ public void Configure(EntityTypeBuilder<GovernanceComparison> b) { b.ToTable("ChampionChallengerComparison","ml"); b.HasKey(x=>x.ComparisonId); foreach(var p in new[]{nameof(GovernanceComparison.ChampionVersion),nameof(GovernanceComparison.ChallengerVersion),nameof(GovernanceComparison.FeatureSchemaHash),nameof(GovernanceComparison.EvaluationCohortHash),nameof(GovernanceComparison.DatasetHash),nameof(GovernanceComparison.DatasetFreezeIdentifier),nameof(GovernanceComparison.ReproducibilityHash),nameof(GovernanceComparison.Status)}) b.Property(p).HasMaxLength(256); b.Property(x=>x.ChampionArtifactPath).HasMaxLength(1000); b.Property(x=>x.ChallengerArtifactPath).HasMaxLength(1000); b.Property(x=>x.ChampionArtifactSha256).HasMaxLength(64); b.Property(x=>x.ChallengerArtifactSha256).HasMaxLength(64); foreach(var p in new[]{nameof(GovernanceComparison.ChampionJson),nameof(GovernanceComparison.ChallengerJson),nameof(GovernanceComparison.MetricDifferencesJson),nameof(GovernanceComparison.SubgroupResultsJson),nameof(GovernanceComparison.BlockingReasonsJson)}) b.Property(p).HasColumnType("nvarchar(max)"); b.Property(x=>x.RowVersion).IsRowVersion().IsConcurrencyToken(); b.HasIndex(x=>new{x.ChampionVersion,x.ChallengerVersion,x.CreatedAtUtc}); } }
public sealed class GovernanceChampionStateConfiguration : IEntityTypeConfiguration<GovernanceChampionState>
{ public void Configure(EntityTypeBuilder<GovernanceChampionState> b) { b.ToTable("ChampionState","ml",t=>t.HasCheckConstraint("CK_ChampionState_Singleton","[GovernanceChampionStateId] = 1")); b.HasKey(x=>x.GovernanceChampionStateId); b.Property(x=>x.ChampionVersion).HasMaxLength(128).IsRequired(); b.Property(x=>x.PreviousChampionVersion).HasMaxLength(128); b.Property(x=>x.RowVersion).IsRowVersion().IsConcurrencyToken(); } }
public sealed class GovernanceDecisionConfiguration : IEntityTypeConfiguration<GovernanceDecision>
{ public void Configure(EntityTypeBuilder<GovernanceDecision> b) { b.ToTable("GovernanceDecision","audit"); b.HasKey(x=>x.GovernanceDecisionId); b.HasOne<GovernanceComparison>().WithMany().HasForeignKey(x=>x.ComparisonId).OnDelete(DeleteBehavior.Restrict); b.Property(x=>x.Decision).HasConversion<string>().HasMaxLength(24); foreach(var p in new[]{nameof(GovernanceDecision.ChampionBefore),nameof(GovernanceDecision.ChampionAfter),nameof(GovernanceDecision.ChallengerVersion),nameof(GovernanceDecision.ApproverIdentifier)}) b.Property(p).HasMaxLength(256).IsRequired(); b.Property(x=>x.Reason).HasMaxLength(2000).IsRequired(); b.Property(x=>x.RowVersion).IsRowVersion().IsConcurrencyToken(); b.HasIndex(x=>x.ComparisonId).IsUnique().HasFilter("[ComparisonId] IS NOT NULL"); } }
public sealed class GovernanceChampionHistoryConfiguration : IEntityTypeConfiguration<GovernanceChampionHistory>
{ public void Configure(EntityTypeBuilder<GovernanceChampionHistory> b) { b.ToTable("ChampionHistory","audit"); b.HasKey(x=>x.ChampionHistoryId); b.HasOne<GovernanceDecision>().WithMany().HasForeignKey(x=>x.GovernanceDecisionId).OnDelete(DeleteBehavior.Restrict); b.Property(x=>x.ModelVersion).HasMaxLength(128); b.Property(x=>x.PreviousChampionVersion).HasMaxLength(128); b.HasIndex(x=>x.IsCurrent).IsUnique().HasFilter("[IsCurrent] = 1"); b.HasIndex(x=>new{x.ModelVersion,x.ApprovedAtUtc}); } }
public sealed class GovernanceAuditRecordConfiguration : IEntityTypeConfiguration<GovernanceAuditRecord>
{ public void Configure(EntityTypeBuilder<GovernanceAuditRecord> b) { b.ToTable("GovernanceAuditRecord","audit"); b.HasKey(x=>x.GovernanceAuditRecordId); b.HasOne<GovernanceDecision>().WithMany().HasForeignKey(x=>x.GovernanceDecisionId).OnDelete(DeleteBehavior.Restrict); b.Property(x=>x.EventType).HasMaxLength(64).IsRequired(); b.Property(x=>x.PayloadJson).HasColumnType("nvarchar(max)"); b.HasIndex(x=>x.GovernanceDecisionId).IsUnique(); } }
