using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PharmaAccess.Data.Entities;

namespace PharmaAccess.Data.Configurations;

internal static class MlEvaluationMapping
{
    internal static void Run<TEntity>(EntityTypeBuilder<TEntity> b, System.Linq.Expressions.Expression<Func<TEntity,object?>> runId) where TEntity : class { b.HasOne<ModelTrainingRun>().WithMany().HasForeignKey(runId).OnDelete(DeleteBehavior.Restrict); }
    internal static void ApproximateNumber<TEntity>(EntityTypeBuilder<TEntity> b, System.Linq.Expressions.Expression<Func<TEntity,double>> property) where TEntity : class => b.Property(property).HasColumnType("float(53)");
}
public sealed class ModelCalibrationConfiguration : IEntityTypeConfiguration<ModelCalibration> { public void Configure(EntityTypeBuilder<ModelCalibration> b) { b.ToTable("ModelCalibration", "ml"); b.HasKey(x=>x.ModelCalibrationId); MlEvaluationMapping.Run(b,x=>x.ModelTrainingRunId); b.Property(x=>x.Method).HasConversion<string>().HasMaxLength(32); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(32); b.Property(x=>x.Slope).HasColumnType("float(53)"); b.Property(x=>x.Intercept).HasColumnType("float(53)"); b.Property(x=>x.WarningsJson).HasMaxLength(8000); b.HasIndex(x=>new{x.ModelTrainingRunId,x.Method}).IsUnique(); } }
public sealed class CalibrationMetricConfiguration : IEntityTypeConfiguration<CalibrationMetricEntity> { public void Configure(EntityTypeBuilder<CalibrationMetricEntity> b) { b.ToTable("CalibrationMetric","ml"); b.HasKey(x=>x.CalibrationMetricId); b.HasOne<ModelCalibration>().WithMany().HasForeignKey(x=>x.ModelCalibrationId).OnDelete(DeleteBehavior.Restrict); b.Property(x=>x.Partition).HasConversion<string>().HasMaxLength(16); b.Property(x=>x.MetricName).HasMaxLength(64).IsRequired(); MlEvaluationMapping.ApproximateNumber(b,x=>x.MetricValue); b.HasIndex(x=>new{x.ModelCalibrationId,x.Partition,x.MetricName}).IsUnique(); } }
public sealed class CalibrationBinConfiguration : IEntityTypeConfiguration<CalibrationBinEntity> { public void Configure(EntityTypeBuilder<CalibrationBinEntity> b) { b.ToTable("CalibrationBin","ml"); b.HasKey(x=>x.CalibrationBinId); b.HasOne<ModelCalibration>().WithMany().HasForeignKey(x=>x.ModelCalibrationId).OnDelete(DeleteBehavior.Restrict); b.Property(x=>x.Partition).HasConversion<string>().HasMaxLength(16); b.Property(x=>x.Binning).HasConversion<string>().HasMaxLength(32); foreach(var p in new[]{nameof(CalibrationBinEntity.LowerBound),nameof(CalibrationBinEntity.UpperBound),nameof(CalibrationBinEntity.MeanProbability),nameof(CalibrationBinEntity.ObservedRate)}) b.Property(p).HasColumnType("float(53)"); b.HasIndex(x=>new{x.ModelCalibrationId,x.Partition,x.Binning,x.BinNumber}).IsUnique(); } }
public sealed class FeatureImportanceConfiguration : IEntityTypeConfiguration<FeatureImportanceEntity> { public void Configure(EntityTypeBuilder<FeatureImportanceEntity> b) { b.ToTable("FeatureImportanceResult","ml"); b.HasKey(x=>x.FeatureImportanceResultId); MlEvaluationMapping.Run(b,x=>x.ModelTrainingRunId); b.Property(x=>x.FeatureName).HasMaxLength(128).IsRequired(); b.Property(x=>x.MetricName).HasMaxLength(64).IsRequired(); foreach(var p in new[]{nameof(FeatureImportanceEntity.BaselineValue),nameof(FeatureImportanceEntity.PermutedValue),nameof(FeatureImportanceEntity.ImportanceDelta),nameof(FeatureImportanceEntity.StandardDeviation)}) b.Property(p).HasColumnType("float(53)"); b.HasIndex(x=>new{x.ModelTrainingRunId,x.MetricName,x.FeatureName}).IsUnique(); } }
public sealed class SubgroupMetricConfiguration : IEntityTypeConfiguration<SubgroupMetricEntity> { public void Configure(EntityTypeBuilder<SubgroupMetricEntity> b) { b.ToTable("SubgroupMetric","ml"); b.HasKey(x=>x.SubgroupMetricId); MlEvaluationMapping.Run(b,x=>x.ModelTrainingRunId); b.Property(x=>x.Partition).HasConversion<string>().HasMaxLength(16); b.Property(x=>x.Dimension).HasMaxLength(64).IsRequired(); b.Property(x=>x.SubgroupValue).HasMaxLength(128).IsRequired(); b.Property(x=>x.MetricName).HasMaxLength(64).IsRequired(); b.Property(x=>x.MetricValue).HasColumnType("float(53)"); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(32); b.HasIndex(x=>new{x.ModelTrainingRunId,x.Partition,x.Dimension,x.SubgroupValue,x.MetricName}).IsUnique(); } }
public sealed class ModelErrorAnalysisConfiguration : IEntityTypeConfiguration<ModelErrorAnalysisEntity> { public void Configure(EntityTypeBuilder<ModelErrorAnalysisEntity> b) { b.ToTable("ModelErrorAnalysis","ml"); b.HasKey(x=>x.ModelErrorAnalysisId); MlEvaluationMapping.Run(b,x=>x.ModelTrainingRunId); b.Property(x=>x.Category).HasConversion<string>().HasMaxLength(64); b.Property(x=>x.UncertaintyStatus).HasConversion<string>().HasMaxLength(32); b.Property(x=>x.Probability).HasColumnType("float(53)"); b.Property(x=>x.Threshold).HasColumnType("float(53)"); b.Property(x=>x.ContextJson).HasMaxLength(8000); b.Property(x=>x.WarningsJson).HasMaxLength(8000); b.HasIndex(x=>new{x.ModelTrainingRunId,x.Category}); } }
public sealed class ThresholdEvaluationConfiguration : IEntityTypeConfiguration<ThresholdEvaluationEntity> { public void Configure(EntityTypeBuilder<ThresholdEvaluationEntity> b) { b.ToTable("ThresholdEvaluation","ml"); b.HasKey(x=>x.ThresholdEvaluationId); MlEvaluationMapping.Run(b,x=>x.ModelTrainingRunId); b.Property(x=>x.Policy).HasConversion<string>().HasMaxLength(32); b.Property(x=>x.Partition).HasConversion<string>().HasMaxLength(16); b.Property(x=>x.Objective).HasMaxLength(256).IsRequired(); b.Property(x=>x.ConstraintsJson).HasMaxLength(4000); foreach(var p in new[]{nameof(ThresholdEvaluationEntity.Threshold),nameof(ThresholdEvaluationEntity.Precision),nameof(ThresholdEvaluationEntity.Recall),nameof(ThresholdEvaluationEntity.F1),nameof(ThresholdEvaluationEntity.Specificity)}) b.Property(p).HasColumnType("float(53)"); b.HasIndex(x=>new{x.ModelTrainingRunId,x.Policy,x.Partition}).IsUnique(); } }
public sealed class ModelApprovalConfiguration : IEntityTypeConfiguration<ModelApprovalEntity> { public void Configure(EntityTypeBuilder<ModelApprovalEntity> b) { b.ToTable("ModelApproval","ml"); b.HasKey(x=>x.ModelApprovalId); b.HasOne<ModelArtifact>().WithMany().HasForeignKey(x=>x.ModelArtifactId).OnDelete(DeleteBehavior.Restrict); b.Property(x=>x.Decision).HasConversion<string>().HasMaxLength(32); b.Property(x=>x.ApprovedBy).HasMaxLength(256).IsRequired(); b.Property(x=>x.ApprovalReason).HasMaxLength(2000).IsRequired(); b.Property(x=>x.TargetEnvironment).HasMaxLength(64).IsRequired(); b.Property(x=>x.ModelCardVersion).HasMaxLength(128).IsRequired(); b.HasIndex(x=>new{x.ModelArtifactId,x.CreatedAtUtc}); } }
public sealed class ModelRegistryEntryConfiguration : IEntityTypeConfiguration<ModelRegistryEntry> { public void Configure(EntityTypeBuilder<ModelRegistryEntry> b) { b.ToTable("ModelRegistryEntry","ml"); b.HasKey(x=>x.ModelRegistryEntryId); b.HasOne<ModelArtifact>().WithMany().HasForeignKey(x=>x.ModelArtifactId).OnDelete(DeleteBehavior.Restrict); b.Property(x=>x.TaskName).HasMaxLength(64).IsRequired(); b.Property(x=>x.Environment).HasMaxLength(64).IsRequired(); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(32); b.HasIndex(x=>new{x.TaskName,x.Environment,x.IsChampion}).IsUnique().HasFilter("[IsChampion] = 1"); b.HasIndex(x=>new{x.ModelArtifactId,x.Environment}).IsUnique(); } }
