using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PharmaAccess.Data.Entities;
using PharmaAccess.Domain.Research;

namespace PharmaAccess.Data.Configurations;

public sealed class ReferenceSnapshotConfiguration:IEntityTypeConfiguration<ReferenceSnapshotEntity>{public void Configure(EntityTypeBuilder<ReferenceSnapshotEntity>b){b.UseTpcMappingStrategy();b.HasKey(x=>x.ReferenceSnapshotId);b.Property(x=>x.SnapshotCode).HasMaxLength(128).IsRequired();b.Property(x=>x.SourceSha256).HasMaxLength(64).IsRequired();b.Property(x=>x.RelativeArchivePath).HasMaxLength(1024).IsRequired();b.HasIndex(x=>x.SnapshotCode).IsUnique();b.HasIndex(x=>x.SourceSha256).IsUnique();b.HasOne<ResearchSourceRegistration>().WithMany().HasForeignKey(x=>x.SourceRegistryId).OnDelete(DeleteBehavior.Restrict);}}
public sealed class OrangeBookSnapshotConfiguration:IEntityTypeConfiguration<OrangeBookSnapshotEntity>{public void Configure(EntityTypeBuilder<OrangeBookSnapshotEntity>b)=>b.ToTable("OrangeBookSnapshot","reference");}
public sealed class DrugsFdaSnapshotConfiguration:IEntityTypeConfiguration<DrugsFdaSnapshotEntity>{public void Configure(EntityTypeBuilder<DrugsFdaSnapshotEntity>b)=>b.ToTable("DrugsFdaSnapshot","reference");}
public sealed class NdcDirectorySnapshotConfiguration:IEntityTypeConfiguration<NdcDirectorySnapshotEntity>{public void Configure(EntityTypeBuilder<NdcDirectorySnapshotEntity>b){b.ToTable("NdcDirectorySnapshot","reference");b.Property(x=>x.DatasetUpdateDate).HasMaxLength(32).IsRequired();b.Property(x=>x.AggregateManifestSha256).HasMaxLength(64).IsRequired();}}
public sealed class RxNormSnapshotConfiguration:IEntityTypeConfiguration<RxNormSnapshotEntity>{public void Configure(EntityTypeBuilder<RxNormSnapshotEntity>b){b.ToTable("RxNormSnapshot","reference");b.Property(x=>x.PublishedMd5).HasMaxLength(32).IsRequired();b.Property(x=>x.ReleaseVersion).HasMaxLength(64).IsRequired();}}
internal static class RefMap{public static void Text<T>(EntityTypeBuilder<T>b,string p,int n,bool required=true)where T:class{var x=b.Property(p).HasMaxLength(n);if(required)x.IsRequired();}public static void Snapshot<T,TParent>(EntityTypeBuilder<T>b,string table,string key,string fk)where T:class where TParent:ReferenceSnapshotEntity{b.ToTable(table,"reference");b.HasKey(key);b.HasOne<TParent>().WithMany().HasForeignKey(fk).OnDelete(DeleteBehavior.Restrict);b.HasIndex(fk,nameof(OrangeBookProductEntity.SourceRowNumber)).IsUnique();}}
public sealed class OrangeBookProductConfiguration:IEntityTypeConfiguration<OrangeBookProductEntity>{public void Configure(EntityTypeBuilder<OrangeBookProductEntity>b){RefMap.Snapshot<OrangeBookProductEntity,OrangeBookSnapshotEntity>(b,"OrangeBookProduct",nameof(OrangeBookProductEntity.OrangeBookProductId),nameof(OrangeBookProductEntity.OrangeBookSnapshotId));foreach(var p in new[]{nameof(OrangeBookProductEntity.IngredientRaw),nameof(OrangeBookProductEntity.DosageFormRouteRaw),nameof(OrangeBookProductEntity.TradeNameRaw),nameof(OrangeBookProductEntity.ApplicantRaw),nameof(OrangeBookProductEntity.StrengthRaw),nameof(OrangeBookProductEntity.ApplicationNumberRaw),nameof(OrangeBookProductEntity.ProductNumberRaw),nameof(OrangeBookProductEntity.ApprovalDateRaw),nameof(OrangeBookProductEntity.ProductTypeRaw)})RefMap.Text(b,p,1000);RefMap.Text(b,nameof(OrangeBookProductEntity.ApplicationTypeRaw),16);foreach(var p in new[]{nameof(OrangeBookProductEntity.NormalizedIngredientSet),nameof(OrangeBookProductEntity.DosageForm),nameof(OrangeBookProductEntity.Route),nameof(OrangeBookProductEntity.NormalizedStrength),nameof(OrangeBookProductEntity.TherapeuticEquivalenceCodeRaw),nameof(OrangeBookProductEntity.ReferenceListedDrugRaw),nameof(OrangeBookProductEntity.ReferenceStandardRaw),nameof(OrangeBookProductEntity.ApplicantFullNameRaw)})RefMap.Text(b,p,1000,false);b.HasIndex(x=>new{x.NormalizedApplicationNumber,x.NormalizedProductNumber});}}
public sealed class DrugsFdaApplicationConfiguration:IEntityTypeConfiguration<DrugsFdaApplicationEntity>{public void Configure(EntityTypeBuilder<DrugsFdaApplicationEntity>b){RefMap.Snapshot<DrugsFdaApplicationEntity,DrugsFdaSnapshotEntity>(b,"DrugsFdaApplication",nameof(DrugsFdaApplicationEntity.DrugsFdaApplicationId),nameof(DrugsFdaApplicationEntity.DrugsFdaSnapshotId));RefMap.Text(b,nameof(DrugsFdaApplicationEntity.ApplicationNumberRaw),32);RefMap.Text(b,nameof(DrugsFdaApplicationEntity.NormalizedApplicationNumber),16);RefMap.Text(b,nameof(DrugsFdaApplicationEntity.ApplicationTypeRaw),16);RefMap.Text(b,nameof(DrugsFdaApplicationEntity.SponsorNameRaw),500,false);b.HasIndex(x=>x.NormalizedApplicationNumber);}}
public sealed class DrugsFdaProductConfiguration:IEntityTypeConfiguration<DrugsFdaProductEntity>{public void Configure(EntityTypeBuilder<DrugsFdaProductEntity>b){RefMap.Snapshot<DrugsFdaProductEntity,DrugsFdaSnapshotEntity>(b,"DrugsFdaProduct",nameof(DrugsFdaProductEntity.DrugsFdaProductId),nameof(DrugsFdaProductEntity.DrugsFdaSnapshotId));RefMap.Text(b,nameof(DrugsFdaProductEntity.ApplicationNumberRaw),32);RefMap.Text(b,nameof(DrugsFdaProductEntity.NormalizedApplicationNumber),16);RefMap.Text(b,nameof(DrugsFdaProductEntity.ProductNumberRaw),32);RefMap.Text(b,nameof(DrugsFdaProductEntity.NormalizedProductNumber),16);foreach(var p in new[]{nameof(DrugsFdaProductEntity.FormRaw),nameof(DrugsFdaProductEntity.StrengthRaw),nameof(DrugsFdaProductEntity.DrugNameRaw),nameof(DrugsFdaProductEntity.ActiveIngredientRaw)})RefMap.Text(b,p,1000,false);b.HasIndex(x=>new{x.NormalizedApplicationNumber,x.NormalizedProductNumber});}}
public sealed class DrugsFdaMarketingStatusConfiguration:IEntityTypeConfiguration<DrugsFdaMarketingStatusEntity>{public void Configure(EntityTypeBuilder<DrugsFdaMarketingStatusEntity>b){RefMap.Snapshot<DrugsFdaMarketingStatusEntity,DrugsFdaSnapshotEntity>(b,"DrugsFdaMarketingStatus",nameof(DrugsFdaMarketingStatusEntity.DrugsFdaMarketingStatusId),nameof(DrugsFdaMarketingStatusEntity.DrugsFdaSnapshotId));RefMap.Text(b,nameof(DrugsFdaMarketingStatusEntity.NormalizedApplicationNumber),16);RefMap.Text(b,nameof(DrugsFdaMarketingStatusEntity.NormalizedProductNumber),16);RefMap.Text(b,nameof(DrugsFdaMarketingStatusEntity.MarketingStatusDescription),256,false);b.HasIndex(x=>new{x.NormalizedApplicationNumber,x.NormalizedProductNumber});}}
public sealed class DrugsFdaTeConfiguration:IEntityTypeConfiguration<DrugsFdaTherapeuticEquivalenceEntity>{public void Configure(EntityTypeBuilder<DrugsFdaTherapeuticEquivalenceEntity>b){RefMap.Snapshot<DrugsFdaTherapeuticEquivalenceEntity,DrugsFdaSnapshotEntity>(b,"DrugsFdaTherapeuticEquivalence",nameof(DrugsFdaTherapeuticEquivalenceEntity.DrugsFdaTherapeuticEquivalenceId),nameof(DrugsFdaTherapeuticEquivalenceEntity.DrugsFdaSnapshotId));RefMap.Text(b,nameof(DrugsFdaTherapeuticEquivalenceEntity.NormalizedApplicationNumber),16);RefMap.Text(b,nameof(DrugsFdaTherapeuticEquivalenceEntity.NormalizedProductNumber),16);RefMap.Text(b,nameof(DrugsFdaTherapeuticEquivalenceEntity.TherapeuticEquivalenceCode),100);}}
public sealed class NdcProductConfiguration:IEntityTypeConfiguration<NdcDirectoryProductEntity>{public void Configure(EntityTypeBuilder<NdcDirectoryProductEntity>b){RefMap.Snapshot<NdcDirectoryProductEntity,NdcDirectorySnapshotEntity>(b,"NdcDirectoryProduct",nameof(NdcDirectoryProductEntity.NdcDirectoryProductId),nameof(NdcDirectoryProductEntity.NdcDirectorySnapshotId));RefMap.Text(b,nameof(NdcDirectoryProductEntity.ProductNdcRaw),64);foreach(var p in new[]{nameof(NdcDirectoryProductEntity.ApplicationNumberRaw),nameof(NdcDirectoryProductEntity.GenericNameRaw),nameof(NdcDirectoryProductEntity.BrandNameRaw),nameof(NdcDirectoryProductEntity.DosageFormRaw),nameof(NdcDirectoryProductEntity.RouteRaw),nameof(NdcDirectoryProductEntity.MarketingCategoryRaw),nameof(NdcDirectoryProductEntity.LabelerNameRaw)})RefMap.Text(b,p,1000,false);b.HasIndex(x=>x.NormalizedProductNdc);b.HasIndex(x=>x.NormalizedApplicationNumber);}}
public sealed class NdcPackageConfiguration:IEntityTypeConfiguration<NdcDirectoryPackageEntity>{public void Configure(EntityTypeBuilder<NdcDirectoryPackageEntity>b){RefMap.Snapshot<NdcDirectoryPackageEntity,NdcDirectorySnapshotEntity>(b,"NdcDirectoryPackage",nameof(NdcDirectoryPackageEntity.NdcDirectoryPackageId),nameof(NdcDirectoryPackageEntity.NdcDirectorySnapshotId));RefMap.Text(b,nameof(NdcDirectoryPackageEntity.PackageNdcRaw),64);RefMap.Text(b,nameof(NdcDirectoryPackageEntity.ProductNdcRaw),64);RefMap.Text(b,nameof(NdcDirectoryPackageEntity.DescriptionRaw),2000,false);b.HasIndex(x=>x.NormalizedPackageNdc);}}
public sealed class RxNormConceptConfiguration:IEntityTypeConfiguration<RxNormConceptEntity>{public void Configure(EntityTypeBuilder<RxNormConceptEntity>b){RefMap.Snapshot<RxNormConceptEntity,RxNormSnapshotEntity>(b,"RxNormConcept",nameof(RxNormConceptEntity.RxNormConceptId),nameof(RxNormConceptEntity.RxNormSnapshotId));foreach(var p in new[]{nameof(RxNormConceptEntity.RxCui),nameof(RxNormConceptEntity.TermType),nameof(RxNormConceptEntity.SourceVocabulary),nameof(RxNormConceptEntity.SourceCode),nameof(RxNormConceptEntity.SuppressFlag)})RefMap.Text(b,p,128);RefMap.Text(b,nameof(RxNormConceptEntity.NameRaw),2000);b.HasIndex(x=>x.RxCui);}}
public sealed class RxNormNdcConfiguration:IEntityTypeConfiguration<RxNormNdcAssociationEntity>{public void Configure(EntityTypeBuilder<RxNormNdcAssociationEntity>b){RefMap.Snapshot<RxNormNdcAssociationEntity,RxNormSnapshotEntity>(b,"RxNormNdcAssociation",nameof(RxNormNdcAssociationEntity.RxNormNdcAssociationId),nameof(RxNormNdcAssociationEntity.RxNormSnapshotId));RefMap.Text(b,nameof(RxNormNdcAssociationEntity.RxCui),128);RefMap.Text(b,nameof(RxNormNdcAssociationEntity.NdcRaw),64);RefMap.Text(b,nameof(RxNormNdcAssociationEntity.SourceVocabulary),128);b.HasIndex(x=>x.NormalizedNdc);b.HasIndex(x=>x.RxCui);}}
public sealed class ProductFamilyConfiguration:IEntityTypeConfiguration<ProductFamilyIdentityEntity>{public void Configure(EntityTypeBuilder<ProductFamilyIdentityEntity>b){b.ToTable("ProductFamilyIdentity","reference");b.HasKey(x=>x.ProductFamilyIdentityId);foreach(var p in new[]{nameof(ProductFamilyIdentityEntity.IdentityHash),nameof(ProductFamilyIdentityEntity.NormalizedApplicationNumber),nameof(ProductFamilyIdentityEntity.NormalizedProductNumber),nameof(ProductFamilyIdentityEntity.NormalizedIngredientSet),nameof(ProductFamilyIdentityEntity.DosageForm),nameof(ProductFamilyIdentityEntity.Route),nameof(ProductFamilyIdentityEntity.NormalizedStrength),nameof(ProductFamilyIdentityEntity.RuleVersion),nameof(ProductFamilyIdentityEntity.Status)})RefMap.Text(b,p,p.EndsWith("Hash")?64:1000);b.HasIndex(x=>x.IdentityHash).IsUnique();b.HasIndex(x=>new{x.NormalizedApplicationNumber,x.NormalizedProductNumber});}}
public sealed class ProductMappingEvidenceConfiguration:IEntityTypeConfiguration<ProductMappingEvidenceEntity>{public void Configure(EntityTypeBuilder<ProductMappingEvidenceEntity>b){b.ToTable("ProductMappingEvidence","reference");b.HasKey(x=>x.ProductMappingEvidenceId);foreach(var p in new[]{nameof(ProductMappingEvidenceEntity.MedicaidNormalizedNdc),nameof(ProductMappingEvidenceEntity.EvidenceType),nameof(ProductMappingEvidenceEntity.MappingTier),nameof(ProductMappingEvidenceEntity.ConfidenceClass),nameof(ProductMappingEvidenceEntity.RuleVersion),nameof(ProductMappingEvidenceEntity.SourceSnapshotType),nameof(ProductMappingEvidenceEntity.SourceRecordHash),nameof(ProductMappingEvidenceEntity.DecisionStatus)})RefMap.Text(b,p,128);b.Property(x=>x.EvidenceJson).HasColumnType("nvarchar(max)").IsRequired();b.HasOne<ProductFamilyIdentityEntity>().WithMany().HasForeignKey(x=>x.ProductFamilyIdentityId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.MedicaidNormalizedNdc,x.RuleVersion,x.SourceSnapshotType,x.SourceSnapshotId,x.SourceRowNumber}).IsUnique();}}
