using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PharmaAccess.Data.Entities;
using PharmaAccess.Domain.Research;

namespace PharmaAccess.Data.Configurations;

public sealed class ResearchProtocolConfiguration : IEntityTypeConfiguration<ResearchProtocol> { public void Configure(EntityTypeBuilder<ResearchProtocol> b) { b.ToTable("ResearchProtocol", "research"); b.HasKey(x => x.ResearchProtocolId); b.Property(x => x.ProtocolCode).HasMaxLength(64).IsRequired(); b.Property(x => x.ProtocolVersion).HasMaxLength(32).IsRequired(); b.HasIndex(x => new { x.ProtocolCode, x.ProtocolVersion }).IsUnique(); b.Property(x => x.Status).HasConversion<string>().HasMaxLength(32); b.Property(x => x.DefinitionHash).HasMaxLength(64).IsRequired(); b.HasIndex(x => x.DefinitionHash).IsUnique(); foreach (var p in new[] { nameof(ResearchProtocol.InclusionRulesJson), nameof(ResearchProtocol.ExclusionRulesJson), nameof(ResearchProtocol.SensitivityAnalysisPlan), nameof(ResearchProtocol.SubgroupAnalysisPlan) }) b.Property(p).HasColumnType("nvarchar(max)"); } }
public sealed class ResearchDataFreezeConfiguration : IEntityTypeConfiguration<ResearchDataFreeze> { public void Configure(EntityTypeBuilder<ResearchDataFreeze> b) { b.ToTable("ResearchDataFreeze", "research"); b.HasKey(x => x.ResearchDataFreezeId); b.Property(x => x.FreezeCode).HasMaxLength(64).IsRequired(); b.Property(x => x.FreezeVersion).HasMaxLength(32).IsRequired(); b.HasIndex(x => new { x.FreezeCode, x.FreezeVersion }).IsUnique(); b.Property(x => x.Status).HasConversion<string>().HasMaxLength(32); foreach (var p in new[] { nameof(ResearchDataFreeze.SourceManifestHash), nameof(ResearchDataFreeze.DatasetHash), nameof(ResearchDataFreeze.CohortHash), nameof(ResearchDataFreeze.FeatureSchemaHash), nameof(ResearchDataFreeze.PredictiveSplitHash), nameof(ResearchDataFreeze.CausalProtocolHash), nameof(ResearchDataFreeze.PythonEnvironmentHash), nameof(ResearchDataFreeze.DotNetEnvironmentHash) }) b.Property(p).HasMaxLength(64).IsRequired(); b.HasOne<ResearchProtocol>().WithMany().HasForeignKey(x => x.ResearchProtocolId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PharmaAccess.Domain.Entities.DatasetVersion>().WithMany().HasForeignKey(x => x.DatasetVersionId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PharmaAccess.Domain.Features.FeatureSetVersion>().WithMany().HasForeignKey(x => x.FeatureSetVersionId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ResearchSourceRegistrationConfiguration : IEntityTypeConfiguration<ResearchSourceRegistration> { public void Configure(EntityTypeBuilder<ResearchSourceRegistration> b) { b.ToTable("ResearchSourceRegistration", "research"); b.HasKey(x => x.SourceRegistryId); b.Property(x => x.SourceCode).HasMaxLength(64).IsRequired(); b.HasIndex(x => x.SourceCode); b.HasIndex(x => new { x.SourceCode, x.Sha256 }).IsUnique(); b.Property(x => x.SourceType).HasConversion<string>().HasMaxLength(64); b.Property(x => x.ValidationStatus).HasConversion<string>().HasMaxLength(32); b.Property(x => x.Sha256).HasMaxLength(64).IsRequired(); b.HasIndex(x => x.Sha256); b.Property(x => x.RegisteredPath).HasMaxLength(1024).IsRequired(); b.Property(x => x.ValidationMessages).HasColumnType("nvarchar(max)"); } }
public abstract class ResearchEntityConfiguration<T> : IEntityTypeConfiguration<T> where T : class { protected abstract string Table { get; } public void Configure(EntityTypeBuilder<T> b) { b.ToTable(Table, "research"); ConfigureEntity(b); } protected abstract void ConfigureEntity(EntityTypeBuilder<T> b); protected static void Text(EntityTypeBuilder<T> b, string name, int length) => b.Property(name).HasMaxLength(length).IsRequired(); }
public sealed class ResearchProtocolApprovalConfiguration : ResearchEntityConfiguration<ResearchProtocolApprovalEntity> { protected override string Table => "ResearchProtocolApproval"; protected override void ConfigureEntity(EntityTypeBuilder<ResearchProtocolApprovalEntity> b) { b.HasKey(x => x.ResearchProtocolApprovalId); Text(b, nameof(ResearchProtocolApprovalEntity.Decision), 32); Text(b, nameof(ResearchProtocolApprovalEntity.Actor), 256); Text(b, nameof(ResearchProtocolApprovalEntity.Reason), 2000); b.HasIndex(x => new { x.ResearchProtocolId, x.DecidedAtUtc }); b.HasOne<ResearchProtocol>().WithMany().HasForeignKey(x => x.ResearchProtocolId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ResearchFreezeSourceConfiguration : ResearchEntityConfiguration<ResearchFreezeSourceEntity> { protected override string Table => "ResearchFreezeSource"; protected override void ConfigureEntity(EntityTypeBuilder<ResearchFreezeSourceEntity> b) { b.HasKey(x => x.ResearchFreezeSourceId); Text(b, nameof(ResearchFreezeSourceEntity.SourceSha256), 64); Text(b, nameof(ResearchFreezeSourceEntity.SchemaProfileVersion), 64); b.HasIndex(x => new { x.ResearchDataFreezeId, x.ResearchSourceRegistrationId }).IsUnique(); b.HasOne<ResearchDataFreeze>().WithMany().HasForeignKey(x => x.ResearchDataFreezeId).OnDelete(DeleteBehavior.Restrict); b.HasOne<ResearchSourceRegistration>().WithMany().HasForeignKey(x => x.ResearchSourceRegistrationId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ResearchFreezeFindingConfiguration : ResearchEntityConfiguration<ResearchFreezeFindingEntity> { protected override string Table => "ResearchFreezeFinding"; protected override void ConfigureEntity(EntityTypeBuilder<ResearchFreezeFindingEntity> b) { b.HasKey(x => x.ResearchFreezeFindingId); Text(b, nameof(ResearchFreezeFindingEntity.Code), 128); Text(b, nameof(ResearchFreezeFindingEntity.Severity), 32); Text(b, nameof(ResearchFreezeFindingEntity.Description), 2000); Text(b, nameof(ResearchFreezeFindingEntity.Recommendation), 2000); b.HasIndex(x => new { x.ResearchDataFreezeId, x.Severity, x.Code }); b.HasOne<ResearchDataFreeze>().WithMany().HasForeignKey(x => x.ResearchDataFreezeId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ResearchFreezeArtifactConfiguration : ResearchEntityConfiguration<ResearchFreezeArtifactEntity> { protected override string Table => "ResearchFreezeArtifact"; protected override void ConfigureEntity(EntityTypeBuilder<ResearchFreezeArtifactEntity> b) { b.HasKey(x => x.ResearchFreezeArtifactId); Text(b, nameof(ResearchFreezeArtifactEntity.ArtifactType), 128); Text(b, nameof(ResearchFreezeArtifactEntity.RelativePath), 1024); Text(b, nameof(ResearchFreezeArtifactEntity.Sha256), 64); b.HasIndex(x => new { x.ResearchDataFreezeId, x.ArtifactType }).IsUnique(); b.HasOne<ResearchDataFreeze>().WithMany().HasForeignKey(x => x.ResearchDataFreezeId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ResearchCohortDefinitionConfiguration : ResearchEntityConfiguration<ResearchCohortDefinitionEntity> { protected override string Table => "ResearchCohortDefinition"; protected override void ConfigureEntity(EntityTypeBuilder<ResearchCohortDefinitionEntity> b) { b.HasKey(x => x.ResearchCohortDefinitionId); Text(b, nameof(ResearchCohortDefinitionEntity.VersionCode), 64); Text(b, nameof(ResearchCohortDefinitionEntity.DefinitionHash), 64); b.Property(x => x.RulesJson).HasColumnType("nvarchar(max)"); b.HasIndex(x => x.VersionCode).IsUnique(); b.HasIndex(x => x.DefinitionHash).IsUnique(); } }
public sealed class ResearchExclusionRuleConfiguration : ResearchEntityConfiguration<ResearchExclusionRuleEntity> { protected override string Table => "ResearchExclusionRule"; protected override void ConfigureEntity(EntityTypeBuilder<ResearchExclusionRuleEntity> b) { b.HasKey(x => x.ResearchExclusionRuleId); Text(b, nameof(ResearchExclusionRuleEntity.RuleCode), 128); Text(b, nameof(ResearchExclusionRuleEntity.Description), 2000); b.HasIndex(x => new { x.ResearchCohortDefinitionId, x.RuleCode }).IsUnique(); b.HasOne<ResearchCohortDefinitionEntity>().WithMany().HasForeignKey(x => x.ResearchCohortDefinitionId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ResearchAnalysisPlanConfiguration : ResearchEntityConfiguration<ResearchAnalysisPlanEntity> { protected override string Table => "ResearchAnalysisPlan"; protected override void ConfigureEntity(EntityTypeBuilder<ResearchAnalysisPlanEntity> b) { b.HasKey(x => x.ResearchAnalysisPlanId); Text(b, nameof(ResearchAnalysisPlanEntity.PlanType), 64); Text(b, nameof(ResearchAnalysisPlanEntity.VersionCode), 64); Text(b, nameof(ResearchAnalysisPlanEntity.DefinitionHash), 64); b.Property(x => x.DefinitionJson).HasColumnType("nvarchar(max)"); b.HasIndex(x => new { x.ResearchProtocolId, x.PlanType, x.VersionCode }).IsUnique(); b.HasOne<ResearchProtocol>().WithMany().HasForeignKey(x => x.ResearchProtocolId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ResearchDatabaseOwnershipConfiguration : ResearchEntityConfiguration<ResearchDatabaseOwnershipEntity> { protected override string Table => "ResearchDatabaseOwnership"; protected override void ConfigureEntity(EntityTypeBuilder<ResearchDatabaseOwnershipEntity> b) { b.HasKey(x => x.ResearchDatabaseOwnershipId); Text(b, nameof(ResearchDatabaseOwnershipEntity.ProjectId), 128); Text(b, nameof(ResearchDatabaseOwnershipEntity.RepositoryMarker), 128); Text(b, nameof(ResearchDatabaseOwnershipEntity.CreatedBy), 256); b.HasIndex(x => x.ProjectId).IsUnique(); } }
