using System.Globalization;
using System.Text;
using System.Text.Json;
namespace PharmaAccess.Application.MachineLearning;
public sealed record SafePredictionExport(string Mode,int GenericLaunchId,string LaunchDisplay,int AsOfQuarter,int TargetQuarter,IReadOnlyList<HistoricalReplayStateResult> RankedStates,double SelectedThreshold,string ModelVersion,string DatasetVersion,string FeatureSetVersion,ModelApprovalStatus GovernanceStatus,bool ProductionApproved);
public sealed record PredictionExportFiles(string Csv,string Json,string CsvFileName,string JsonFileName);
public static class PredictionResultExport
{
 public static PredictionExportFiles Create(SafePredictionExport x){var stem=$"next-state-prediction-{Safe(x.LaunchDisplay)}-{Quarter(x.AsOfQuarter)}";var rows=x.RankedStates.OrderBy(s=>s.Rank).Select(s=>new{x.Mode,x.GenericLaunchId,x.LaunchDisplay,x.AsOfQuarter,x.TargetQuarter,s.Rank,s.StateId,s.StateCode,s.StateName,s.Probability,s.AboveSelectedThreshold,x.SelectedThreshold,x.ModelVersion,x.DatasetVersion,x.FeatureSetVersion,GovernanceStatus=x.GovernanceStatus.ToString(),x.ProductionApproved}).ToArray();var b=new StringBuilder("Mode,GenericLaunchId,LaunchDisplay,AsOfQuarter,TargetQuarter,Rank,StateId,StateCode,StateName,Probability,AboveSelectedThreshold,SelectedThreshold,ModelVersion,DatasetVersion,FeatureSetVersion,GovernanceStatus,ProductionApproved\n");foreach(var r in rows)b.AppendLine(string.Join(',',Csv(r.Mode),r.GenericLaunchId,Csv(r.LaunchDisplay),r.AsOfQuarter,r.TargetQuarter,r.Rank,r.StateId,Csv(r.StateCode),Csv(r.StateName),r.Probability.ToString("R",CultureInfo.InvariantCulture),r.AboveSelectedThreshold,r.SelectedThreshold.ToString("R",CultureInfo.InvariantCulture),Csv(r.ModelVersion),Csv(r.DatasetVersion),Csv(r.FeatureSetVersion),r.GovernanceStatus,r.ProductionApproved));return new(b.ToString(),JsonSerializer.Serialize(rows,new JsonSerializerOptions{WriteIndented=true}),stem+".csv",stem+".json");}
 static string Csv(string value)=>'"'+value.Replace("\"","\"\"")+'"';static string Quarter(int q)=>$"{q/10}-Q{q%10}";static string Safe(string value){var s=new string(value.ToLowerInvariant().Select(c=>char.IsLetterOrDigit(c)?c:'-').ToArray());while(s.Contains("--",StringComparison.Ordinal))s=s.Replace("--","-",StringComparison.Ordinal);s=s.Trim('-');return string.IsNullOrEmpty(s)?"launch":s[..Math.Min(80,s.Length)];}
}
