using System.Globalization;
using System.Text;
using System.Text.Json;
namespace PharmaAccess.Application.MachineLearning;
public sealed record SafePredictionExport(string Mode,int GenericLaunchId,string LaunchDisplay,int AsOfQuarter,int TargetQuarter,IReadOnlyList<HistoricalReplayStateResult> RankedStates,double SelectedThreshold,string ModelVersion,string DatasetVersion,string FeatureSetVersion,ModelApprovalStatus GovernanceStatus,bool ProductionApproved){public string? DrugName{get;init;}public string? ActiveIngredient{get;init;}public string? Anda{get;init;}public DateOnly? ApprovalDate{get;init;}public IReadOnlyList<StateMarketContext> MarketContexts{get;init;}=[];}
public sealed record PredictionExportFiles(string Csv,string Json,string CsvFileName,string JsonFileName);
public static class PredictionResultExport
{
 public static PredictionExportFiles Create(SafePredictionExport x)
 {
  var stem=$"next-state-prediction-{Safe(x.DrugName??x.Anda??x.LaunchDisplay)}-{Quarter(x.AsOfQuarter)}";var contexts=x.MarketContexts.ToDictionary(c=>c.StateId);
  var rows=x.RankedStates.OrderBy(s=>s.Rank).Select(s=>{contexts.TryGetValue(s.StateId,out var c);return new{x.DrugName,x.ActiveIngredient,x.Anda,x.ApprovalDate,x.Mode,x.GenericLaunchId,x.LaunchDisplay,x.AsOfQuarter,x.TargetQuarter,s.Rank,s.StateId,s.StateCode,s.StateName,s.Probability,s.AboveSelectedThreshold,x.SelectedThreshold,x.ModelVersion,x.DatasetVersion,x.FeatureSetVersion,GovernanceStatus=x.GovernanceStatus.ToString(),x.ProductionApproved,c?.RecentMarketVolume,c?.MarketSizeScore,c?.HistoricalBaselineVolume,c?.HistoricalBaselineMarketWeight,c?.StateMarketGrowthRate,c?.GrowthMomentumScore,c?.RecentWindowVolume,c?.PriorWindowVolume,DataSupport=c?.DataSupport.ToString(),c?.MarketProfile,MarketContextAsOfQuarter=c?.AsOfQuarter};}).ToArray();
  var b=new StringBuilder("DrugName,ActiveIngredient,ANDA,ApprovalDate,Mode,GenericLaunchId,LaunchDisplay,AsOfQuarter,TargetQuarter,Rank,StateId,StateCode,StateName,Probability,AboveSelectedThreshold,SelectedThreshold,ModelVersion,DatasetVersion,FeatureSetVersion,GovernanceStatus,ProductionApproved,RecentMarketVolume,MarketSizeScore,HistoricalBaselineVolume,HistoricalBaselineMarketWeight,StateMarketGrowthRate,GrowthMomentumScore,RecentWindowVolume,PriorWindowVolume,DataSupport,MarketProfile,MarketContextAsOfQuarter\n");
  foreach(var r in rows)b.AppendLine(string.Join(',',Csv(r.DrugName??""),Csv(r.ActiveIngredient??""),Csv(r.Anda??""),r.ApprovalDate?.ToString("yyyy-MM-dd")??"",Csv(r.Mode),r.GenericLaunchId,Csv(r.LaunchDisplay),r.AsOfQuarter,r.TargetQuarter,r.Rank,r.StateId,Csv(r.StateCode),Csv(r.StateName),r.Probability.ToString("R",CultureInfo.InvariantCulture),r.AboveSelectedThreshold,r.SelectedThreshold.ToString("R",CultureInfo.InvariantCulture),Csv(r.ModelVersion),Csv(r.DatasetVersion),Csv(r.FeatureSetVersion),r.GovernanceStatus,r.ProductionApproved,L(r.RecentMarketVolume),F(r.MarketSizeScore),L(r.HistoricalBaselineVolume),F(r.HistoricalBaselineMarketWeight),F(r.StateMarketGrowthRate),F(r.GrowthMomentumScore),L(r.RecentWindowVolume),L(r.PriorWindowVolume),r.DataSupport??"",Csv(r.MarketProfile??""),r.MarketContextAsOfQuarter?.ToString(CultureInfo.InvariantCulture)??""));
  return new(b.ToString(),JsonSerializer.Serialize(rows,new JsonSerializerOptions{WriteIndented=true}),stem+".csv",stem+".json");
 }
 static string F(decimal? value)=>value?.ToString(CultureInfo.InvariantCulture)??"";static string L(long? value)=>value?.ToString(CultureInfo.InvariantCulture)??"";
 static string Csv(string value)=>'"'+value.Replace("\"","\"\"")+'"';static string Quarter(int q)=>$"{q/10}-Q{q%10}";static string Safe(string value){var s=new string(value.ToLowerInvariant().Select(c=>char.IsLetterOrDigit(c)?c:'-').ToArray());while(s.Contains("--",StringComparison.Ordinal))s=s.Replace("--","-",StringComparison.Ordinal);s=s.Trim('-');return string.IsNullOrEmpty(s)?"launch":s[..Math.Min(80,s.Length)];}
}
