using PharmaAccess.Application.Causal;
using PharmaAccess.Domain.Causal;
using Xunit;

namespace PharmaAccess.Causal.Tests;

public sealed class MilestoneSixCausalTests
{
    [Fact] public void Propensity_excludes_outcome_is_deterministic_and_bounded(){var rows=Analysis();var model=new LogisticNuisanceModel();var a=model.Fit(rows,Vars,new());var b=model.Fit(rows,Vars,new());Assert.Equal(a.Scores,b.Scores);Assert.All(a.Scores,x=>Assert.InRange(x,.02,.98));Assert.Throws<InvalidOperationException>(()=>model.Fit(rows,["OutcomeValue"],new()));}
    [Fact] public void Att_and_ate_weights_match_formulas_and_report_ess(){var rows=Analysis().Take(2).ToArray();rows=[rows[0] with{BinaryTreatment=true},rows[1] with{BinaryTreatment=false}];var att=PropensityWeighting.Calculate(rows,[.8,.25],EstimandType.AverageTreatmentEffectOnTreated,new());Assert.Equal(1,att.Weights[0]);Assert.Equal(1d/3,att.Weights[1],8);var ate=PropensityWeighting.Calculate(rows,[.8,.25],EstimandType.AverageTreatmentEffect,new());Assert.Equal(1.25,ate.Weights[0],8);Assert.Equal(4d/3,ate.Weights[1],8);Assert.True(ate.EffectiveSampleSize>0);}
    [Fact] public void Extreme_weights_and_positivity_failures_are_visible(){var rows=Analysis();var scores=rows.Select((r,i)=>r.BinaryTreatment ? .001 : .999).ToArray();var weights=PropensityWeighting.Calculate(rows,scores,EstimandType.AverageTreatmentEffectOnTreated,new(2));var diagnostic=CausalDiagnostics.Positivity(rows,scores,weights,new(.1,1000,10,10));Assert.True(weights.ExtremeWeightCount>0);Assert.Equal(DiagnosticStatus.Failed,diagnostic.Status);}
    [Fact] public void Balance_reports_smd_weighted_smd_and_failed_imbalance(){var rows=Analysis(imbalanced:true);var balance=CausalDiagnostics.Balance(rows,Enumerable.Repeat(1d,rows.Length).ToArray(),Vars,.1);Assert.Contains(balance,x=>Math.Abs(x.StandardizedMeanDifference)>.1);Assert.All(balance,x=>Assert.False(double.IsNaN(x.WeightedStandardizedMeanDifference)));}
    [Fact] public void Four_estimators_run_and_unadjusted_is_descriptive(){var rows=Analysis();var p=new LogisticNuisanceModel().Fit(rows,Vars,new());var w=PropensityWeighting.Calculate(rows,p.Scores,EstimandType.AverageTreatmentEffectOnTreated,new());var raw=CausalEstimators.Unadjusted(rows,EstimandType.AverageTreatmentEffectOnTreated);var weighted=CausalEstimators.Weighted(rows,w,EstimandType.AverageTreatmentEffectOnTreated);var or=CausalEstimators.OutcomeRegression(rows,Vars,EstimandType.AverageTreatmentEffectOnTreated);var aipw=CausalEstimators.Aipw(rows,p.Scores,or.M1,or.M0,EstimandType.AverageTreatmentEffectOnTreated);Assert.Equal(CausalEstimateStatus.DescriptiveOnly,raw.Status);Assert.All([raw,weighted,or.Result,aipw],x=>Assert.InRange(x.Estimate,-1,1));}
    [Fact] public void Estimators_reject_missing_treatment_groups(){var rows=Analysis().Select(x=>x with{BinaryTreatment=true}).ToArray();Assert.Throws<InvalidOperationException>(()=>CausalEstimators.Unadjusted(rows,EstimandType.AverageTreatmentEffect));}
    [Fact] public void Grouped_bootstrap_is_deterministic_clustered_and_cancellable(){var rows=Analysis();var config=new BootstrapConfiguration(20,17,10);var service=new GroupedBootstrap();var a=service.Run(rows,config,x=>CausalEstimators.Unadjusted(x,EstimandType.AverageTreatmentEffect).Estimate);var b=service.Run(rows,config,x=>CausalEstimators.Unadjusted(x,EstimandType.AverageTreatmentEffect).Estimate);Assert.Equal(a,b);Assert.True(a.Lower<=a.Upper);using var cts=new CancellationTokenSource();cts.Cancel();Assert.Throws<OperationCanceledException>(()=>service.Run(rows,config,x=>0,cts.Token));}
    [Fact] public async Task Cohort_dry_run_excludes_censoring_and_is_reproducible_without_persistence(){var input=SyntheticCausalData.Create();var command=Command(true);var runner=new CausalStudyRunner();var a=await runner.RunAsync(command,input);var b=await runner.RunAsync(command,input);Assert.True(a.DryRun);Assert.Equal(a.ReproducibilityHash,b.ReproducibilityHash);Assert.True(a.ExcludedRows["CensoredOrMissingOutcome"]>0);Assert.Empty(a.Estimates);}
    [Fact] public async Task Synthetic_pipeline_runs_diagnostics_estimators_placebos_sensitivity_and_heterogeneity(){var result=await new CausalStudyRunner().RunAsync(Command(false),SyntheticCausalData.Create());Assert.True(result.EligibleRowCount>50);Assert.Equal(4,result.Estimates.Count);Assert.InRange(result.Estimates.Single(x=>x.Estimator==CausalEstimatorKind.AugmentedInverseProbabilityWeighting).Estimate,.08,.30);Assert.NotNull(result.Positivity);Assert.Equal(3,result.Placebos.Count);Assert.True(result.Sensitivity.Count>=6);Assert.NotEmpty(result.Heterogeneity);Assert.Contains(result.Warnings,x=>x.Contains("Cross-fitting"));}
    [Fact] public void Counterfactuals_preserve_baseline_and_flag_support(){var estimate=CausalEstimators.Unadjusted(Analysis(),EstimandType.AverageTreatmentEffect);var service=new CounterfactualScenarioService();var supported=service.Evaluate(1,estimate with{Status=CausalEstimateStatus.Estimated},new("scenario-v1","IncreaseNeighborExposure",.5,.1,.9),.2);var outside=service.Evaluate(1,estimate with{Status=CausalEstimateStatus.Estimated},new("scenario-v2","Unsupported",.95,.1,.9),.2);Assert.Equal(.2,supported.BaselinePredictedOutcome);Assert.Equal(SimulationSupportStatus.Supported,supported.SupportStatus);Assert.Equal(SimulationSupportStatus.Extrapolative,outside.SupportStatus);Assert.Contains(outside.Limitations,x=>x.Contains("not a guaranteed"));}
    [Fact] public async Task Synthetic_reports_are_complete_labeled_and_reproducible(){var result=await new CausalStudyRunner().RunAsync(Command(false),SyntheticCausalData.Create());var configured=Environment.GetEnvironmentVariable("PHARMAACCESS_M6_REPORT_PATH");var root=configured??Path.Combine(Path.GetTempPath(),$"pa-m6-{Guid.NewGuid():N}");try{var writer=new CausalReportWriter();var a=writer.Write(root,Command(false),result);var b=writer.Write(root,Command(false),result);Assert.Equal(12,a.Count);Assert.Equal(a.Select(x=>x.Sha256),b.Select(x=>x.Sha256));Assert.All(Directory.GetFiles(root,"*.md"),x=>Assert.Contains(CausalReportWriter.SyntheticNotice,File.ReadAllText(x)));}finally{if(configured is null&&Directory.Exists(root))Directory.Delete(root,true);}}
    private static readonly string[] Vars=["QuarterSinceApproval","StateDataCompleteness","StateHistoricalEntryRate","StateHistoricalGenericVolume","StateHistoricalMarketWeight"];
    private static CausalAnalysisRowContract[] Analysis(bool imbalanced=false)=>SyntheticCausalData.Create(20,8,17,false,imbalanced).Where(x=>x.Outcome.HasValue).Select(x=>new CausalAnalysisRowContract(x.FeatureRowId,x.GenericLaunchId,x.DrugId,x.StateId,x.Region,x.LaunchCohort,x.ObservationQuarterId,x.OutcomeQuarterId,x.QuarterSinceApproval,x.ContinuousExposure,x.BinaryTreatment!.Value,x.Outcome!.Value,x.Confounders.ToDictionary(y=>y.Key,y=>y.Value!.Value),x.HistoricalVolumeBand,x.NationalDiffusionBand,x.FeatureRowId.ToString())).ToArray();
    private static RunCausalStudyCommand Command(bool dry)=>new(1,1,1,"neighbor-v1","next-entry-v1","dag-v1","adjust-v1",EstimandType.AverageTreatmentEffectOnTreated,Enum.GetValues<CausalEstimatorKind>(),20210,20214,MissingDataPolicy.CompleteCase,new(),new(),new(20,17,10),new(.2,10,5,5),dry,"corr-m6","synthetic-test");
}
