using PharmaAccess.Domain.Causal;

namespace PharmaAccess.Data.Entities;

public sealed class CausalStudyEntity { private CausalStudyEntity(){} public long CausalStudyId{get;private set;} public string StudyCode{get;private set;}=null!; public string StudyName{get;private set;}=null!; public string ResearchQuestion{get;private set;}=null!; public int DatasetVersionId{get;private set;} public int FeatureSetVersionId{get;private set;} public long CausalDagDefinitionId{get;private set;} public long CausalAdjustmentSetId{get;private set;} public long TreatmentDefinitionId{get;private set;} public string OutcomeDefinitionVersion{get;private set;}=null!; public EstimandType Estimand{get;private set;} public string TargetPopulation{get;private set;}=null!; public int ObservationStartQuarterId{get;private set;} public int ObservationEndQuarterId{get;private set;} public CausalStudyStatus Status{get;private set;} public AssumptionStatus AssumptionStatus{get;private set;} public DateTime CreatedAtUtc{get;private set;} public DateTime? FinalizedAtUtc{get;private set;} public string? CodeCommitHash{get;private set;} public string? Notes{get;private set;} }
public sealed class CausalDagDefinitionEntity { private CausalDagDefinitionEntity(){} public long CausalDagDefinitionId{get;private set;} public string VersionCode{get;private set;}=null!; public string Name{get;private set;}=null!; public string? Description{get;private set;} public string DefinitionJson{get;private set;}=null!; public string DefinitionHash{get;private set;}=null!; public DateTime CreatedAtUtc{get;private set;} public DefinitionStatus Status{get;private set;} public string? Notes{get;private set;} }
public sealed class CausalAdjustmentSetEntity { private CausalAdjustmentSetEntity(){} public long CausalAdjustmentSetId{get;private set;} public string VersionCode{get;private set;}=null!; public string Name{get;private set;}=null!; public string VariablesJson{get;private set;}=null!; public string DefinitionHash{get;private set;}=null!; public DateTime CreatedAtUtc{get;private set;} public DefinitionStatus Status{get;private set;} public string? Notes{get;private set;} }
public sealed class TreatmentDefinitionEntity { private TreatmentDefinitionEntity(){} public long TreatmentDefinitionId{get;private set;} public string VersionCode{get;private set;}=null!; public string TreatmentName{get;private set;}=null!; public ExposureType ExposureType{get;private set;} public double Threshold{get;private set;} public int MinimumPeerCount{get;private set;} public int LagQuarters{get;private set;} public string ReferenceVersion{get;private set;}=null!; public string DefinitionJson{get;private set;}=null!; public string DefinitionHash{get;private set;}=null!; public DateTime CreatedAtUtc{get;private set;} public DefinitionStatus Status{get;private set;} }
public sealed class CausalAnalysisRowEntity { private CausalAnalysisRowEntity(){} public long CausalAnalysisRowId{get;private set;} public long CausalStudyId{get;private set;} public int DrugId{get;private set;} public int StateId{get;private set;} public int ObservationQuarterId{get;private set;} public int OutcomeQuarterId{get;private set;} public double TreatmentValue{get;private set;} public bool BinaryTreatment{get;private set;} public bool OutcomeValue{get;private set;} public bool IsCensored{get;private set;} public string EligibilityStatus{get;private set;}=null!; public string? ExclusionReason{get;private set;} public double? PropensityScore{get;private set;} public double? OutcomeRegressionTreated{get;private set;} public double? OutcomeRegressionUntreated{get;private set;} public double? InfluenceFunctionValue{get;private set;} public double? Weight{get;private set;} public DateTime GeneratedAtUtc{get;private set;} public string RowHash{get;private set;}=null!; }
public sealed class CausalEstimateEntity { private CausalEstimateEntity(){} public long CausalEstimateId{get;private set;} public long CausalStudyId{get;private set;} public string EstimatorName{get;private set;}=null!; public EstimandType Estimand{get;private set;} public EffectScale EffectScale{get;private set;} public double Estimate{get;private set;} public double? StandardError{get;private set;} public double? ConfidenceIntervalLower{get;private set;} public double? ConfidenceIntervalUpper{get;private set;} public double? PValue{get;private set;} public int? BootstrapRepetitions{get;private set;} public double? EffectiveSampleSize{get;private set;} public int TreatedCount{get;private set;} public int ControlCount{get;private set;} public CausalEstimateStatus Status{get;private set;} public DateTime CreatedAtUtc{get;private set;} public string Interpretation{get;private set;}=null!; public string Limitations{get;private set;}=null!; }
public sealed class CausalDiagnosticEntity { private CausalDiagnosticEntity(){} public long CausalDiagnosticId{get;private set;} public long CausalStudyId{get;private set;} public string DiagnosticType{get;private set;}=null!; public string? VariableName{get;private set;} public string MetricName{get;private set;}=null!; public double? MetricValue{get;private set;} public double? Threshold{get;private set;} public DiagnosticStatus Status{get;private set;} public DiagnosticSeverity Severity{get;private set;} public string Description{get;private set;}=null!; public string Recommendation{get;private set;}=null!; public DateTime CreatedAtUtc{get;private set;} }
public sealed class CounterfactualScenarioEntity { private CounterfactualScenarioEntity(){} public long CounterfactualScenarioId{get;private set;} public long CausalStudyId{get;private set;} public string ScenarioCode{get;private set;}=null!; public string ScenarioName{get;private set;}=null!; public string Description{get;private set;}=null!; public string InterventionDefinitionJson{get;private set;}=null!; public string BaselinePolicy{get;private set;}=null!; public ScenarioStatus Status{get;private set;} public DateTime CreatedAtUtc{get;private set;} public string? Notes{get;private set;} }
public sealed class CounterfactualResultEntity { private CounterfactualResultEntity(){} public long CounterfactualResultId{get;private set;} public long CounterfactualScenarioId{get;private set;} public int? DrugId{get;private set;} public int? StateId{get;private set;} public int? ObservationQuarterId{get;private set;} public double BaselinePredictedOutcome{get;private set;} public double InterventionPredictedOutcome{get;private set;} public double EstimatedDifference{get;private set;} public double? UncertaintyLower{get;private set;} public double? UncertaintyUpper{get;private set;} public SimulationSupportStatus SupportStatus{get;private set;} public string WarningMessagesJson{get;private set;}=null!; public DateTime CreatedAtUtc{get;private set;} }
