using PharmaAccess.Application.MachineLearning;

namespace PharmaAccess.Data.Entities;

public sealed class ModelCalibration { private ModelCalibration() { } public long ModelCalibrationId { get; private set; } public long ModelTrainingRunId { get; private set; } public CalibrationMethod Method { get; private set; } public CalibrationStatus Status { get; private set; } public double? Slope { get; private set; } public double? Intercept { get; private set; } public int ValidationRowCount { get; private set; } public DateTime CreatedAtUtc { get; private set; } public string? WarningsJson { get; private set; } }
public sealed class CalibrationMetricEntity { private CalibrationMetricEntity() { } public long CalibrationMetricId { get; private set; } public long ModelCalibrationId { get; private set; } public MlPartition Partition { get; private set; } public string MetricName { get; private set; } = null!; public double MetricValue { get; private set; } public DateTime CreatedAtUtc { get; private set; } }
public sealed class CalibrationBinEntity { private CalibrationBinEntity() { } public long CalibrationBinId { get; private set; } public long ModelCalibrationId { get; private set; } public MlPartition Partition { get; private set; } public CalibrationBinning Binning { get; private set; } public int BinNumber { get; private set; } public double LowerBound { get; private set; } public double UpperBound { get; private set; } public int RowCount { get; private set; } public double MeanProbability { get; private set; } public double ObservedRate { get; private set; } }
public sealed class FeatureImportanceEntity { private FeatureImportanceEntity() { } public long FeatureImportanceResultId { get; private set; } public long ModelTrainingRunId { get; private set; } public string FeatureName { get; private set; } = null!; public string MetricName { get; private set; } = null!; public double BaselineValue { get; private set; } public double PermutedValue { get; private set; } public double ImportanceDelta { get; private set; } public double StandardDeviation { get; private set; } public int RepetitionCount { get; private set; } public int Rank { get; private set; } public DateTime CreatedAtUtc { get; private set; } }
public sealed class SubgroupMetricEntity { private SubgroupMetricEntity() { } public long SubgroupMetricId { get; private set; } public long ModelTrainingRunId { get; private set; } public MlPartition Partition { get; private set; } public string Dimension { get; private set; } = null!; public string SubgroupValue { get; private set; } = null!; public string MetricName { get; private set; } = null!; public double? MetricValue { get; private set; } public int RowCount { get; private set; } public EvaluationStatus Status { get; private set; } public DateTime CreatedAtUtc { get; private set; } }
public sealed class ModelErrorAnalysisEntity { private ModelErrorAnalysisEntity() { } public long ModelErrorAnalysisId { get; private set; } public long ModelTrainingRunId { get; private set; } public int DrugId { get; private set; } public int StateId { get; private set; } public int ObservationQuarterId { get; private set; } public ErrorCategory Category { get; private set; } public bool ActualLabel { get; private set; } public double Probability { get; private set; } public bool PredictedLabel { get; private set; } public double Threshold { get; private set; } public int MissingFeatureCount { get; private set; } public UncertaintyStatus UncertaintyStatus { get; private set; } public string? ContextJson { get; private set; } public string? WarningsJson { get; private set; } public DateTime CreatedAtUtc { get; private set; } }
public sealed class ThresholdEvaluationEntity { private ThresholdEvaluationEntity() { } public long ThresholdEvaluationId { get; private set; } public long ModelTrainingRunId { get; private set; } public ThresholdPolicyKind Policy { get; private set; } public MlPartition Partition { get; private set; } public double Threshold { get; private set; } public string Objective { get; private set; } = null!; public string? ConstraintsJson { get; private set; } public double Precision { get; private set; } public double Recall { get; private set; } public double F1 { get; private set; } public double Specificity { get; private set; } public DateTime CreatedAtUtc { get; private set; } }
public sealed class ModelApprovalEntity { private ModelApprovalEntity() { } public long ModelApprovalId { get; private set; } public long ModelArtifactId { get; private set; } public ApprovalDecision Decision { get; private set; } public string ApprovedBy { get; private set; } = null!; public string ApprovalReason { get; private set; } = null!; public string TargetEnvironment { get; private set; } = null!; public bool PromoteToChampion { get; private set; } public string ModelCardVersion { get; private set; } = null!; public DateTime CreatedAtUtc { get; private set; } }
public sealed class ModelRegistryEntry { private ModelRegistryEntry() { } public long ModelRegistryEntryId { get; private set; } public long ModelArtifactId { get; private set; } public string TaskName { get; private set; } = null!; public string Environment { get; private set; } = null!; public ModelApprovalStatus Status { get; private set; } public bool IsChampion { get; private set; } public bool IsSynthetic { get; private set; } public DateTime CreatedAtUtc { get; private set; } public DateTime? UpdatedAtUtc { get; private set; } }
