namespace PharmaAccess.Data.Entities;

public abstract class ReferenceSnapshotEntity { public long ReferenceSnapshotId{get;set;} public long SourceRegistryId{get;set;} public string SnapshotCode{get;set;}=null!; public DateOnly ReleaseDate{get;set;} public string SourceSha256{get;set;}=null!; public string RelativeArchivePath{get;set;}=null!; public DateTime RetrievedAtUtc{get;set;} public long RowCount{get;set;} }
public sealed class OrangeBookSnapshotEntity:ReferenceSnapshotEntity { }
public sealed class OrangeBookProductEntity { public long OrangeBookProductId{get;set;} public long OrangeBookSnapshotId{get;set;} public long SourceRowNumber{get;set;} public string IngredientRaw{get;set;}=null!;public string? NormalizedIngredientSet{get;set;}public string DosageFormRouteRaw{get;set;}=null!;public string? DosageForm{get;set;}public string? Route{get;set;}public string TradeNameRaw{get;set;}=null!;public string ApplicantRaw{get;set;}=null!;public string StrengthRaw{get;set;}=null!;public string? NormalizedStrength{get;set;}public string ApplicationTypeRaw{get;set;}=null!;public string ApplicationNumberRaw{get;set;}=null!;public string? NormalizedApplicationNumber{get;set;}public string ProductNumberRaw{get;set;}=null!;public string? NormalizedProductNumber{get;set;}public string? TherapeuticEquivalenceCodeRaw{get;set;}public string ApprovalDateRaw{get;set;}=null!;public DateOnly? ApprovalDate{get;set;}public string? ReferenceListedDrugRaw{get;set;}public string? ReferenceStandardRaw{get;set;}public string ProductTypeRaw{get;set;}=null!;public string? ApplicantFullNameRaw{get;set;} }
public sealed class DrugsFdaSnapshotEntity:ReferenceSnapshotEntity { }
public sealed class DrugsFdaApplicationEntity { public long DrugsFdaApplicationId{get;set;}public long DrugsFdaSnapshotId{get;set;}public long SourceRowNumber{get;set;}public string ApplicationNumberRaw{get;set;}=null!;public string NormalizedApplicationNumber{get;set;}=null!;public string ApplicationTypeRaw{get;set;}=null!;public string? SponsorNameRaw{get;set;} }
public sealed class DrugsFdaProductEntity { public long DrugsFdaProductId{get;set;}public long DrugsFdaSnapshotId{get;set;}public long SourceRowNumber{get;set;}public string ApplicationNumberRaw{get;set;}=null!;public string NormalizedApplicationNumber{get;set;}=null!;public string ProductNumberRaw{get;set;}=null!;public string NormalizedProductNumber{get;set;}=null!;public string? FormRaw{get;set;}public string? StrengthRaw{get;set;}public string? DrugNameRaw{get;set;}public string? ActiveIngredientRaw{get;set;}public bool? ReferenceDrug{get;set;}public bool? ReferenceStandard{get;set;} }
public sealed class DrugsFdaMarketingStatusEntity { public long DrugsFdaMarketingStatusId{get;set;}public long DrugsFdaSnapshotId{get;set;}public long SourceRowNumber{get;set;}public string NormalizedApplicationNumber{get;set;}=null!;public string NormalizedProductNumber{get;set;}=null!;public int MarketingStatusCode{get;set;}public string? MarketingStatusDescription{get;set;} }
public sealed class DrugsFdaTherapeuticEquivalenceEntity { public long DrugsFdaTherapeuticEquivalenceId{get;set;}public long DrugsFdaSnapshotId{get;set;}public long SourceRowNumber{get;set;}public string NormalizedApplicationNumber{get;set;}=null!;public string NormalizedProductNumber{get;set;}=null!;public string TherapeuticEquivalenceCode{get;set;}=null!; }
public sealed class NdcDirectorySnapshotEntity:ReferenceSnapshotEntity { public string DatasetUpdateDate{get;set;}=null!; public string AggregateManifestSha256{get;set;}=null!; }
public sealed class NdcDirectoryProductEntity { public long NdcDirectoryProductId{get;set;}public long NdcDirectorySnapshotId{get;set;}public long SourceRowNumber{get;set;}public string ProductNdcRaw{get;set;}=null!;public string? NormalizedProductNdc{get;set;}public string? ApplicationNumberRaw{get;set;}public string? NormalizedApplicationNumber{get;set;}public string? GenericNameRaw{get;set;}public string? BrandNameRaw{get;set;}public string? DosageFormRaw{get;set;}public string? RouteRaw{get;set;}public string? MarketingCategoryRaw{get;set;}public string? LabelerNameRaw{get;set;}public DateOnly? MarketingStartDate{get;set;}public DateOnly? MarketingEndDate{get;set;} }
public sealed class NdcDirectoryPackageEntity { public long NdcDirectoryPackageId{get;set;}public long NdcDirectorySnapshotId{get;set;}public long SourceRowNumber{get;set;}public string PackageNdcRaw{get;set;}=null!;public string? NormalizedPackageNdc{get;set;}public string ProductNdcRaw{get;set;}=null!;public string? DescriptionRaw{get;set;} }
public sealed class RxNormSnapshotEntity:ReferenceSnapshotEntity { public string PublishedMd5{get;set;}=null!;public string ReleaseVersion{get;set;}=null!; }
public sealed class RxNormConceptEntity { public long RxNormConceptId{get;set;}public long RxNormSnapshotId{get;set;}public long SourceRowNumber{get;set;}public string RxCui{get;set;}=null!;public string TermType{get;set;}=null!;public string SourceVocabulary{get;set;}=null!;public string SourceCode{get;set;}=null!;public string NameRaw{get;set;}=null!;public string SuppressFlag{get;set;}=null!; }
public sealed class RxNormNdcAssociationEntity { public long RxNormNdcAssociationId{get;set;}public long RxNormSnapshotId{get;set;}public long SourceRowNumber{get;set;}public string RxCui{get;set;}=null!;public string NdcRaw{get;set;}=null!;public string? NormalizedNdc{get;set;}public bool IsHistorical{get;set;}public string SourceVocabulary{get;set;}=null!; }
public sealed class ProductFamilyIdentityEntity { public long ProductFamilyIdentityId{get;set;}public string IdentityHash{get;set;}=null!;public string NormalizedApplicationNumber{get;set;}=null!;public string NormalizedProductNumber{get;set;}=null!;public string NormalizedIngredientSet{get;set;}=null!;public string DosageForm{get;set;}=null!;public string Route{get;set;}=null!;public string NormalizedStrength{get;set;}=null!;public string RuleVersion{get;set;}=null!;public string Status{get;set;}=null!; }
public sealed class ProductMappingEvidenceEntity { public long ProductMappingEvidenceId{get;set;}public long ProductFamilyIdentityId{get;set;}public string MedicaidNormalizedNdc{get;set;}=null!;public string EvidenceType{get;set;}=null!;public string MappingTier{get;set;}=null!;public string ConfidenceClass{get;set;}=null!;public string RuleVersion{get;set;}=null!;public string SourceSnapshotType{get;set;}=null!;public long SourceSnapshotId{get;set;}public long SourceRowNumber{get;set;}public string SourceRecordHash{get;set;}=null!;public int CandidateCount{get;set;}public string DecisionStatus{get;set;}=null!;public string EvidenceJson{get;set;}=null!;public DateTime CreatedAtUtc{get;set;} }
