namespace PharmaAccess.Data.Entities;

public sealed class ResearchProtocolApprovalEntity{public long ResearchProtocolApprovalId{get;set;}public long ResearchProtocolId{get;set;}public string Decision{get;set;}=null!;public string Actor{get;set;}=null!;public string Reason{get;set;}=null!;public DateTime DecidedAtUtc{get;set;}}
public sealed class ResearchFreezeSourceEntity{public long ResearchFreezeSourceId{get;set;}public long ResearchDataFreezeId{get;set;}public long ResearchSourceRegistrationId{get;set;}public string SourceSha256{get;set;}=null!;public string SchemaProfileVersion{get;set;}=null!;}
public sealed class ResearchFreezeFindingEntity{public long ResearchFreezeFindingId{get;set;}public long ResearchDataFreezeId{get;set;}public string Code{get;set;}=null!;public string Severity{get;set;}=null!;public string Description{get;set;}=null!;public string Recommendation{get;set;}=null!;public DateTime CreatedAtUtc{get;set;}}
public sealed class ResearchFreezeArtifactEntity{public long ResearchFreezeArtifactId{get;set;}public long ResearchDataFreezeId{get;set;}public string ArtifactType{get;set;}=null!;public string RelativePath{get;set;}=null!;public string Sha256{get;set;}=null!;public long ByteSize{get;set;}public DateTime CreatedAtUtc{get;set;}}
public sealed class ResearchCohortDefinitionEntity{public long ResearchCohortDefinitionId{get;set;}public string VersionCode{get;set;}=null!;public string PopulationDefinition{get;set;}=null!;public string RulesJson{get;set;}=null!;public string DefinitionHash{get;set;}=null!;public DateTime CreatedAtUtc{get;set;}}
public sealed class ResearchExclusionRuleEntity{public long ResearchExclusionRuleId{get;set;}public long ResearchCohortDefinitionId{get;set;}public string RuleCode{get;set;}=null!;public string Description{get;set;}=null!;public bool IsBlocking{get;set;}public int Priority{get;set;}}
public sealed class ResearchAnalysisPlanEntity{public long ResearchAnalysisPlanId{get;set;}public long ResearchProtocolId{get;set;}public string PlanType{get;set;}=null!;public string VersionCode{get;set;}=null!;public string DefinitionJson{get;set;}=null!;public string DefinitionHash{get;set;}=null!;public bool TestPartitionLockedForSelection{get;set;}public DateTime CreatedAtUtc{get;set;}}
public sealed class ResearchDatabaseOwnershipEntity{public int ResearchDatabaseOwnershipId{get;set;}public string ProjectId{get;set;}=null!;public string RepositoryMarker{get;set;}=null!;public DateTime CreatedAtUtc{get;set;}public string CreatedBy{get;set;}=null!;}
