// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaAccess.Data;

#nullable disable

namespace PharmaAccess.Data.Migrations
{
    [DbContext(typeof(PharmaAccessDbContext))]
    [Migration("20260720192846_InitialCoreFoundation")]
    partial class InitialCoreFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaAccess.Domain.Entities.DatasetVersion", b =>
                {
                    b.Property<int>("DatasetVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatasetVersionId"));

                    b.Property<string>("CodeCommitHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FeatureVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("TotalRows")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalSourceFiles")
                        .HasColumnType("int");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("DatasetVersionId");

                    b.HasIndex("VersionCode")
                        .IsUnique();

                    b.ToTable("DatasetVersion", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IngredientCombination")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("NormalizedIngredient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Route")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RxNormId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Strength")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TherapeuticClass")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("DrugId");

                    b.HasIndex("NormalizedIngredient");

                    b.ToTable("Drug", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.DrugProduct", b =>
                {
                    b.Property<int>("DrugProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugProductId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("Labeler")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("MappingConfidence")
                        .HasColumnType("float");

                    b.Property<string>("NormalizedNdc")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("OriginalNdc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("DrugProductId");

                    b.HasIndex("DrugId");

                    b.HasIndex("SourceSystem", "OriginalNdc")
                        .IsUnique();

                    b.ToTable("DrugProduct", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.FirstGenericApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<string>("Applicant")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("ApprovalDate")
                        .HasColumnType("date");

                    b.Property<string>("ApprovalSource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimaryLaunchReference")
                        .HasColumnType("bit");

                    b.HasKey("ApprovalId");

                    b.HasIndex("DrugId", "ApprovalDate");

                    b.ToTable("FirstGenericApproval", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.JobRun", b =>
                {
                    b.Property<int>("JobRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobRunId"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("JobRunId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("DatasetVersionId");

                    b.ToTable("JobRun", "audit");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.QuarterDimension", b =>
                {
                    b.Property<int>("QuarterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuarterId"));

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateOnly>("QuarterEndDate")
                        .HasColumnType("date");

                    b.Property<int>("QuarterNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("QuarterStartDate")
                        .HasColumnType("date");

                    b.HasKey("QuarterId");

                    b.HasIndex("DisplayCode")
                        .IsUnique();

                    b.HasIndex("CalendarYear", "QuarterNumber")
                        .IsUnique();

                    b.ToTable("CalendarQuarter", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.SourceFile", b =>
                {
                    b.Property<int>("SourceFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceFileId"));

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<int>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNote")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("RejectedRowCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportingPeriod")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RowCount")
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("SourceFileId");

                    b.HasIndex("DatasetVersionId", "Sha256")
                        .IsUnique();

                    b.ToTable("SourceFile", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Division")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExclusionReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("StateId");

                    b.HasIndex("StateCode")
                        .IsUnique();

                    b.ToTable("State", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.StateDrugUtilization", b =>
                {
                    b.Property<int>("StateDrugUtilizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateDrugUtilizationId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int?>("DrugProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("bit");

                    b.Property<long>("PrescriptionCount")
                        .HasColumnType("bigint");

                    b.Property<int>("QuarterId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReimbursementAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("SourceRowCount")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("StateDrugUtilizationId");

                    b.HasIndex("DrugId");

                    b.HasIndex("DrugProductId");

                    b.HasIndex("QuarterId");

                    b.HasIndex("StateId");

                    b.HasIndex("DatasetVersionId", "DrugId", "StateId", "QuarterId")
                        .IsUnique();

                    b.ToTable("StateDrugUtilization", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.DrugProduct", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.FirstGenericApproval", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.JobRun", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.SourceFile", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.StateDrugUtilization", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.DrugProduct", null)
                        .WithMany()
                        .HasForeignKey("DrugProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("QuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.State", null)
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
