// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaAccess.Data;

#nullable disable

namespace PharmaAccess.Data.Migrations
{
    [DbContext(typeof(PharmaAccessDbContext))]
    [Migration("20260720203139_AddFeatureEngineeringFoundation")]
    partial class AddFeatureEngineeringFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaAccess.Domain.Entities.DatasetVersion", b =>
                {
                    b.Property<int>("DatasetVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatasetVersionId"));

                    b.Property<string>("CodeCommitHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FeatureVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("TotalRows")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalSourceFiles")
                        .HasColumnType("int");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("DatasetVersionId");

                    b.HasIndex("VersionCode")
                        .IsUnique();

                    b.ToTable("DatasetVersion", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IngredientCombination")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("NormalizedIngredient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Route")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RxNormId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Strength")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TherapeuticClass")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("DrugId");

                    b.HasIndex("NormalizedIngredient");

                    b.ToTable("Drug", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.DrugProduct", b =>
                {
                    b.Property<int>("DrugProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugProductId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("Labeler")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("MappingConfidence")
                        .HasColumnType("float");

                    b.Property<string>("NormalizedNdc")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("OriginalNdc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("DrugProductId");

                    b.HasIndex("DrugId");

                    b.HasIndex("SourceSystem", "OriginalNdc")
                        .IsUnique();

                    b.ToTable("DrugProduct", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.FdaFirstGenericApprovalNormalized", b =>
                {
                    b.Property<long>("StagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StagingId"));

                    b.Property<string>("Applicant")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("date");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MappingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NormalizedIngredient")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("int");

                    b.Property<long>("SourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Strength")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ValidationMessagesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("StagingId");

                    b.HasIndex("NormalizedIngredient", "ApprovalDate");

                    b.HasIndex("SourceFileId", "SourceRowNumber")
                        .IsUnique();

                    b.HasIndex("SourceFileId", "ValidationStatus");

                    b.ToTable("FdaFirstGenericApprovalNormalized", "stg");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.FdaFirstGenericApprovalRaw", b =>
                {
                    b.Property<long>("RawRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawRecordId"));

                    b.Property<string>("ActiveIngredientRaw")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ApplicantRaw")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ApplicationNumberRaw")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ApprovalDateRaw")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DosageFormRaw")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("ParsedApprovalDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductNumberRaw")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("int");

                    b.Property<long>("SourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StrengthRaw")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("RawRecordId");

                    b.HasIndex("SourceFileId", "ParseStatus");

                    b.HasIndex("SourceFileId", "SourceRowNumber")
                        .IsUnique();

                    b.ToTable("FdaFirstGenericApprovalRaw", "raw");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.FirstGenericApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<string>("Applicant")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("ApprovalDate")
                        .HasColumnType("date");

                    b.Property<string>("ApprovalSource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimaryLaunchReference")
                        .HasColumnType("bit");

                    b.HasKey("ApprovalId");

                    b.HasIndex("DrugId", "ApprovalDate");

                    b.ToTable("FirstGenericApproval", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.JobRun", b =>
                {
                    b.Property<int>("JobRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobRunId"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("JobRunId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("DatasetVersionId");

                    b.ToTable("JobRun", "audit");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.MedicaidStateDrugUtilizationNormalized", b =>
                {
                    b.Property<long>("StagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StagingId"));

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("bit");

                    b.Property<string>("MappingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NormalizedNdc")
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<string>("OriginalNdc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("PrescriptionCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuarterNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("ReimbursementAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("int");

                    b.Property<long>("SourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("ValidationMessagesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("StagingId");

                    b.HasIndex("NormalizedNdc");

                    b.HasIndex("SourceFileId", "SourceRowNumber")
                        .IsUnique();

                    b.HasIndex("SourceFileId", "ValidationStatus");

                    b.HasIndex("StateCode", "CalendarYear", "QuarterNumber");

                    b.ToTable("MedicaidStateDrugUtilizationNormalized", "stg");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.MedicaidStateDrugUtilizationRaw", b =>
                {
                    b.Property<long>("RawRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawRecordId"));

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NdcRaw")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PackageSizeRaw")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("ParsedPrescriptionCount")
                        .HasColumnType("bigint");

                    b.Property<int?>("ParsedQuarter")
                        .HasColumnType("int");

                    b.Property<decimal?>("ParsedReimbursementAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int?>("ParsedYear")
                        .HasColumnType("int");

                    b.Property<string>("PrescriptionCountRaw")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProductNameRaw")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("QuarterRaw")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReimbursementAmountRaw")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("int");

                    b.Property<long>("SourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StateCodeRaw")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UtilizationTypeRaw")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("YearRaw")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("RawRecordId");

                    b.HasIndex("SourceFileId", "ParseStatus");

                    b.HasIndex("SourceFileId", "SourceRowNumber")
                        .IsUnique();

                    b.ToTable("MedicaidStateDrugUtilizationRaw", "raw");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.QuarterDimension", b =>
                {
                    b.Property<int>("QuarterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuarterId"));

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateOnly>("QuarterEndDate")
                        .HasColumnType("date");

                    b.Property<int>("QuarterNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("QuarterStartDate")
                        .HasColumnType("date");

                    b.HasKey("QuarterId");

                    b.HasIndex("DisplayCode")
                        .IsUnique();

                    b.HasIndex("CalendarYear", "QuarterNumber")
                        .IsUnique();

                    b.ToTable("CalendarQuarter", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.SourceFile", b =>
                {
                    b.Property<int>("SourceFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceFileId"));

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<int>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNote")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("RejectedRowCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportingPeriod")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RowCount")
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("SourceFileId");

                    b.HasIndex("DatasetVersionId", "Sha256")
                        .IsUnique();

                    b.ToTable("SourceFile", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Division")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExclusionReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("StateId");

                    b.HasIndex("StateCode")
                        .IsUnique();

                    b.ToTable("State", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.StateDrugUtilization", b =>
                {
                    b.Property<int>("StateDrugUtilizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateDrugUtilizationId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int?>("DrugProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("bit");

                    b.Property<long>("PrescriptionCount")
                        .HasColumnType("bigint");

                    b.Property<int>("QuarterId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReimbursementAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("SourceRowCount")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("StateDrugUtilizationId");

                    b.HasIndex("DrugId");

                    b.HasIndex("DrugProductId");

                    b.HasIndex("QuarterId");

                    b.HasIndex("StateId");

                    b.HasIndex("DatasetVersionId", "DrugId", "StateId", "QuarterId")
                        .IsUnique();

                    b.ToTable("StateDrugUtilization", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.StateReferenceNormalized", b =>
                {
                    b.Property<long>("StagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StagingId"));

                    b.Property<string>("Division")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("int");

                    b.Property<long>("SourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ValidationMessagesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("StagingId");

                    b.HasIndex("SourceFileId", "SourceRowNumber")
                        .IsUnique();

                    b.HasIndex("SourceFileId", "StateCode")
                        .IsUnique();

                    b.HasIndex("SourceFileId", "ValidationStatus");

                    b.ToTable("StateReferenceNormalized", "stg");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.StateReferenceRaw", b =>
                {
                    b.Property<long>("RawRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawRecordId"));

                    b.Property<string>("DivisionRaw")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EligibilityRaw")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RegionRaw")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("int");

                    b.Property<long>("SourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StateCodeRaw")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StateNameRaw")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("RawRecordId");

                    b.HasIndex("SourceFileId", "ParseStatus");

                    b.HasIndex("SourceFileId", "SourceRowNumber")
                        .IsUnique();

                    b.ToTable("StateReferenceRaw", "raw");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.DrugStateQuarterFeature", b =>
                {
                    b.Property<long>("DrugStateQuarterFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DrugStateQuarterFeatureId"));

                    b.Property<int>("ApprovalQuarterId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableAsOfQuarterId")
                        .HasColumnType("int");

                    b.Property<int>("ConsecutiveActiveQuarterCount")
                        .HasColumnType("int");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("FeatureDefinitionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<int>("FeatureSetVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenericLaunchId")
                        .HasColumnType("int");

                    b.Property<int>("InitialActiveStateCount")
                        .HasColumnType("int");

                    b.Property<long>("InitialPrescriptionVolume")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFirstEntryQuarter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsObservedZero")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LabelFutureQ4AccessGap")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("LabelFutureQ4NumericDistribution")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("LabelFutureQ4WeightedDistribution")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<bool?>("LabelNextQuarterEntry")
                        .HasColumnType("bit");

                    b.Property<bool?>("LabelPersistentInequality")
                        .HasColumnType("bit");

                    b.Property<int?>("LabelQuartersUntilEntry")
                        .HasColumnType("int");

                    b.Property<long?>("Lag1PrescriptionCount")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Lag1ReimbursementAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<long?>("Lag2PrescriptionCount")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Lag2ReimbursementAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("LaunchCohort")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("MissingFeatureCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("NationalActiveStateSharePreviousQuarter")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<long?>("NationalPrescriptionCountPreviousQuarter")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("NationalPrescriptionGrowth")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("NationalReimbursementPreviousQuarter")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("NeighborStateAdoptionShare")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("NumberOfObservedQuarters")
                        .HasColumnType("int");

                    b.Property<int>("ObservationQuarterId")
                        .HasColumnType("int");

                    b.Property<long?>("ObservedPrescriptionCount")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ObservedReimbursementAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("PrescriptionGrowthRate")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("PreviousQuarterAccessGap")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("PreviousQuarterNumericDistribution")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("PreviousQuarterWeightedDistribution")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("QuarterSinceApproval")
                        .HasColumnType("int");

                    b.Property<decimal?>("RegionActiveStateShare")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("RegionHistoricalEntryRate")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("RegionPrescriptionGrowth")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("ReimbursementGrowthRate")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("SimilarStateAdoptionShare")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal>("StateDataCompleteness")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("StateHistoricalEntryRate")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<long>("StateHistoricalGenericVolume")
                        .HasColumnType("bigint");

                    b.Property<int>("StateHistoricalLaunchCount")
                        .HasColumnType("int");

                    b.Property<decimal>("StateHistoricalMarketWeight")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("StateHistoricalMedianEntryDelay")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("StateVolumePercentile")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.HasKey("DrugStateQuarterFeatureId");

                    b.HasIndex("ApprovalQuarterId");

                    b.HasIndex("AvailableAsOfQuarterId");

                    b.HasIndex("DatasetVersionId");

                    b.HasIndex("DrugId");

                    b.HasIndex("GenericLaunchId");

                    b.HasIndex("ObservationQuarterId");

                    b.HasIndex("StateId");

                    b.HasIndex("FeatureSetVersionId", "DrugId", "StateId", "ObservationQuarterId");

                    b.HasIndex("FeatureSetVersionId", "GenericLaunchId", "StateId", "ObservationQuarterId")
                        .IsUnique();

                    b.ToTable("DrugStateQuarterFeature", "feature");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.FeatureDefinition", b =>
                {
                    b.Property<int>("FeatureDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureDefinitionId"));

                    b.Property<string>("AvailableAsOfRule")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FeatureCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FeatureSetVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsLabel")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModelInput")
                        .HasColumnType("bit");

                    b.Property<string>("LeakageRisk")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("MissingValuePolicy")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("ValidMaximum")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("ValidMinimum")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.HasKey("FeatureDefinitionId");

                    b.HasIndex("FeatureSetVersionId", "FeatureName")
                        .IsUnique();

                    b.ToTable("FeatureDefinition", "feature");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.FeatureSetVersion", b =>
                {
                    b.Property<int>("FeatureSetVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureSetVersionId"));

                    b.Property<string>("CodeCommitHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("FeatureSetVersionId");

                    b.HasIndex("DatasetVersionId");

                    b.HasIndex("VersionCode")
                        .IsUnique();

                    b.ToTable("FeatureSetVersion", "feature");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.GenericLaunch", b =>
                {
                    b.Property<int>("GenericLaunchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenericLaunchId"));

                    b.Property<DateOnly>("ApprovalDate")
                        .HasColumnType("date");

                    b.Property<int>("ApprovalQuarterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("ExclusionReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsEligibleForAnalysis")
                        .HasColumnType("bit");

                    b.Property<string>("LaunchReferenceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ObservationEndQuarterId")
                        .HasColumnType("int");

                    b.Property<int>("ObservationStartQuarterId")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryApprovalId")
                        .HasColumnType("int");

                    b.HasKey("GenericLaunchId");

                    b.HasIndex("ApprovalQuarterId");

                    b.HasIndex("ObservationEndQuarterId");

                    b.HasIndex("ObservationStartQuarterId");

                    b.HasIndex("PrimaryApprovalId")
                        .IsUnique();

                    b.HasIndex("DrugId", "ApprovalQuarterId");

                    b.ToTable("GenericLaunch", "core");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.LaunchQuarterSummary", b =>
                {
                    b.Property<long>("LaunchQuarterSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LaunchQuarterSummaryId"));

                    b.Property<decimal>("AccessGap")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("ActiveStateCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("ConcentrationIndex")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("EligibleStateCount")
                        .HasColumnType("int");

                    b.Property<int>("FeatureSetVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenericLaunchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleteQuarter")
                        .HasColumnType("bit");

                    b.Property<string>("MarketWeightVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("NumericDistribution")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("ObservationQuarterId")
                        .HasColumnType("int");

                    b.Property<int>("QuarterSinceApproval")
                        .HasColumnType("int");

                    b.Property<int>("RegionalCoverageCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("TopFiveStateShare")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("TopStateShare")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<long>("TotalPrescriptionCount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalReimbursementAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("WeightedDistribution")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.HasKey("LaunchQuarterSummaryId");

                    b.HasIndex("DatasetVersionId");

                    b.HasIndex("DrugId");

                    b.HasIndex("GenericLaunchId");

                    b.HasIndex("ObservationQuarterId");

                    b.HasIndex("FeatureSetVersionId", "DrugId", "ObservationQuarterId");

                    b.HasIndex("FeatureSetVersionId", "GenericLaunchId", "ObservationQuarterId")
                        .IsUnique();

                    b.ToTable("LaunchQuarterSummary", "feature");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.RegionalHistoricalProfile", b =>
                {
                    b.Property<long>("RegionalHistoricalProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RegionalHistoricalProfileId"));

                    b.Property<decimal>("ActiveStateShare")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("AvailableAsOfQuarterId")
                        .HasColumnType("int");

                    b.Property<int>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("EligibleStateCount")
                        .HasColumnType("int");

                    b.Property<int>("FeatureSetVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HistoricalEntryRate")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("PrescriptionGrowth")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("RegionalHistoricalProfileId");

                    b.HasIndex("AvailableAsOfQuarterId");

                    b.HasIndex("DatasetVersionId");

                    b.HasIndex("FeatureSetVersionId", "Region", "AvailableAsOfQuarterId")
                        .IsUnique();

                    b.ToTable("RegionalHistoricalProfile", "feature");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.StateHistoricalProfile", b =>
                {
                    b.Property<long>("StateHistoricalProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StateHistoricalProfileId"));

                    b.Property<int>("AvailableAsOfQuarterId")
                        .HasColumnType("int");

                    b.Property<decimal>("DataCompleteness")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("DatasetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureSetVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HistoricalEntryRate")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<long>("HistoricalGenericVolume")
                        .HasColumnType("bigint");

                    b.Property<int>("HistoricalLaunchCount")
                        .HasColumnType("int");

                    b.Property<decimal>("HistoricalMarketWeight")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal?>("HistoricalMedianEntryDelay")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VolumePercentile")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.HasKey("StateHistoricalProfileId");

                    b.HasIndex("AvailableAsOfQuarterId");

                    b.HasIndex("DatasetVersionId");

                    b.HasIndex("StateId");

                    b.HasIndex("FeatureSetVersionId", "StateId", "AvailableAsOfQuarterId")
                        .IsUnique();

                    b.ToTable("StateHistoricalProfile", "feature");
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.DrugProduct", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.FdaFirstGenericApprovalNormalized", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.SourceFile", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.FdaFirstGenericApprovalRaw", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.SourceFile", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.FirstGenericApproval", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.JobRun", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.MedicaidStateDrugUtilizationNormalized", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.SourceFile", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.MedicaidStateDrugUtilizationRaw", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.SourceFile", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.SourceFile", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.StateDrugUtilization", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.DrugProduct", null)
                        .WithMany()
                        .HasForeignKey("DrugProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("QuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.State", null)
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.StateReferenceNormalized", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.SourceFile", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Entities.StateReferenceRaw", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.SourceFile", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.DrugStateQuarterFeature", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("ApprovalQuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("AvailableAsOfQuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Features.FeatureSetVersion", null)
                        .WithMany()
                        .HasForeignKey("FeatureSetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Features.GenericLaunch", null)
                        .WithMany()
                        .HasForeignKey("GenericLaunchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("ObservationQuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.State", null)
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.FeatureDefinition", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Features.FeatureSetVersion", null)
                        .WithMany()
                        .HasForeignKey("FeatureSetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.FeatureSetVersion", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.GenericLaunch", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("ApprovalQuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("ObservationEndQuarterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("ObservationStartQuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.FirstGenericApproval", null)
                        .WithMany()
                        .HasForeignKey("PrimaryApprovalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.LaunchQuarterSummary", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Features.FeatureSetVersion", null)
                        .WithMany()
                        .HasForeignKey("FeatureSetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Features.GenericLaunch", null)
                        .WithMany()
                        .HasForeignKey("GenericLaunchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("ObservationQuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.RegionalHistoricalProfile", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("AvailableAsOfQuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Features.FeatureSetVersion", null)
                        .WithMany()
                        .HasForeignKey("FeatureSetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaAccess.Domain.Features.StateHistoricalProfile", b =>
                {
                    b.HasOne("PharmaAccess.Domain.Entities.QuarterDimension", null)
                        .WithMany()
                        .HasForeignKey("AvailableAsOfQuarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.DatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Features.FeatureSetVersion", null)
                        .WithMany()
                        .HasForeignKey("FeatureSetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaAccess.Domain.Entities.State", null)
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
