using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace PharmaAccess.Domain.Research;

public enum ResearchProtocolStatus { Draft, UnderReview, Approved, Rejected, Superseded, Archived }
public enum ResearchFreezeStatus { ProtocolDraft, SourceFilesRegistered, SourceFilesValidated, DatasetBuilt, DatasetValidated, CohortDefined, FeatureSetValidated, PredictiveSplitFrozen, CausalProtocolFrozen, ValidationBundleGenerated, ReadyForAnalysis, Rejected, Archived }
public enum ResearchSourceType { FdaFirstGenericApproval, CmsMedicaidStateDrugUtilization, StateTerritoryReference, GeographicRegionAdjacency, RxNormDrugNormalization, ManuallyCuratedMapping }
public enum ResearchSourceValidationStatus { Registered, Validated, Warning, Failed }
public enum ResearchFindingSeverity { Warning, Blocking }

public sealed class ResearchProtocol
{
    private ResearchProtocol() { }
    public ResearchProtocol(string code, string version, string title, string researchQuestion, string primaryPredictionTask,
        string primaryCausalQuestion, string primaryPredictiveMetric, string secondaryPredictiveMetrics,
        string primaryCausalEstimand, string primaryEffectScale, string primaryEstimator, string secondaryEstimators,
        string populationDefinition, string observationWindow, string inclusionRulesJson, string exclusionRulesJson,
        string stateEligibilityPolicyVersion, string stateEntryPolicyVersion, string marketWeightPolicyVersion,
        int featureSetVersionId, long predictiveSplitDefinitionId, long dagVersionId, long adjustmentSetVersionId,
        long treatmentDefinitionVersionId, long outcomeDefinitionVersionId, string missingDataPolicy, string censoringPolicy,
        string multiplicityPolicy, string sensitivityAnalysisPlan, string subgroupAnalysisPlan, string stoppingRules,
        DateTime createdAtUtc)
    {
        ProtocolCode=Required(code,64);ProtocolVersion=Required(version,32);Title=Required(title,256);ResearchQuestion=Required(researchQuestion,2000);
        PrimaryPredictionTask=Required(primaryPredictionTask,128);PrimaryCausalQuestion=Required(primaryCausalQuestion,2000);PrimaryPredictiveMetric=Required(primaryPredictiveMetric,64);SecondaryPredictiveMetrics=Required(secondaryPredictiveMetrics,1000);PrimaryCausalEstimand=Required(primaryCausalEstimand,32);PrimaryEffectScale=Required(primaryEffectScale,32);PrimaryEstimator=Required(primaryEstimator,128);SecondaryEstimators=Required(secondaryEstimators,1000);PopulationDefinition=Required(populationDefinition,2000);ObservationWindow=Required(observationWindow,256);InclusionRulesJson=Required(inclusionRulesJson,8000);ExclusionRulesJson=Required(exclusionRulesJson,8000);StateEligibilityPolicyVersion=Required(stateEligibilityPolicyVersion,64);StateEntryPolicyVersion=Required(stateEntryPolicyVersion,64);MarketWeightPolicyVersion=Required(marketWeightPolicyVersion,64);FeatureSetVersionId=(int)Positive(featureSetVersionId);PredictiveSplitDefinitionId=Positive(predictiveSplitDefinitionId);DagVersionId=Positive(dagVersionId);AdjustmentSetVersionId=Positive(adjustmentSetVersionId);TreatmentDefinitionVersionId=Positive(treatmentDefinitionVersionId);OutcomeDefinitionVersionId=Positive(outcomeDefinitionVersionId);MissingDataPolicy=Required(missingDataPolicy,256);CensoringPolicy=Required(censoringPolicy,1000);MultiplicityPolicy=Required(multiplicityPolicy,1000);SensitivityAnalysisPlan=Required(sensitivityAnalysisPlan,4000);SubgroupAnalysisPlan=Required(subgroupAnalysisPlan,4000);StoppingRules=Required(stoppingRules,2000);CreatedAtUtc=Utc(createdAtUtc);Status=ResearchProtocolStatus.Draft;DefinitionHash=Hash(DefinitionPayload());
    }
    public long ResearchProtocolId{get;private set;} public string ProtocolCode{get;private set;}=null!;public string ProtocolVersion{get;private set;}=null!;public string Title{get;private set;}=null!;public string ResearchQuestion{get;private set;}=null!;public string PrimaryPredictionTask{get;private set;}=null!;public string PrimaryCausalQuestion{get;private set;}=null!;public string PrimaryPredictiveMetric{get;private set;}=null!;public string SecondaryPredictiveMetrics{get;private set;}=null!;public string PrimaryCausalEstimand{get;private set;}=null!;public string PrimaryEffectScale{get;private set;}=null!;public string PrimaryEstimator{get;private set;}=null!;public string SecondaryEstimators{get;private set;}=null!;public string PopulationDefinition{get;private set;}=null!;public string ObservationWindow{get;private set;}=null!;public string InclusionRulesJson{get;private set;}=null!;public string ExclusionRulesJson{get;private set;}=null!;public string StateEligibilityPolicyVersion{get;private set;}=null!;public string StateEntryPolicyVersion{get;private set;}=null!;public string MarketWeightPolicyVersion{get;private set;}=null!;public int FeatureSetVersionId{get;private set;}public long PredictiveSplitDefinitionId{get;private set;}public long DagVersionId{get;private set;}public long AdjustmentSetVersionId{get;private set;}public long TreatmentDefinitionVersionId{get;private set;}public long OutcomeDefinitionVersionId{get;private set;}public string MissingDataPolicy{get;private set;}=null!;public string CensoringPolicy{get;private set;}=null!;public string MultiplicityPolicy{get;private set;}=null!;public string SensitivityAnalysisPlan{get;private set;}=null!;public string SubgroupAnalysisPlan{get;private set;}=null!;public string StoppingRules{get;private set;}=null!;public DateTime CreatedAtUtc{get;private set;}public DateTime? ApprovedAtUtc{get;private set;}public string? ApprovedBy{get;private set;}public string? ApprovalNotes{get;private set;}public ResearchProtocolStatus Status{get;private set;}public string DefinitionHash{get;private set;}=null!;
    public void SubmitForReview(){Require(ResearchProtocolStatus.Draft);Status=ResearchProtocolStatus.UnderReview;}
    public void Approve(string actor,DateTime atUtc,string reason){Require(ResearchProtocolStatus.UnderReview);ApprovedBy=Required(actor,256);ApprovalNotes=Required(reason,2000);ApprovedAtUtc=Utc(atUtc);Status=ResearchProtocolStatus.Approved;}
    public void Reject(string actor,string reason){if(Status is not (ResearchProtocolStatus.Draft or ResearchProtocolStatus.UnderReview))throw new InvalidOperationException("Only draft or under-review protocols may be rejected.");ApprovedBy=Required(actor,256);ApprovalNotes=Required(reason,2000);Status=ResearchProtocolStatus.Rejected;}
    public void Supersede(){Require(ResearchProtocolStatus.Approved);Status=ResearchProtocolStatus.Superseded;} public void Archive(){if(Status is not (ResearchProtocolStatus.Rejected or ResearchProtocolStatus.Superseded))throw new InvalidOperationException("Only rejected or superseded protocols may be archived.");Status=ResearchProtocolStatus.Archived;}
    private object DefinitionPayload()=>new{ProtocolCode,ProtocolVersion,Title,ResearchQuestion,PrimaryPredictionTask,PrimaryCausalQuestion,PrimaryPredictiveMetric,SecondaryPredictiveMetrics,PrimaryCausalEstimand,PrimaryEffectScale,PrimaryEstimator,SecondaryEstimators,PopulationDefinition,ObservationWindow,InclusionRulesJson,ExclusionRulesJson,StateEligibilityPolicyVersion,StateEntryPolicyVersion,MarketWeightPolicyVersion,FeatureSetVersionId,PredictiveSplitDefinitionId,DagVersionId,AdjustmentSetVersionId,TreatmentDefinitionVersionId,OutcomeDefinitionVersionId,MissingDataPolicy,CensoringPolicy,MultiplicityPolicy,SensitivityAnalysisPlan,SubgroupAnalysisPlan,StoppingRules};
    private void Require(ResearchProtocolStatus expected){if(Status!=expected)throw new InvalidOperationException($"Transition requires {expected}; current status is {Status}.");}
    internal static string Required(string value,int max){if(string.IsNullOrWhiteSpace(value)||value.Trim().Length>max)throw new ArgumentException("Required research value is invalid.");return value.Trim();}internal static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.");internal static long Positive(long value)=>value>0?value:throw new ArgumentOutOfRangeException(nameof(value));internal static string Hash(object value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(value))));
}

public sealed class ResearchDataFreeze
{
    private ResearchDataFreeze() { }
    public ResearchDataFreeze(string code,string version,long protocolId,int datasetVersionId,int featureSetVersionId,string sourceManifestHash,string datasetHash,string cohortHash,string featureSchemaHash,string predictiveSplitHash,string causalProtocolHash,string pythonEnvironmentHash,string dotNetEnvironmentHash,string gitCommitHash,bool isSynthetic,DateTime createdAtUtc,string? notes=null){FreezeCode=ResearchProtocol.Required(code,64);FreezeVersion=ResearchProtocol.Required(version,32);ResearchProtocolId=ResearchProtocol.Positive(protocolId);DatasetVersionId=(int)ResearchProtocol.Positive(datasetVersionId);FeatureSetVersionId=(int)ResearchProtocol.Positive(featureSetVersionId);SourceManifestHash=Sha(sourceManifestHash);DatasetHash=Sha(datasetHash);CohortHash=Sha(cohortHash);FeatureSchemaHash=Sha(featureSchemaHash);PredictiveSplitHash=Sha(predictiveSplitHash);CausalProtocolHash=Sha(causalProtocolHash);PythonEnvironmentHash=Sha(pythonEnvironmentHash);DotNetEnvironmentHash=Sha(dotNetEnvironmentHash);GitCommitHash=ResearchProtocol.Required(gitCommitHash,64);IsSynthetic=isSynthetic;CreatedAtUtc=ResearchProtocol.Utc(createdAtUtc);Notes=notes;Status=ResearchFreezeStatus.ProtocolDraft;}
    public long ResearchDataFreezeId{get;private set;}public string FreezeCode{get;private set;}=null!;public string FreezeVersion{get;private set;}=null!;public long ResearchProtocolId{get;private set;}public int DatasetVersionId{get;private set;}public int FeatureSetVersionId{get;private set;}public string SourceManifestHash{get;private set;}=null!;public string DatasetHash{get;private set;}=null!;public string CohortHash{get;private set;}=null!;public string FeatureSchemaHash{get;private set;}=null!;public string PredictiveSplitHash{get;private set;}=null!;public string CausalProtocolHash{get;private set;}=null!;public string PythonEnvironmentHash{get;private set;}=null!;public string DotNetEnvironmentHash{get;private set;}=null!;public string GitCommitHash{get;private set;}=null!;public bool IsSynthetic{get;private set;}public ResearchFreezeStatus Status{get;private set;}public int BlockingFindingCount{get;private set;}public int WarningCount{get;private set;}public DateTime CreatedAtUtc{get;private set;}public DateTime? FrozenAtUtc{get;private set;}public string? FrozenBy{get;private set;}public string? Notes{get;private set;}
    public void Advance(ResearchFreezeStatus next){if(Status is ResearchFreezeStatus.ReadyForAnalysis or ResearchFreezeStatus.Rejected or ResearchFreezeStatus.Archived)throw new InvalidOperationException("Terminal freezes are immutable.");if((int)next!=(int)Status+1||next>ResearchFreezeStatus.ValidationBundleGenerated)throw new InvalidOperationException("Research freeze transitions are sequential.");Status=next;}
    public void RecordFindings(int blocking,int warnings){if(Status is ResearchFreezeStatus.ReadyForAnalysis or ResearchFreezeStatus.Archived)throw new InvalidOperationException("Approved freezes are immutable.");if(blocking<0||warnings<0)throw new ArgumentOutOfRangeException(nameof(blocking));BlockingFindingCount=blocking;WarningCount=warnings;}
    public void Approve(ResearchProtocol protocol,string actor,DateTime atUtc,string reason,bool markAsReal=false){if(Status!=ResearchFreezeStatus.ValidationBundleGenerated)throw new InvalidOperationException("Validation bundle must be generated before approval.");if(protocol.Status!=ResearchProtocolStatus.Approved||BlockingFindingCount>0)throw new InvalidOperationException("Approved protocol and zero blocking findings are required.");if(IsSynthetic&&markAsReal)throw new InvalidOperationException("Synthetic freezes cannot become real research freezes.");FrozenBy=ResearchProtocol.Required(actor,256);FrozenAtUtc=ResearchProtocol.Utc(atUtc);Notes=ResearchProtocol.Required(reason,2000);Status=ResearchFreezeStatus.ReadyForAnalysis;}
    public void Reject(string actor,string reason){if(Status is ResearchFreezeStatus.ReadyForAnalysis or ResearchFreezeStatus.Archived)throw new InvalidOperationException("Approved or archived freezes cannot be rejected.");FrozenBy=ResearchProtocol.Required(actor,256);Notes=ResearchProtocol.Required(reason,2000);Status=ResearchFreezeStatus.Rejected;}public void Archive(){if(Status is not (ResearchFreezeStatus.ReadyForAnalysis or ResearchFreezeStatus.Rejected))throw new InvalidOperationException("Only terminal freezes may be archived.");Status=ResearchFreezeStatus.Archived;}
    public string ReproducibilityHash()=>ResearchProtocol.Hash(new{FreezeCode,FreezeVersion,ResearchProtocolId,DatasetVersionId,FeatureSetVersionId,SourceManifestHash,DatasetHash,CohortHash,FeatureSchemaHash,PredictiveSplitHash,CausalProtocolHash,PythonEnvironmentHash,DotNetEnvironmentHash,GitCommitHash,IsSynthetic});
    private static string Sha(string value){value=ResearchProtocol.Required(value,64).ToUpperInvariant();if(value.Length!=64||value.Any(x=>!Uri.IsHexDigit(x)))throw new ArgumentException("SHA-256 is invalid.");return value;}
}

public sealed class ResearchSourceRegistration
{
    private ResearchSourceRegistration() { }
    public ResearchSourceRegistration(string sourceCode,ResearchSourceType sourceType,string authority,string datasetName,string description,string officialReference,DateTime accessedAtUtc,DateOnly? coverageStart,DateOnly? coverageEnd,string licenseNotes,string schemaVersion,string localFileName,string registeredPath,string sha256,long byteSize,string encoding,string delimiter,bool synthetic,string registeredBy,DateTime registeredAtUtc){SourceCode=ResearchProtocol.Required(sourceCode,64);SourceType=sourceType;SourceAuthority=ResearchProtocol.Required(authority,256);DatasetName=ResearchProtocol.Required(datasetName,256);Description=ResearchProtocol.Required(description,2000);OfficialSourceReference=ResearchProtocol.Required(officialReference,2048);AccessedAtUtc=ResearchProtocol.Utc(accessedAtUtc);CoverageStart=coverageStart;CoverageEnd=coverageEnd;LicenseOrUsageNotes=ResearchProtocol.Required(licenseNotes,2000);ExpectedSchemaVersion=ResearchProtocol.Required(schemaVersion,64);LocalFileName=ResearchProtocol.Required(localFileName,512);RegisteredPath=ResearchProtocol.Required(registeredPath,1024);Sha256=sha256.ToUpperInvariant();if(Sha256.Length!=64||Sha256.Any(x=>!Uri.IsHexDigit(x)))throw new ArgumentException("SHA-256 is invalid.");ByteSize=byteSize>=0?byteSize:throw new ArgumentOutOfRangeException(nameof(byteSize));Encoding=ResearchProtocol.Required(encoding,64);Delimiter=ResearchProtocol.Required(delimiter,8);IsSynthetic=synthetic;RegisteredBy=ResearchProtocol.Required(registeredBy,256);RegisteredAtUtc=ResearchProtocol.Utc(registeredAtUtc);ValidationStatus=ResearchSourceValidationStatus.Registered;ValidationMessages="[]";}
    public long SourceRegistryId{get;private set;}public string SourceCode{get;private set;}=null!;public ResearchSourceType SourceType{get;private set;}public string SourceAuthority{get;private set;}=null!;public string DatasetName{get;private set;}=null!;public string Description{get;private set;}=null!;public string OfficialSourceReference{get;private set;}=null!;public DateTime AccessedAtUtc{get;private set;}public DateOnly? CoverageStart{get;private set;}public DateOnly? CoverageEnd{get;private set;}public string LicenseOrUsageNotes{get;private set;}=null!;public string ExpectedSchemaVersion{get;private set;}=null!;public string LocalFileName{get;private set;}=null!;public string RegisteredPath{get;private set;}=null!;public string Sha256{get;private set;}=null!;public long ByteSize{get;private set;}public long? RowCount{get;private set;}public string Encoding{get;private set;}=null!;public string Delimiter{get;private set;}=null!;public bool IsSynthetic{get;private set;}public ResearchSourceValidationStatus ValidationStatus{get;private set;}public string ValidationMessages{get;private set;}=null!;public string RegisteredBy{get;private set;}=null!;public DateTime RegisteredAtUtc{get;private set;}
    public void MarkValidated(long rows,IReadOnlyList<string> warnings){if(ValidationStatus!=ResearchSourceValidationStatus.Registered)throw new InvalidOperationException("Source registration is immutable after validation.");RowCount=rows>=0?rows:throw new ArgumentOutOfRangeException(nameof(rows));ValidationMessages=JsonSerializer.Serialize(warnings);ValidationStatus=warnings.Count==0?ResearchSourceValidationStatus.Validated:ResearchSourceValidationStatus.Warning;}
}
