[CmdletBinding(SupportsShouldProcess,ConfirmImpact='High')]
param(
 [string]$Server='.',[string]$Database='PharmaAccessCausalIntelligence_ResearchDev',[string]$DatasetVersion='real-2021-2025-v1',
 [Parameter(Mandatory)][string]$Actor,[Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9_-]{8,128}$')][string]$CorrelationId,
 [switch]$DotNetTestsPassed,[switch]$PipCheckPassed,[switch]$PythonTestsPassed,[string]$ArtifactRoot='.\artifacts\final')
$ErrorActionPreference='Stop'
function Assert-Native([string]$operation){if($LASTEXITCODE-ne0){throw "$operation failed with exit code $LASTEXITCODE."}}
function FileHash([string]$path){$s=[IO.File]::OpenRead([IO.Path]::GetFullPath($path));$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash($s))).Replace('-','')}finally{$h.Dispose();$s.Dispose()}}
function Query([string]$sql){$saved=$global:WhatIfPreference;$global:WhatIfPreference=$false;try{$rows=@(sqlcmd -S $Server -E -d $Database -C -b -W -h-1 -Q "SET NOCOUNT ON;$sql");Assert-Native 'Database preflight';return @($rows|ForEach-Object{($_.Trim()-replace '\s*\|\s*','|')}|Where-Object{$_})}finally{$global:WhatIfPreference=$saved}}
if($Server-cne'.'-or$Database-cne'PharmaAccessCausalIntelligence_ResearchDev'-or$DatasetVersion-cne'real-2021-2025-v1'){throw 'Exact server, database, and DatasetVersion are required.'}
if($env:PHARMAACCESS_ALLOW_RESEARCH_DB_WRITE-cne'YES'){throw 'PHARMAACCESS_ALLOW_RESEARCH_DB_WRITE=YES is required.'}
if(-not($DotNetTestsPassed-and$PipCheckPassed-and$PythonTestsPassed)){throw 'Explicit successful .NET, pip, and Python test gates are required.'}
$root=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path;$art=[IO.Path]::GetFullPath((Join-Path $root $ArtifactRoot));if(-not$art.StartsWith($root+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'ArtifactRoot must be repository-relative.'};[IO.Directory]::CreateDirectory($art)|Out-Null
$owner=@(Query 'SELECT CONCAT(ProjectId,''|'',RepositoryMarker) FROM research.ResearchDatabaseOwnership;');if($owner[-1]-cne'PharmaAccessCausalIntelligence|pharma-access-causal-intelligence'){throw 'Database ownership marker mismatch.'}
$state=@(Query "SELECT CONCAT(Status,'|',ValidationStatus,'|',TotalRows,'|',COALESCE(CONVERT(varchar(33),FinalizedAtUtc,126),'NULL')) FROM core.DatasetVersion WHERE VersionCode='$DatasetVersion';");if($state[-1]-cne'Validating|InProgress|174471|NULL'){throw "Dataset lifecycle preflight failed: $($state[-1])"}
$approved=@(Query "SELECT COUNT(*) FROM research.ResearchProtocol WHERE ProtocolCode='approval-to-access-real' AND ProtocolVersion IN('1.0','1.1','1.2') AND Status='Approved';");if([int]$approved[-1]-ne3){throw 'All real research protocols must be approved.'}
$recon=@(Query "SELECT CONCAT((SELECT COUNT(*) FROM research.AndaLaunch WHERE EligibilityCategory IN('A','B')),'|',(SELECT COUNT(*) FROM research.AndaStateQuarterPanel),'|',(SELECT COUNT(*) FROM research.AndaLaunch WHERE EligibilityCategory IN('A','B') AND Partition='Training'),'|',(SELECT COUNT(*) FROM research.AndaLaunch WHERE EligibilityCategory IN('A','B') AND Partition='Validation'),'|',(SELECT COUNT(*) FROM research.AndaLaunch WHERE EligibilityCategory IN('A','B') AND Partition='LockedTest'),'|',(SELECT COUNT(*) FROM research.AndaLaunchMappingEvidence),'|',(SELECT COUNT(*) FROM research.AndaLaunchMappingEvidence m WHERE EXISTS(SELECT 1 FROM research.AndaLaunchMappingEvidence x WHERE x.MedicaidNormalizedNdc=m.MedicaidNormalizedNdc AND x.AndaLaunchId<>m.AndaLaunchId)),'|',(SELECT COUNT(*) FROM research.AndaStateQuarterPanel WHERE IsSuppressed=1 AND (PrescriptionCount IS NOT NULL OR ReimbursementAmount IS NOT NULL)));");if($recon[-1]-cne'261|174471|147|66|48|1237|0|0'){throw "Database reconciliation failed: $($recon[-1])"}
$predictive=Get-Content (Join-Path $art 'final-predictive-metrics.json') -Raw|ConvertFrom-Json;$causal=Get-Content (Join-Path $art 'final-causal-estimates.json') -Raw|ConvertFrom-Json;$pythonPath=Join-Path $art 'final-python-causal-validation.json';if(-not(Test-Path $pythonPath)){throw 'Python validation artifact is missing.'};$python=Get-Content $pythonPath -Raw|ConvertFrom-Json
$test=$predictive.Selected.TestMetrics;if([math]::Abs($test.RocAuc-.822051629878897)-gt1e-12-or[math]::Abs($test.PrAuc-.11116877746872178)-gt1e-12-or$predictive.trainLaunches-ne147-or$predictive.validationLaunches-ne66-or$predictive.testLaunches-ne48-or$predictive.SelectedThreshold-ne$predictive.Selected.ValidationMetrics.Threshold){throw 'Predictive artifact or locked-test selection gate failed.'}
$aipw=$causal.Estimates|Where-Object Estimator -eq 3;if([math]::Abs($aipw.Estimate-.001566580700392556)-gt1e-12-or[math]::Abs($python.estimate-(-.013823338128640627))-gt1e-12-or[math]::Abs($python.dotnetEstimate-$aipw.Estimate)-gt1e-12){throw 'Causal/Python artifact reconciliation failed.'}
$requiredExisting=@('final-predictive-results.md','final-predictive-metrics.json','final-predictive-test-predictions.csv','final-calibration-data.csv','final-causal-results.md','final-causal-estimates.json','final-balance-diagnostics.csv','final-overlap-diagnostics.csv','final-sensitivity-results.csv');foreach($f in $requiredExisting){if(-not(Test-Path (Join-Path $art $f))){throw "Required final artifact is missing: $f"}}
$requestedWhatIf=$WhatIfPreference;$WhatIfPreference=$false
$at=[DateTime]::UtcNow;$exact='The primary AIPW estimate was a 0.157-percentage-point ATT risk difference. The 95% confidence interval ranged from -0.377 to 0.928 percentage points and included zero, so the analysis did not provide clear evidence of a nonzero causal effect under the stated observational assumptions.'
$decision='I, Tanvir Mahmud Khan, accept that the governed .NET AIPW estimate is primary; the Python grouped cross-fitted estimate is an independent robustness analysis. The difference between 0.00157 and -0.01382 is material and prominently disclosed. Both estimates are uncertain, the governed confidence interval includes zero, and no claim that neighbor exposure causes adoption is made. Different nuisance-model fitting procedures explain the discrepancy. This methodological limitation is not a database-integrity or reproducibility failure and is not a finalization blocker.'
Copy-Item -LiteralPath $pythonPath -Destination (Join-Path $art 'final-python-validation-report.json') -Force
@("Stage,Launches","Training,147","Validation,66","LockedTest,48","Total,261")|Set-Content (Join-Path $art 'final-cohort-flow.csv') -Encoding utf8
@("Metric,Value","PanelRows,174471","EligibleLaunches,261","MappedNdc,1237","SuppressedNonNullValues,0")|Set-Content (Join-Path $art 'final-state-quarter-profile.csv') -Encoding utf8
@("Partition,Launches,SelectionUse","Training,147,Model fitting","Validation,66,Model and threshold selection","LockedTest,48,One-time final evaluation")|Set-Content (Join-Path $art 'final-temporal-split-profile.csv') -Encoding utf8
"# Final causal results`n`nGoverned .NET AIPW ATT risk difference: **0.00157** (95% ANDA-clustered bootstrap CI **-0.00377 to 0.00928**). Python grouped cross-fitted AIPW: **-0.01382**. The material discrepancy reflects different nuisance-model fitting procedures; .NET is the protocol-defined primary estimate and Python is a robustness analysis.`n`n$exact`n`nThese observational results do not establish that neighbor exposure causes adoption.`n"|Set-Content (Join-Path $art 'final-causal-results.md') -Encoding utf8
"# Methodology`n`nThe frozen ANDA-level cohort contains 261 launches and 174,471 state-quarter rows. Predictive fitting used grouped chronological training/validation partitions and accessed the locked test partition only for final evaluation. The primary observational estimand is the ATT risk difference estimated by governed .NET AIPW; grouped cross-fitted Python AIPW is an independent robustness analysis.`n"|Set-Content (Join-Path $art 'final-methodology.md') -Encoding utf8
"# Limitations`n`nGoverned .NET AIPW: **0.00157**; 95% CI: **-0.00377 to 0.00928**. Python grouped cross-fitted AIPW: **-0.01382**. The estimators use different nuisance-model fitting procedures, producing a material discrepancy. $exact No claim is made that neighbor exposure causes adoption; observational identification assumptions, residual confounding, interference, overlap and measurement limitations remain.`n"|Set-Content (Join-Path $art 'final-limitations.md') -Encoding utf8
"# Reproducibility guide`n`nDataset: real-2021-2025-v1. Correlation ID: $CorrelationId. Run solution restore/build/test and pinned Python pip check/pytest, verify the final artifact manifest, then inspect the immutable research freeze record. Raw import, panel construction, model training and mapping are not rerun during closeout.`n"|Set-Content (Join-Path $art 'final-reproducibility-guide.md') -Encoding utf8
"# Executive summary`n`nLocked-test ROC AUC was 0.8221 and PR AUC was 0.1112. Governed .NET AIPW was 0.00157 with 95% CI -0.00377 to 0.00928; Python grouped cross-fitted AIPW was -0.01382. The material robustness discrepancy is disclosed and the observational analysis provides no clear evidence of a nonzero effect.`n"|Set-Content (Join-Path $art 'final-executive-summary.md') -Encoding utf8
$report=[ordered]@{datasetVersion=$DatasetVersion;preview=$WhatIfPreference;finalizedAtUtc=$at.ToString('O');actor=$Actor;correlationId=$CorrelationId;status='Finalized';validationStatus='Passed';totalRows=174471;humanDecision=$decision;governedDotNetAipw=$aipw.Estimate;confidenceInterval=@($aipw.ConfidenceLower,$aipw.ConfidenceUpper);pythonCrossFittedAipw=$python.estimate}
$report|ConvertTo-Json -Depth 8|Set-Content (Join-Path $art 'final-dataset-freeze-report.json') -Encoding utf8
"# Final dataset freeze report`n`nActor: $Actor  `nCorrelation ID: $CorrelationId  `nFinalization UTC: $($at.ToString('O'))`n`n$decision`n`n$exact`n"|Set-Content (Join-Path $art 'final-dataset-freeze-report.md') -Encoding utf8
$manifestFiles=@('final-dataset-freeze-report.md','final-dataset-freeze-report.json','final-cohort-flow.csv','final-state-quarter-profile.csv','final-temporal-split-profile.csv','final-predictive-results.md','final-predictive-metrics.json','final-predictive-test-predictions.csv','final-calibration-data.csv','final-causal-results.md','final-causal-estimates.json','final-balance-diagnostics.csv','final-overlap-diagnostics.csv','final-sensitivity-results.csv','final-python-validation-report.json','final-methodology.md','final-limitations.md','final-reproducibility-guide.md','final-executive-summary.md')
$manifest=@($manifestFiles|ForEach-Object{$f=Get-Item (Join-Path $art $_);[ordered]@{artifactType=($_-replace '[^A-Za-z0-9_-]','-');relativePath="artifacts/final/$_";sha256=FileHash $f.FullName;byteSize=$f.Length}});$manifest|ConvertTo-Json -Depth 5|Set-Content (Join-Path $art 'final-artifact-manifest.json') -Encoding utf8
$manifestFile=Get-Item (Join-Path $art 'final-artifact-manifest.json');$artifacts=@($manifest+[ordered]@{artifactType='final-artifact-manifest';relativePath='artifacts/final/final-artifact-manifest.json';sha256=FileHash $manifestFile.FullName;byteSize=$manifestFile.Length})
$protocolHash=@(Query "SELECT DefinitionHash FROM research.ResearchProtocol WHERE ProtocolCode='approval-to-access-real' AND ProtocolVersion='1.2' AND Status='Approved';")[-1];$sourceHash=FileHash (Join-Path $root 'data\private\mappings\research-sources.private.json');$featureHash=FileHash (Join-Path $root 'docs\data\FEATURE_DICTIONARY.md');$pythonEnv=FileHash (Join-Path $root 'python\requirements.lock');$dotnetEnv=FileHash (Join-Path $root 'Directory.Packages.props');$git=(&git rev-parse HEAD).Trim();Assert-Native 'Git revision lookup'
$command=[ordered]@{datasetVersion=$DatasetVersion;actor=$Actor;correlationId=$CorrelationId;finalizedAtUtc=$at.ToString('O');gitCommitHash=$git;sourceManifestHash=$sourceHash;panelHash=$predictive.DatasetHash;cohortHash=FileHash (Join-Path $art 'final-cohort-flow.csv');featureSchemaHash=$featureHash;splitHash=$predictive.SplitManifestHash;causalProtocolHash=$protocolHash;pythonEnvironmentHash=$pythonEnv;dotNetEnvironmentHash=$dotnetEnv;humanDecision=$decision;artifacts=$artifacts};$commandPath=Join-Path $art '.finalization-command.json';$command|ConvertTo-Json -Depth 8|Set-Content $commandPath -Encoding utf8
$WhatIfPreference=$requestedWhatIf
Write-Host "Preview gates passed: dataset=$DatasetVersion rows=174471 splits=147/66/48 artifacts=$($artifacts.Count) discrepancyAccepted=True"
if(-not$PSCmdlet.ShouldProcess("$Server/$Database/$DatasetVersion",'Atomically finalize dataset and persist immutable freeze audit')){$WhatIfPreference=$false;Remove-Item $commandPath -Force;Write-Host 'WhatIf completed; no database write occurred.';return}
$env:ConnectionStrings__PharmaAccess="Server=$Server;Database=$Database;Trusted_Connection=True;TrustServerCertificate=True";try{dotnet run --no-build --no-restore --project (Join-Path $root 'src\PharmaAccess.Worker\PharmaAccess.Worker.csproj') -- finalize-research-dataset $commandPath;Assert-Native 'Confirmed dataset finalization'}finally{Remove-Item Env:ConnectionStrings__PharmaAccess -ErrorAction SilentlyContinue;Remove-Item $commandPath -Force -ErrorAction SilentlyContinue}
