[CmdletBinding(SupportsShouldProcess,ConfirmImpact='High')]
param([string]$PlanPath='.\config\research-reference-source-plan.json',[string]$DestinationRoot='.\data\private\reference',[switch]$ResumeIncompleteSnapshot)
$ErrorActionPreference='Stop'; trap { [Console]::Error.WriteLine($_.Exception.Message); exit 1 }
function Assert-Native([string]$name){if($LASTEXITCODE-ne 0){throw"$name failed with exit code $LASTEXITCODE."}}
function Hash([string]$path,[string]$algorithm='SHA256'){(Get-FileHash -LiteralPath $path -Algorithm $algorithm).Hash.ToUpperInvariant()}
function Download([string]$url,[string]$path){if(Test-Path -LiteralPath $path){Write-Host "Reusing incomplete-snapshot file: $([IO.Path]::GetFileName($path))";return};& curl.exe --ssl-no-revoke -L --fail --silent --show-error --output $path $url;Assert-Native "Downloading $([IO.Path]::GetFileName($path))"}
function Inventory([string]$root){$prefix=(Resolve-Path -LiteralPath $root).Path.TrimEnd('\')+'\';@(Get-ChildItem -LiteralPath $root -File -Recurse|Sort-Object FullName|ForEach-Object{[ordered]@{relativePath=$_.FullName.Substring($prefix.Length).Replace('\','/');bytes=$_.Length;sha256=Hash $_.FullName;rows=if($_.Extension-in '.txt','.rrf'){[Math]::Max(0,([IO.File]::ReadLines($_.FullName)|Measure-Object).Count-1)}else{$null}}})}
$plan=Get-Content -LiteralPath $PlanPath -Raw|ConvertFrom-Json
if($plan.destinationRoot-cne'data/private/reference'-or $DestinationRoot-cne'.\data\private\reference'){throw'Exact private reference destination is required.'}
$allowed=@('www.fda.gov','open.fda.gov','api.fda.gov','download.open.fda.gov','www.nlm.nih.gov','uts.nlm.nih.gov')
foreach($source in $plan.sources){foreach($property in 'officialPage','downloadUrl','metadataUrl','downloadLocation'){if(($source.PSObject.Properties.Name -contains $property) -and ([uri]$source.$property).Host -notin $allowed){throw "Non-authoritative source host: $($source.code)"}};if($source.PSObject.Properties.Name -contains 'parts'){foreach($part in @($source.parts)){if(([uri]$part.downloadUrl).Host -notin $allowed){throw "Non-authoritative part host: $($source.code)"}}}}
$snapshot=Join-Path $DestinationRoot $plan.snapshotDate
Write-Host "Snapshot: $snapshot";foreach($s in $plan.sources){Write-Host "$($s.code): $($s.releaseDate) $($s.filename) $($s.downloadUrl)";if($s.manualDropRequired){Write-Host "  credential: manual UMLS drop required; MD5 $($s.publishedMd5)"}}
if(-not$PSCmdlet.ShouldProcess($snapshot,'Acquire, freeze, extract, hash and validate authoritative reference snapshots')){return}
if(Test-Path -LiteralPath $snapshot){if(-not$ResumeIncompleteSnapshot-or(Test-Path -LiteralPath (Join-Path $snapshot 'm9-reference-source-manifest.private.json'))){throw'Snapshot directory already exists; overwrite is prohibited.'}}else{New-Item -ItemType Directory -Path $snapshot|Out-Null}
$ConfirmPreference='None';$records=@();$blockers=@()
foreach($s in $plan.sources){$dir=Join-Path $snapshot $s.code;if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Path $dir|Out-Null}
 if($s.manualDropRequired){$manual=Join-Path (Join-Path $DestinationRoot 'manual-drop') $s.filename;if(-not(Test-Path -LiteralPath $manual)){$blockers+="RxNormManualDropMissing:$($s.filename)";$records+=[ordered]@{code=$s.code;releaseDate=$s.releaseDate;status='BlockedCredential';expectedFilename=$s.filename;publishedMd5=$s.publishedMd5;officialLocation=$s.downloadLocation};continue};if((Hash $manual 'MD5')-cne$s.publishedMd5.ToUpperInvariant()){throw'RxNorm published MD5 mismatch.'};$zip=Join-Path $dir $s.filename;Copy-Item -LiteralPath $manual -Destination $zip
 }elseif($s.code-eq'ndc-directory'){foreach($part in $s.parts){$zip=Join-Path $dir $part.filename;Download $part.downloadUrl $zip}}
 else{$zip=Join-Path $dir $s.filename;Download $s.downloadUrl $zip}
 foreach($zip in Get-ChildItem -LiteralPath $dir -Filter '*.zip'){$extract=Join-Path $dir ([IO.Path]::GetFileNameWithoutExtension($zip.Name));if(-not(Test-Path -LiteralPath $extract)){Expand-Archive -LiteralPath $zip.FullName -DestinationPath $extract};$names=@(Get-ChildItem -LiteralPath $extract -File -Recurse|ForEach-Object{$_.Name});if($s.PSObject.Properties.Name -contains 'requiredMembers'){foreach($required in @($s.requiredMembers)){if(-not($names|Where-Object{$_-ieq([IO.Path]::GetFileName($required))})){$blockers+="MissingMember:$($s.code):$required"}}}}
 $records+=[ordered]@{code=$s.code;releaseDate=$s.releaseDate;status='Acquired';role=$s.role;expectedRecords=if($s.PSObject.Properties.Name -contains 'expectedRecords'){$s.expectedRecords}else{$null};files=Inventory $dir}}
$private=[ordered]@{version=$plan.version;snapshotDate=$plan.snapshotDate;retrievedAtUtc=[DateTime]::UtcNow.ToString('O');sources=$records;blockers=$blockers};$privateJson=$private|ConvertTo-Json -Depth 12;$privatePath=Join-Path $snapshot 'm9-reference-source-manifest.private.json';[IO.File]::WriteAllText($privatePath,$privateJson,[Text.UTF8Encoding]::new($false));$aggregate=Hash $privatePath
$auditRoot='.\artifacts\research-audit';[IO.Directory]::CreateDirectory($auditRoot)|Out-Null;$audit=Join-Path $auditRoot 'm9-reference-acquisition-report.json';$public=[ordered]@{snapshotDate=$plan.snapshotDate;aggregateManifestSha256=$aggregate;sources=@($records|ForEach-Object{[ordered]@{code=$_.code;releaseDate=$_.releaseDate;status=$_.status;fileCount=@($_.files|Where-Object{$_}).Count;rowCount=if($_.code-eq'ndc-directory'){$_.expectedRecords}else{(@($_.files)|Measure-Object rows -Sum).Sum}}});blockers=$blockers};[IO.File]::WriteAllText($audit,($public|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));Write-Host "Private manifest: $privatePath";Write-Host "Aggregate SHA256: $aggregate";if($blockers.Count){Write-Warning ($blockers-join'; ')}
