[CmdletBinding(SupportsShouldProcess,ConfirmImpact='High')]
param([string]$SnapshotCode='2026-07-22-first-generic-r6')
$ErrorActionPreference='Stop';trap{[Console]::Error.WriteLine($_.Exception.Message);exit 1};if($env:PHARMAACCESS_ALLOW_RESEARCH_DB_WRITE-cne'YES'){throw'PHARMAACCESS_ALLOW_RESEARCH_DB_WRITE must equal YES exactly.'}
function Assert-Native([string]$o){if($LASTEXITCODE-ne 0){throw "$o failed with native exit code $LASTEXITCODE."}}
$requestedWhatIf=$WhatIfPreference;$WhatIfPreference=$false;$root=(Resolve-Path '.').Path;$snapshot=Join-Path $root "data\private\reference\$SnapshotCode";$manifest=Get-Content (Join-Path $snapshot 'm9-fda-first-generic-html-manifest.private.json') -Raw|ConvertFrom-Json
$secret=@(dotnet user-secrets list --project '.\src\PharmaAccess.Api\PharmaAccess.Api.csproj');Assert-Native 'Reading secrets';$line=$secret|Where-Object{$_-match'^ConnectionStrings:PharmaAccess\s*='}|Select-Object -First 1;$cs=$line.Substring($line.IndexOf('=')+1).Trim();if($cs-notmatch'(?i)Server\s*=\s*\.'-or$cs-notmatch'(?i)Database\s*=\s*PharmaAccessCausalIntelligence_ResearchDev'){throw'Exact database target required.'}
$pre=@(sqlcmd -S . -E -d PharmaAccessCausalIntelligence_ResearchDev -b -W -h-1 -Q "SET NOCOUNT ON;SELECT Status FROM research.ResearchProtocol WHERE ProtocolCode='approval-to-access-real' AND ProtocolVersion='1.2';SELECT COUNT(*) FROM core.SourceFile WHERE SchemaVersion='fda-first-generic-html-v1.1';");Assert-Native 'Preflight';if(-not($pre-match'Approved')-or($pre|Where-Object{$_.Trim()-eq'0'}).Count-ne1){throw'Protocol approval or idempotency gate failed.'};$WhatIfPreference=$requestedWhatIf
Write-Host 'Structured events: 457; existing FDA raw rows will not be changed.';if(-not$PSCmdlet.ShouldProcess('PharmaAccessCausalIntelligence_ResearchDev','Register five FDA HTML sources and bulk-import structured event JSON')){return}
$cn=[System.Data.SqlClient.SqlConnection]::new($cs);$cn.Open();$tx=$cn.BeginTransaction();try{$dataset=[int]([System.Data.SqlClient.SqlCommand]::new("SELECT DatasetVersionId FROM core.DatasetVersion WHERE VersionCode='real-2021-2025-v1'",$cn,$tx).ExecuteScalar());foreach($s in $manifest.sources){$cmd=$cn.CreateCommand();$cmd.Transaction=$tx;$cmd.CommandText="INSERT core.SourceFile(DatasetVersionId,SourceType,OriginalFileName,SourceUrl,RetrievedAtUtc,ImportedAtUtc,ReportingPeriod,Sha256,ByteSize,[RowCount],RejectedRowCount,SchemaVersion,LicenseNote,ImportStatus) OUTPUT INSERTED.SourceFileId VALUES(@d,N'FDAFirstGeneric',@f,@u,@r,SYSUTCDATETIME(),@p,@h,@b,@n,0,N'fda-first-generic-html-v1.1',N'Public FDA source; structured HTML table lineage.',N'Imported')";[void]$cmd.Parameters.AddWithValue('@d',$dataset);[void]$cmd.Parameters.AddWithValue('@f',$s.htmlFile);[void]$cmd.Parameters.AddWithValue('@u',$s.officialUrl);[void]$cmd.Parameters.AddWithValue('@r',[DateTime]$s.retrievedAtUtc);[void]$cmd.Parameters.AddWithValue('@p',[string]$s.year);[void]$cmd.Parameters.AddWithValue('@h',$s.htmlSha256);[void]$cmd.Parameters.AddWithValue('@b',[long]$s.bytes);[void]$cmd.Parameters.AddWithValue('@n',[long]$s.rowCount);$id=[int]$cmd.ExecuteScalar();$rows=Get-Content (Join-Path $snapshot $s.structuredFile) -Raw|ConvertFrom-Json;$table=[Data.DataTable]::new();[void]$table.Columns.Add('SourceFileId',[int]);[void]$table.Columns.Add('SourceRowNumber',[long]);[void]$table.Columns.Add('RawValuesJson',[string]);[void]$table.Columns.Add('ImportedAtUtc',[DateTime]);foreach($r in $rows){[void]$table.Rows.Add($id,[long]$r.source_row_number,($r|ConvertTo-Json -Compress),[DateTime]::UtcNow)};$bulk=[System.Data.SqlClient.SqlBulkCopy]::new($cn,[System.Data.SqlClient.SqlBulkCopyOptions]::CheckConstraints,$tx);$bulk.DestinationTableName='[raw].[ResearchReferenceRaw]';foreach($c in $table.Columns){[void]$bulk.ColumnMappings.Add($c.ColumnName,$c.ColumnName)};$bulk.WriteToServer($table);$bulk.Dispose()};$tx.Commit();Write-Host 'Imported 457 governed structured approval events.'}catch{$tx.Rollback();throw}finally{$cn.Dispose()}
