[CmdletBinding(SupportsShouldProcess, ConfirmImpact='High')]
param([string]$DefinitionPath='.\config\research-protocols\approval-to-access-real-1.0.json')
$ErrorActionPreference='Stop'; trap { [Console]::Error.WriteLine($_.Exception.Message); exit 1 }
function Assert-Native([string]$name){if($LASTEXITCODE-ne 0){throw "$name failed with exit code $LASTEXITCODE."}}
if($env:PHARMAACCESS_ALLOW_RESEARCH_DB_WRITE-cne'YES'){throw'PHARMAACCESS_ALLOW_RESEARCH_DB_WRITE must equal YES exactly.'}
$document=Get-Content -LiteralPath $DefinitionPath -Raw|ConvertFrom-Json
Write-Host "Protocol: $($document.protocolCode) / $($document.protocolVersion)"; Write-Host "Question: $($document.researchQuestion)"; Write-Host "Study period: $($document.studyPeriod|ConvertTo-Json -Compress)"; Write-Host "Predictive: $($document.predictive|ConvertTo-Json -Compress)"; Write-Host "Causal: $($document.causal|ConvertTo-Json -Compress)"; Write-Host "Remaining review questions: $(@($document.remainingReviewQuestions).Count)"
if((Get-Content -LiteralPath $DefinitionPath -Raw).Contains('HUMAN_DECISION_REQUIRED')){Write-Warning 'Creation is blocked until every human decision is resolved in a reviewed protocol version.';if($WhatIfPreference){return};throw 'Unresolved human decisions prevent protocol creation.'}
$secret=@(dotnet user-secrets list --project '.\src\PharmaAccess.Api\PharmaAccess.Api.csproj');Assert-Native 'Reading user secrets';$line=$secret|Where-Object{$_-match'^ConnectionStrings:PharmaAccess\s*='}|Select-Object -First 1;if(-not$line){throw'Connection secret missing.'};$connection=$line.Substring($line.IndexOf('=')+1).Trim();if($connection-notmatch'(?i)(?:Server|Data Source)\s*=\s*\.(?:;|$)'-or$connection-notmatch'(?i)(?:Database|Initial Catalog)\s*=\s*PharmaAccessCausalIntelligence_ResearchDev(?:;|$)'){throw'Exact database target required.'}
$owner=@(sqlcmd -S . -E -d PharmaAccessCausalIntelligence_ResearchDev -b -W -h-1 -s '|' -Q 'SET NOCOUNT ON;SELECT ProjectId,RepositoryMarker FROM research.ResearchDatabaseOwnership;');Assert-Native 'Reading ownership';if(-not($owner-match'PharmaAccessCausalIntelligence\s*\|\s*pharma-access-causal-intelligence')){throw'Ownership mismatch.'}
if(-not$PSCmdlet.ShouldProcess("$($document.protocolCode)/$($document.protocolVersion)",'Create Draft protocol only')){return}
$env:ConnectionStrings__PharmaAccess=$connection;try{dotnet run --no-build --project '.\src\PharmaAccess.Worker\PharmaAccess.Worker.csproj' -- create-real-protocol $DefinitionPath;Assert-Native 'Creating Draft protocol'}finally{Remove-Item Env:ConnectionStrings__PharmaAccess -ErrorAction SilentlyContinue}
