[CmdletBinding(SupportsShouldProcess,ConfirmImpact='High')]
param(
 [string]$PrivateRoot='.\data\private',[string]$ManifestPath='.\data\private\mappings\research-sources.private.json',[string]$ValidationReportPath='.\artifacts\research-audit\m9-source-validation-repaired.json',
 [string]$ProtocolCode='approval-to-access-real',[string]$ProtocolVersion='1.0',[string]$DatasetVersion='real-2021-2025-v1',[string]$PreviousCorrelationId='m9b-real-import-002',[Parameter(Mandatory)][string]$ResumeAuditId,
 [ValidateSet(20000,50000,100000)][int]$BatchSize=50000,[switch]$AllowDirtyWorktreePreview)
$ErrorActionPreference='Stop';trap{[Console]::Error.WriteLine($_.Exception.Message);exit 1}
function Assert-Native([string]$name){if($LASTEXITCODE-ne 0){throw"$name failed with exit code $LASTEXITCODE."}}
if($env:PHARMAACCESS_ALLOW_RESEARCH_DB_WRITE-cne'YES'){throw'PHARMAACCESS_ALLOW_RESEARCH_DB_WRITE must equal YES exactly.'}
$secret=@(dotnet user-secrets list --project '.\src\PharmaAccess.Api\PharmaAccess.Api.csproj');Assert-Native 'Reading user secrets';$line=$secret|Where-Object{$_-match'^ConnectionStrings:PharmaAccess\s*='}|Select-Object -First 1;if(-not$line){throw'Connection secret missing.'};$connection=$line.Substring($line.IndexOf('=')+1).Trim();if($connection-notmatch'(?i)(?:Server|Data Source)\s*=\s*\.(?:;|$)'-or$connection-notmatch'(?i)(?:Database|Initial Catalog)\s*=\s*PharmaAccessCausalIntelligence_ResearchDev(?:;|$)'){throw'Exact server and database are required.'}
$owner=@(sqlcmd -S . -E -d PharmaAccessCausalIntelligence_ResearchDev -b -W -h-1 -s '|' -Q 'SET NOCOUNT ON;SELECT ProjectId,RepositoryMarker FROM research.ResearchDatabaseOwnership;');Assert-Native 'Reading ownership';if(-not($owner-match'PharmaAccessCausalIntelligence\s*\|\s*pharma-access-causal-intelligence')){throw'Ownership mismatch.'}
$state=@(sqlcmd -S . -E -d PharmaAccessCausalIntelligence_ResearchDev -b -W -h-1 -s '|' -Q "SET NOCOUNT ON;SELECT d.Status,r.Status,p.Status FROM research.ResearchImportRun r JOIN core.DatasetVersion d ON d.DatasetVersionId=r.DatasetVersionId JOIN research.ResearchProtocol p ON p.ResearchProtocolId=r.ResearchProtocolId WHERE d.VersionCode=N'$($DatasetVersion.Replace("'","''"))' AND r.CorrelationId=N'$($PreviousCorrelationId.Replace("'","''"))' AND p.ProtocolCode=N'$($ProtocolCode.Replace("'","''"))' AND p.ProtocolVersion=N'$($ProtocolVersion.Replace("'","''"))';");Assert-Native 'Reading resume state';$row=$state|Where-Object{$_-like'*|*'}|Select-Object -Last 1;if(-not$row){throw'Resumable dataset/run/protocol combination does not exist.'};$parts=$row.Split('|').ForEach({$_.Trim()});if($parts[0]-in@('Validated','Finalized')-or$parts[1]-notin@('Importing','Failed')-or$parts[2]-cne'Approved'){throw'Resume lifecycle state is invalid.'}
$savedImportWhatIf=$global:WhatIfPreference;$global:WhatIfPreference=$false;try{Import-Module (Join-Path $PSScriptRoot 'modules\ResearchSourceIntegrity.psm1') -Force}finally{$global:WhatIfPreference=$savedImportWhatIf};$manifest=Get-Content -LiteralPath $ManifestPath -Raw|ConvertFrom-Json;foreach($a in $manifest.assignments){$check=Test-ResearchSourceAssignment $PrivateRoot ([string]$a.relativePath) ([string]$a.sha256);if($check.Status-ne'Match'){throw"Resume source integrity failed: $($a.relativePath) [$($check.Status)]"}}
$tracked=@(git ls-files 'data/private/**' 'artifacts/research-audit/**' '.venv/**' '**/bin/**' '**/obj/**');Assert-Native 'Checking tracked private paths';if($tracked.Count){throw'Private or generated paths are tracked.'};$dirty=@(git status --short);Assert-Native 'Checking worktree';if($dirty.Count-and(-not($WhatIfPreference-and$AllowDirtyWorktreePreview))){throw'Confirmed resume requires a clean Git worktree.'};if($dirty.Count){Write-Warning 'Preview-only dirty-worktree exception active; confirmed resume remains blocked until clean.'}
$gitCommit=@(git rev-parse HEAD|Select-Object -Last 1)[0].Trim();Assert-Native 'Reading Git commit';$env:ConnectionStrings__PharmaAccess=$connection;$savedGlobalWhatIf=$global:WhatIfPreference;try{dotnet run --no-build --project '.\src\PharmaAccess.Worker\PharmaAccess.Worker.csproj' -- validate-real-import-resume $PrivateRoot $ManifestPath $ValidationReportPath $ProtocolCode $ProtocolVersion $DatasetVersion $PreviousCorrelationId $ResumeAuditId $gitCommit $BatchSize;Assert-Native 'Validating resume'}finally{$global:WhatIfPreference=$false;Remove-Item Env:ConnectionStrings__PharmaAccess -ErrorAction SilentlyContinue;$global:WhatIfPreference=$savedGlobalWhatIf}
if(-not$PSCmdlet.ShouldProcess("PharmaAccessCausalIntelligence_ResearchDev/$DatasetVersion",'Resume committed raw import after the latest atomic checkpoint')){return}
$env:ConnectionStrings__PharmaAccess=$connection;try{dotnet run --no-build --project '.\src\PharmaAccess.Worker\PharmaAccess.Worker.csproj' -- execute-real-import $PrivateRoot $ManifestPath $ValidationReportPath $ProtocolCode $ProtocolVersion $DatasetVersion $BatchSize $PreviousCorrelationId $gitCommit true $ResumeAuditId;Assert-Native 'Resuming real import'}finally{Remove-Item Env:ConnectionStrings__PharmaAccess -ErrorAction SilentlyContinue}
