using System.Diagnostics;
using System.Globalization;
using Microsoft.ML;
using PharmaAccess.Application.MachineLearning;

namespace PharmaAccess.ML;

public sealed class DynamicAsOfPredictionService:IAsyncDisposable,IDynamicAsOfPredictionService
{
 const string Database="PharmaAccessCausalIntelligence_ResearchDev",Version="NextQuarterStateEntry-real-next-quarter-entry-serving-v1";
 readonly bool allowed;readonly string snapshotPath,comparisonPath,bundlePath;readonly Lazy<Task<Cache>> cache;
 public DynamicAsOfPredictionService(bool development,bool enabled,string snapshot,string comparison,string bundle){allowed=development&&enabled;snapshotPath=snapshot;comparisonPath=comparison;bundlePath=bundle;cache=new(LoadAndValidate,true);}
 public async Task<IReadOnlyList<HistoricalReplayLaunch>> GetLaunchesAsync(CancellationToken token=default){Guard();var c=await cache.Value.WaitAsync(token);return c.Rows.Select(x=>x.LaunchId).Distinct().Order().Select(x=>new HistoricalReplayLaunch(x,$"Generic launch {x}")).ToArray();}
 public async Task<IReadOnlyList<int>> GetQuartersAsync(int id,CancellationToken token=default){Guard();var c=await cache.Value.WaitAsync(token);var q=c.Rows.Where(x=>x.LaunchId==id&&x.Quarter<=20253).Select(x=>x.Quarter).Distinct().Order().ToArray();if(q.Length==0)throw new KeyNotFoundException("No scientifically valid dynamic as-of quarter is available.");return q;}
 public async Task<DynamicAsOfResponse> ScoreAsync(DynamicAsOfRequest request,CancellationToken token=default){Guard();if(request.GenericLaunchId<=0||request.AsOfQuarter<20211||request.AsOfQuarter>20253||request.AsOfQuarter%10 is <1 or >4)throw new ArgumentException("Dynamic launch and as-of quarter are invalid or beyond the research horizon.");var c=await cache.Value.WaitAsync(token);var rows=c.Rows.Where(x=>x.LaunchId==request.GenericLaunchId&&x.Quarter==request.AsOfQuarter&&!x.HasEntered&&!x.Censored).ToArray();if(rows.Length==0)throw new InvalidOperationException("InsufficientHistoricalContext");var data=c.Ml.Data.LoadFromEnumerable(rows.Select(x=>x.Input));var outputs=c.Ml.Data.CreateEnumerable<ModelOutput>(c.Model.Transform(data),false).ToArray();if(outputs.Length!=rows.Length)throw new InvalidDataException("Dynamic batch score count mismatch.");var ranked=rows.Zip(outputs).OrderByDescending(x=>x.Second.Probability).ThenBy(x=>x.First.StateCode,StringComparer.Ordinal).Select((x,i)=>{var s=VerifiedStateReference.Get(x.First.StateId);return new HistoricalReplayStateResult(s.StateId,s.StateCode,s.StateName,x.Second.Probability,HistoricalReplayMode.MeetsThreshold(x.Second.Probability),i+1);}).ToArray();return new(DynamicAsOfMode.Name,request.GenericLaunchId,$"Generic launch {request.GenericLaunchId}",request.AsOfQuarter,Next(request.AsOfQuarter),ranked.Length,ranked,Version,"62C607C6462D603D04CDF43662B16EAD773138C916912080B15A7F65C85F9022","real-2021-2025-v1","real-next-entry-features-v1",.08,ModelApprovalStatus.ValidationSelected,false,false,["Dynamic as-of reconstruction from authoritative historical research data.","Research/development prediction only; not causal, commercial, consumption, or market-entry advice."]);}
 void Guard(){if(!allowed)throw new InvalidOperationException("Research development dynamic as-of scoring is disabled.");}
 async Task<Cache> LoadAndValidate(){var rows=await Extract();var training=rows.Select(x=>x.Training).ToArray();var test=new TemporalTrainingDatasetBuilder().Build(training,new(2022,2023,2023,2024,2024),250_000).Test;ValidateFeatures(test);var loaded=LoadModel();var data=loaded.Ml.Data.LoadFromEnumerable(test.Select(ToInput));var probabilities=loaded.Ml.Data.CreateEnumerable<ModelOutput>(loaded.Model.Transform(data),false).Select(x=>x.Probability).ToArray();ValidateProbabilities(test,probabilities);return new(rows,loaded.Ml,loaded.Model);}
 async Task<Row[]> Extract(){var p=new ProcessStartInfo("sqlcmd"){RedirectStandardOutput=true,RedirectStandardError=true,UseShellExecute=false,CreateNoWindow=true};foreach(var a in new[]{"-S","lpc:.","-E","-d",Database,"-X","-b","-W","-h","-1","-s","|","-w","65535","-Q","SET NOCOUNT ON; "+Sql})p.ArgumentList.Add(a);using var process=Process.Start(p)??throw new InvalidOperationException("sqlcmd is unavailable.");var rows=new List<Row>(180000);while(await process.StandardOutput.ReadLineAsync() is{} line)if(!string.IsNullOrWhiteSpace(line))rows.Add(Parse(line.Split('|')));var error=await process.StandardError.ReadToEndAsync();await process.WaitForExitAsync();if(process.ExitCode!=0)throw new InvalidOperationException($"Read-only research extraction failed: {error.Trim()}");if(rows.Count!=174471)throw new InvalidDataException("Authoritative research panel row count mismatch.");return rows.ToArray();}
 void ValidateFeatures(IReadOnlyList<NextQuarterTrainingRow> test){var expected=File.ReadLines(snapshotPath).Skip(1).Select(x=>x.Split(',')).ToArray();if(expected.Length!=12477||test.Count!=12477)throw new InvalidDataException("R2A gate row count mismatch.");for(var i=0;i<test.Count;i++){var e=expected[i];var r=test[i];if(e[0]!=r.FeatureRowId.ToString()||e[1]!=r.GenericLaunchId.ToString()||e[2]!=r.StateId.ToString()||e[3]!=r.ObservationQuarterId.ToString()||e[4]!=(r.LabelNextQuarterEntry==true?"1":"0"))throw new InvalidDataException($"R2A stable-key mismatch at row {i}.");var actual=Values(ToInput(r));for(var j=0;j<32;j++){var value=float.Parse(e[j+5],NumberStyles.Float,CultureInfo.InvariantCulture);if(!(float.IsNaN(value)&&float.IsNaN(actual[j]))&&BitConverter.SingleToInt32Bits(value)!=BitConverter.SingleToInt32Bits(actual[j]))throw new InvalidDataException($"R2A feature mismatch row {i}, feature {NextQuarterFeatureSchema.OrderedFeatures[j]}.");}}}
 void ValidateProbabilities(IReadOnlyList<NextQuarterTrainingRow> test,float[] actual){var expected=File.ReadLines(comparisonPath).Skip(1).Select(x=>x.Split(',')).ToArray();if(expected.Length!=test.Count||actual.Length!=test.Count)throw new InvalidDataException("R2B gate row count mismatch.");for(var i=0;i<test.Count;i++){if(expected[i][0]!=test[i].FeatureRowId.ToString())throw new InvalidDataException("R2B key mismatch.");var p=float.Parse(expected[i][6],CultureInfo.InvariantCulture);if(BitConverter.SingleToInt32Bits(p)!=BitConverter.SingleToInt32Bits(actual[i]))throw new InvalidDataException($"R2B probability mismatch at row {i}.");}}
 (MLContext Ml,ITransformer Model) LoadModel(){var root=Path.GetDirectoryName(Path.GetFullPath(bundlePath))!;var registry=new LocalServingModelBundleRegistry(root,new("real-2021-2025-v1",2,"84B973AFF0545C987B52C525F0CBAB607C293BEFC1D5EBCC87ED6769DECB0C36","real-next-entry-features-v1",1,"8E849D11A4D25976F808E49436A6576E74311C4CC97016E7C7126C43210AC750","BE2EBF510D5E610DD4F54D4E62BB6F9BDB47EACFB496B6739659C7E6AA6C595E"));var a=registry.LoadAndVerify(Path.Combine(bundlePath,"manifest.json"));if(a.Version!=Version||a.Status!=ModelApprovalStatus.ValidationSelected||a.Sha256!="62C607C6462D603D04CDF43662B16EAD773138C916912080B15A7F65C85F9022"||a.Threshold!=.08)throw new InvalidDataException("Dynamic model identity mismatch.");var ml=new MLContext();return(ml,ml.Model.Load(a.ModelPath,out _));}
 static Row Parse(string[] x){if(x.Length!=31)throw new InvalidDataException("Research projection width mismatch.");int I(int i)=>int.Parse(x[i],CultureInfo.InvariantCulture);long L(int i)=>long.Parse(x[i],CultureInfo.InvariantCulture);decimal D(int i)=>decimal.Parse(x[i],CultureInfo.InvariantCulture);bool N(int i)=>x[i]=="NULL";long? NL(int i)=>N(i)?null:L(i);decimal? ND(int i)=>N(i)?null:D(i);bool B(int i)=>x[i]=="1";bool? NB(int i)=>N(i)?null:B(i);var t=new NextQuarterTrainingRow(L(0),I(1),I(1),I(2),I(7),I(5),true,false,false,true,B(25),NB(23),I(8),I(8)+1,F(NL(9)),F(ND(10)),F(NL(11)),F(NL(12)),F(ND(13)),F(ND(14)),Growth(NL(9),NL(11)),Growth(ND(10),ND(13)),0,0,F(ND(15)),F(ND(16)),F(ND(17)),L(18),0,float.NaN,float.NaN,(float)D(19),float.NaN,1,float.NaN,float.NaN,F(ND(20)),float.NaN,float.NaN,float.NaN,new[]{N(9),N(10),N(11),N(12),N(15),N(20)}.Count(v=>v),B(26),false,B(27));return new(I(1),I(2),x[3].Trim(),I(7),B(24),B(25),t,ToInput(t));}
 static float F<T>(T? x)where T:struct,IConvertible=>x.HasValue?Convert.ToSingle(x.Value,CultureInfo.InvariantCulture):float.NaN;static float Growth<T>(T? c,T? p)where T:struct,IConvertible{if(!c.HasValue||!p.HasValue)return float.NaN;var v=Convert.ToDouble(p.Value);return v==0?float.NaN:(float)((Convert.ToDouble(c.Value)-v)/v);}static int Next(int q)=>q%10==4?(q/10+1)*10+1:q+1;
 static ModelInput ToInput(NextQuarterTrainingRow x)=>new(){Label=x.LabelNextQuarterEntry??false,QuarterSinceApproval=x.QuarterSinceApproval,NumberOfObservedQuarters=x.NumberOfObservedQuarters,ObservedPrescriptionCount=x.ObservedPrescriptionCount,ObservedReimbursementAmount=x.ObservedReimbursementAmount,Lag1PrescriptionCount=x.Lag1PrescriptionCount,Lag2PrescriptionCount=x.Lag2PrescriptionCount,Lag1ReimbursementAmount=x.Lag1ReimbursementAmount,Lag2ReimbursementAmount=x.Lag2ReimbursementAmount,PrescriptionGrowthRate=x.PrescriptionGrowthRate,ReimbursementGrowthRate=x.ReimbursementGrowthRate,InitialActiveStateCount=x.InitialActiveStateCount,InitialPrescriptionVolume=x.InitialPrescriptionVolume,PreviousQuarterNumericDistribution=x.PreviousQuarterNumericDistribution,PreviousQuarterWeightedDistribution=x.PreviousQuarterWeightedDistribution,PreviousQuarterAccessGap=x.PreviousQuarterAccessGap,StateHistoricalGenericVolume=x.StateHistoricalGenericVolume,StateHistoricalLaunchCount=x.StateHistoricalLaunchCount,StateHistoricalEntryRate=x.StateHistoricalEntryRate,StateHistoricalMedianEntryDelay=x.StateHistoricalMedianEntryDelay,StateHistoricalMarketWeight=x.StateHistoricalMarketWeight,StateVolumePercentile=x.StateVolumePercentile,StateDataCompleteness=x.StateDataCompleteness,RegionActiveStateShare=x.RegionActiveStateShare,RegionHistoricalEntryRate=x.RegionHistoricalEntryRate,NeighborStateAdoptionShare=x.NeighborStateAdoptionShare,SimilarStateAdoptionShare=x.SimilarStateAdoptionShare,RegionPrescriptionGrowth=x.RegionPrescriptionGrowth,NationalPrescriptionGrowth=x.NationalPrescriptionGrowth,MissingFeatureCount=x.MissingFeatureCount,IsObservedZero=x.IsObservedZero?1:0,IsMissing=x.IsMissing?1:0,IsSuppressed=x.IsSuppressed?1:0};
 static float[] Values(ModelInput x)=>[x.QuarterSinceApproval,x.NumberOfObservedQuarters,x.ObservedPrescriptionCount,x.ObservedReimbursementAmount,x.Lag1PrescriptionCount,x.Lag2PrescriptionCount,x.Lag1ReimbursementAmount,x.Lag2ReimbursementAmount,x.PrescriptionGrowthRate,x.ReimbursementGrowthRate,x.InitialActiveStateCount,x.InitialPrescriptionVolume,x.PreviousQuarterNumericDistribution,x.PreviousQuarterWeightedDistribution,x.PreviousQuarterAccessGap,x.StateHistoricalGenericVolume,x.StateHistoricalLaunchCount,x.StateHistoricalEntryRate,x.StateHistoricalMedianEntryDelay,x.StateHistoricalMarketWeight,x.StateVolumePercentile,x.StateDataCompleteness,x.RegionActiveStateShare,x.RegionHistoricalEntryRate,x.NeighborStateAdoptionShare,x.SimilarStateAdoptionShare,x.RegionPrescriptionGrowth,x.NationalPrescriptionGrowth,x.MissingFeatureCount,x.IsObservedZero,x.IsMissing,x.IsSuppressed];
 public ValueTask DisposeAsync()=>ValueTask.CompletedTask;
 sealed record Row(int LaunchId,int StateId,string StateCode,int Quarter,bool Censored,bool HasEntered,NextQuarterTrainingRow Training,ModelInput Input);sealed record Cache(Row[] Rows,MLContext Ml,ITransformer Model);
const string Sql="""WITH X AS( SELECT p.*,al.ApprovalPageYear,al.Partition,s.StateId,w.PrescriptionNumerator,w.NormalizedWeight,LAG(p.PrescriptionCount,1) OVER(PARTITION BY p.AndaLaunchId,p.StateCode ORDER BY p.ObservationQuarter) Lag1Rx,LAG(p.PrescriptionCount,2) OVER(PARTITION BY p.AndaLaunchId,p.StateCode ORDER BY p.ObservationQuarter) Lag2Rx,LAG(p.ReimbursementAmount,1) OVER(PARTITION BY p.AndaLaunchId,p.StateCode ORDER BY p.ObservationQuarter) Lag1Reimb,LAG(p.ReimbursementAmount,2) OVER(PARTITION BY p.AndaLaunchId,p.StateCode ORDER BY p.ObservationQuarter) Lag2Reimb,LAG(p.NumericDistribution,51) OVER(PARTITION BY p.AndaLaunchId ORDER BY p.ObservationQuarter,p.StateCode) PrevND,LAG(p.WeightedDistribution,51) OVER(PARTITION BY p.AndaLaunchId ORDER BY p.ObservationQuarter,p.StateCode) PrevWD,LAG(p.AccessGap,51) OVER(PARTITION BY p.AndaLaunchId ORDER BY p.ObservationQuarter,p.StateCode) PrevGap FROM research.AndaStateQuarterPanel p JOIN research.AndaLaunch al ON al.AndaLaunchId=p.AndaLaunchId JOIN core.State s ON s.StateCode=p.StateCode JOIN research.HistoricalMarketWeight w ON w.StateCode=p.StateCode) SELECT PanelRowId,AndaLaunchId,StateId,RTRIM(StateCode),Region,ApprovalPageYear,Partition,ObservationQuarter,QuarterSinceApproval,PrescriptionCount,ReimbursementAmount,Lag1Rx,Lag2Rx,Lag1Reimb,Lag2Reimb,PrevND,PrevWD,PrevGap,PrescriptionNumerator,NormalizedWeight,LaggedNeighborExposure,EligiblePeerCount,HighNeighborAdoptionExposure,LabelNextQuarterEntry,IsCensored,HasEntered,IsObservedZero,IsSuppressed,NumericDistribution,WeightedDistribution,AccessGap FROM X ORDER BY AndaLaunchId,StateId,ObservationQuarter OPTION (MAXDOP 1);""";
}
