using System.Globalization;
using System.Security.Cryptography;
using Microsoft.ML;
using PharmaAccess.Application.MachineLearning;

namespace PharmaAccess.ML;

public sealed class HistoricalPredictionReplayService
{
    public static IHistoricalPredictionReplayService Create(bool isDevelopment,bool enabled,string snapshotPath,string bundlePath)
        =>new Implementation(isDevelopment,enabled,snapshotPath,bundlePath);

    private sealed class Implementation(bool development,bool enabled,string snapshotPath,string bundlePath):IHistoricalPredictionReplayService
    {
        private const string Version="NextQuarterStateEntry-real-next-quarter-entry-serving-v1";
        private readonly Lazy<(SelectedModelArtifact Artifact,MLContext Ml,ITransformer Model)> model=new(()=>Load(bundlePath),true);
        private readonly Lazy<Snapshot> source=new(()=>new Snapshot(snapshotPath),true);
        public Task<IReadOnlyList<HistoricalReplayLaunch>> GetLaunchesAsync(CancellationToken token=default){Guard();token.ThrowIfCancellationRequested();return Task.FromResult<IReadOnlyList<HistoricalReplayLaunch>>(source.Value.Rows.Select(x=>x.GenericLaunchId).Distinct().Order().Select(x=>new HistoricalReplayLaunch(x,$"Generic launch {x}")).ToArray());}
        public Task<IReadOnlyList<int>> GetQuartersAsync(int id,CancellationToken token=default){Guard();token.ThrowIfCancellationRequested();var values=source.Value.Rows.Where(x=>x.GenericLaunchId==id).Select(x=>x.Quarter).Distinct().Order().ToArray();if(values.Length==0)throw new KeyNotFoundException("Generic launch is unavailable in the verified replay snapshot.");return Task.FromResult<IReadOnlyList<int>>(values);}
        public Task<HistoricalReplayResponse> ReplayAsync(HistoricalReplayRequest request,CancellationToken token=default)
        {
            Guard();token.ThrowIfCancellationRequested();if(request.GenericLaunchId<=0||request.AsOfQuarter<19001)throw new ArgumentException("A valid launch and as-of quarter are required.");var rows=source.Value.Rows.Where(x=>x.GenericLaunchId==request.GenericLaunchId&&x.Quarter==request.AsOfQuarter).ToArray();if(rows.Length==0)throw new KeyNotFoundException("The requested launch-quarter is unavailable in the verified replay snapshot.");
            var loaded=model.Value;var data=loaded.Ml.Data.LoadFromEnumerable(rows.Select(x=>x.Input));var transformed=loaded.Model.Transform(data);var outputs=loaded.Ml.Data.CreateEnumerable<ModelOutput>(transformed,reuseRowObject:false).ToArray();if(outputs.Length!=rows.Length)throw new InvalidDataException("Batch scorer row count mismatch.");
            var ranked=rows.Zip(outputs).OrderByDescending(x=>x.Second.Probability).ThenBy(x=>x.First.StateId).Select((x,i)=>new HistoricalReplayStateResult(x.First.StateId,$"Jurisdiction {x.First.StateId}",x.Second.Probability,HistoricalReplayMode.MeetsThreshold(x.Second.Probability),i+1)).ToArray();
            return Task.FromResult(new HistoricalReplayResponse(HistoricalReplayMode.Name,request.GenericLaunchId,$"Generic launch {request.GenericLaunchId}",request.AsOfQuarter,NextQuarter(request.AsOfQuarter),loaded.Artifact.Version,loaded.Artifact.Sha256,"real-2021-2025-v1",loaded.Artifact.DatasetVersionId,"real-next-entry-features-v1",loaded.Artifact.FeatureSetVersionId,loaded.Artifact.Threshold,ranked.Length,ranked,["Historical replay using a verified research model that is not approved for production serving.","The target is first observed eligible Medicaid utilization in T+1; this is not a causal estimate or commercial recommendation."],loaded.Artifact.Status,false,false));
        }
        private void Guard(){if(!development||!enabled)throw new InvalidOperationException("Research development historical replay is disabled.");}
        private static (SelectedModelArtifact,MLContext,ITransformer) Load(string path){var root=Path.GetDirectoryName(Path.GetFullPath(path))??throw new InvalidDataException("Bundle root is invalid.");var registry=new LocalServingModelBundleRegistry(root,new("real-2021-2025-v1",2,"84B973AFF0545C987B52C525F0CBAB607C293BEFC1D5EBCC87ED6769DECB0C36","real-next-entry-features-v1",1,"8E849D11A4D25976F808E49436A6576E74311C4CC97016E7C7126C43210AC750","BE2EBF510D5E610DD4F54D4E62BB6F9BDB47EACFB496B6739659C7E6AA6C595E"));var artifact=registry.LoadAndVerify(Path.Combine(path,"manifest.json"));if(artifact.Version!=Version||artifact.Status!=ModelApprovalStatus.ValidationSelected||artifact.Sha256!="62C607C6462D603D04CDF43662B16EAD773138C916912080B15A7F65C85F9022"||artifact.Threshold!=.08)throw new InvalidDataException("Registered research candidate identity mismatch.");var ml=new MLContext();var model=ml.Model.Load(artifact.ModelPath,out _);return(artifact,ml,model);}
        private static int NextQuarter(int value){var year=value/10;var quarter=value%10;if(quarter is <1 or >4)throw new InvalidDataException("Snapshot quarter is invalid.");return quarter==4?(year+1)*10+1:year*10+quarter+1;}
    }

    private sealed class Snapshot
    {
        private const string Hash="8B049DC35661502EA0E1236B8275D81EA21F540D7D6F729F4FAC2C6A3A4F336D";
        public Row[] Rows{get;}
        public Snapshot(string path){var full=Path.GetFullPath(path);using(var stream=File.OpenRead(full))if(Convert.ToHexString(SHA256.HashData(stream))!=Hash)throw new InvalidDataException("Historical replay snapshot hash mismatch.");var lines=File.ReadAllLines(full);var header=lines[0].Split(',');var expected=new[]{"QuarterSinceApproval","NumberOfObservedQuarters","ObservedPrescriptionCount","ObservedReimbursementAmount","Lag1PrescriptionCount","Lag2PrescriptionCount","Lag1ReimbursementAmount","Lag2ReimbursementAmount","PrescriptionGrowthRate","ReimbursementGrowthRate","InitialActiveStateCount","InitialPrescriptionVolume","PreviousQuarterNumericDistribution","PreviousQuarterWeightedDistribution","PreviousQuarterAccessGap","StateHistoricalGenericVolume","StateHistoricalLaunchCount","StateHistoricalEntryRate","StateHistoricalMedianEntryDelay","StateHistoricalMarketWeight","StateVolumePercentile","StateDataCompleteness","RegionActiveStateShare","RegionHistoricalEntryRate","NeighborStateAdoptionShare","SimilarStateAdoptionShare","RegionPrescriptionGrowth","NationalPrescriptionGrowth","MissingFeatureCount","IsObservedZero","IsMissing","IsSuppressed"};if(header.Length!=37||!header.Skip(5).SequenceEqual(expected,StringComparer.Ordinal))throw new InvalidDataException("Historical replay snapshot schema mismatch.");Rows=lines.Skip(1).Select(Parse).ToArray();if(Rows.Length!=12477||Rows.Select(x=>x.GenericLaunchId).Distinct().Count()!=48||Rows.Select(x=>x.StateId).Distinct().Count()!=51||Rows.Count(x=>x.Label)!=256)throw new InvalidDataException("Historical replay snapshot invariants failed.");}
        private static Row Parse(string line){var v=line.Split(',');if(v.Length!=37)throw new InvalidDataException("Snapshot row width mismatch.");float F(int i)=>float.Parse(v[i],NumberStyles.Float,CultureInfo.InvariantCulture);var input=new ModelInput{Label=v[4]=="1",QuarterSinceApproval=F(5),NumberOfObservedQuarters=F(6),ObservedPrescriptionCount=F(7),ObservedReimbursementAmount=F(8),Lag1PrescriptionCount=F(9),Lag2PrescriptionCount=F(10),Lag1ReimbursementAmount=F(11),Lag2ReimbursementAmount=F(12),PrescriptionGrowthRate=F(13),ReimbursementGrowthRate=F(14),InitialActiveStateCount=F(15),InitialPrescriptionVolume=F(16),PreviousQuarterNumericDistribution=F(17),PreviousQuarterWeightedDistribution=F(18),PreviousQuarterAccessGap=F(19),StateHistoricalGenericVolume=F(20),StateHistoricalLaunchCount=F(21),StateHistoricalEntryRate=F(22),StateHistoricalMedianEntryDelay=F(23),StateHistoricalMarketWeight=F(24),StateVolumePercentile=F(25),StateDataCompleteness=F(26),RegionActiveStateShare=F(27),RegionHistoricalEntryRate=F(28),NeighborStateAdoptionShare=F(29),SimilarStateAdoptionShare=F(30),RegionPrescriptionGrowth=F(31),NationalPrescriptionGrowth=F(32),MissingFeatureCount=F(33),IsObservedZero=F(34),IsMissing=F(35),IsSuppressed=F(36)};return new(long.Parse(v[0],CultureInfo.InvariantCulture),int.Parse(v[1],CultureInfo.InvariantCulture),int.Parse(v[2],CultureInfo.InvariantCulture),int.Parse(v[3],CultureInfo.InvariantCulture),v[4]=="1",input);}
    }
    private sealed record Row(long FeatureRowId,int GenericLaunchId,int StateId,int Quarter,bool Label,ModelInput Input);
}
