using System.Diagnostics;
using System.Globalization;
using PharmaAccess.Application.MachineLearning;
namespace PharmaAccess.ML;
public sealed class ResearchLaunchCatalogService(bool development,bool enabled):IResearchLaunchCatalogService
{
 readonly Lazy<Task<IReadOnlyList<HistoricalReplayLaunch>>> cache=new(()=>Load(),true);
 public Task<IReadOnlyList<HistoricalReplayLaunch>> GetLaunchesAsync(CancellationToken token=default){if(!development||!enabled)throw new InvalidOperationException("Research launch catalog is disabled.");return cache.Value.WaitAsync(token);}
 static async Task<IReadOnlyList<HistoricalReplayLaunch>> Load(){var p=new ProcessStartInfo("sqlcmd"){RedirectStandardOutput=true,RedirectStandardError=true,UseShellExecute=false,CreateNoWindow=true};foreach(var a in new[]{"-S","lpc:.","-E","-d","PharmaAccessCausalIntelligence_ResearchDev","-X","-b","-W","-h","-1","-s","|","-Q","SET NOCOUNT ON; SELECT al.AndaLaunchId,RTRIM(al.GenericLaunchCode),RTRIM(al.Anda),CONVERT(char(10),al.ApprovalDate,23),al.ApprovalPageYear,al.SequenceNumber FROM research.AndaLaunch al WHERE EXISTS (SELECT 1 FROM research.AndaStateQuarterPanel p WHERE p.AndaLaunchId=al.AndaLaunchId) ORDER BY al.AndaLaunchId;"})p.ArgumentList.Add(a);using var process=Process.Start(p)??throw new InvalidOperationException("sqlcmd is unavailable.");var result=new List<HistoricalReplayLaunch>(261);while(await process.StandardOutput.ReadLineAsync() is{} line){if(string.IsNullOrWhiteSpace(line))continue;var x=line.Split('|');if(x.Length!=6)throw new InvalidDataException("Launch catalog projection width mismatch.");var id=int.Parse(x[0],CultureInfo.InvariantCulture);var anda=x[2].Trim();var date=DateOnly.ParseExact(x[3],"yyyy-MM-dd",CultureInfo.InvariantCulture);result.Add(new(id,$"{x[1].Trim()} — ANDA {anda} — {date:yyyy-MM-dd}",x[1].Trim(),anda,date,int.Parse(x[4],CultureInfo.InvariantCulture),int.Parse(x[5],CultureInfo.InvariantCulture)));}var error=await process.StandardError.ReadToEndAsync();await process.WaitForExitAsync();if(process.ExitCode!=0)throw new InvalidOperationException($"Read-only launch catalog extraction failed: {error.Trim()}");if(result.Count!=261||result.Select(x=>x.GenericLaunchId).Distinct().Count()!=261||result.Any(x=>string.IsNullOrWhiteSpace(x.GenericLaunchCode)||string.IsNullOrWhiteSpace(x.Anda)))throw new InvalidDataException("Authoritative launch catalog invariants failed.");return result;}
}
