using PharmaAccess.Application.MachineLearning;
using PharmaAccess.ML;
using Xunit;
namespace PharmaAccess.ML.Tests;
public sealed class DynamicAsOfPredictionTests
{
 static string Root{get{var p=AppContext.BaseDirectory;while(p is not null&&!File.Exists(Path.Combine(p,"PharmaAccess.sln")))p=Directory.GetParent(p)?.FullName;return p??throw new DirectoryNotFoundException();}}
 static string Snapshot=>Path.Combine(Root,"artifacts","recovery","next-state-entry-r2a","reconstructed-final-test-features","final-test-features.csv");static string Comparison=>Path.Combine(Root,"artifacts","recovery","next-state-entry-r2b","prediction-comparison.csv");static string Bundle=>Path.Combine(Root,"artifacts","models","NextQuarterStateEntry-real-next-quarter-entry-serving-v1");
 [Fact]public async Task Full_R2A_and_R2B_gate_passes_before_dynamic_scoring_and_anchor_probabilities_are_unchanged(){await using var dynamic=new DynamicAsOfPredictionService(true,true,Snapshot,Comparison,Bundle);var launches=await dynamic.GetLaunchesAsync();Assert.Equal(261,launches.Count);var result=await dynamic.ScoreAsync(new(291,20244));var replay=HistoricalPredictionReplayService.Create(true,true,Snapshot,Bundle);var historical=await replay.ReplayAsync(new(291,20244));Assert.Equal(DynamicAsOfMode.Name,result.Mode);Assert.Equal(51,result.RankedStates.Count);Assert.All(result.RankedStates,x=>Assert.Equal(historical.RankedStates.Single(y=>y.StateId==x.StateId).Probability,x.Probability));Assert.Equal(result.RankedStates.OrderByDescending(x=>x.Probability).ThenBy(x=>x.StateCode,StringComparer.Ordinal),result.RankedStates);Assert.Equal(.08,result.SelectedThreshold);var enteredExcluded=await dynamic.ScoreAsync(new(94,20244));Assert.Single(enteredExcluded.RankedStates);Assert.Equal(ModelApprovalStatus.ValidationSelected,result.GovernanceStatus);Assert.False(result.ProductionApproved);Assert.False(result.Champion);}
 [Theory][InlineData(false,false)][InlineData(false,true)][InlineData(true,false)]public async Task Dynamic_fails_closed_without_development_and_flag(bool development,bool enabled){await using var service=new DynamicAsOfPredictionService(development,enabled,Snapshot,Comparison,Bundle);await Assert.ThrowsAsync<InvalidOperationException>(()=>service.GetLaunchesAsync());}
 [Theory][InlineData(20254)][InlineData(20261)][InlineData(20250)]public async Task Future_or_invalid_quarter_is_rejected(int quarter){await using var service=new DynamicAsOfPredictionService(true,true,Snapshot,Comparison,Bundle);await Assert.ThrowsAsync<ArgumentException>(()=>service.ScoreAsync(new(291,quarter)));}
}
