using System.Globalization;
using PharmaAccess.Application.MachineLearning;
using PharmaAccess.ML;
using Xunit;

namespace PharmaAccess.ML.Tests;

public sealed class HistoricalPredictionReplayTests
{
    [Fact]public void Verified_state_reference_is_complete_and_unique(){Assert.Equal(51,VerifiedStateReference.All.Count);Assert.Equal(51,VerifiedStateReference.All.Select(x=>x.StateId).Distinct().Count());Assert.Equal(51,VerifiedStateReference.All.Select(x=>x.StateCode).Distinct(StringComparer.Ordinal).Count());Assert.All(VerifiedStateReference.All,x=>{Assert.False(string.IsNullOrWhiteSpace(x.StateName));Assert.Same(x,VerifiedStateReference.Get(x.StateId));});}
    private static string Root=>FindRoot();private static string Snapshot=>Path.Combine(Root,"artifacts","recovery","next-state-entry-r2a","reconstructed-final-test-features","final-test-features.csv");private static string Bundle=>Path.Combine(Root,"artifacts","models","NextQuarterStateEntry-real-next-quarter-entry-serving-v1");
    [Theory][InlineData(false,false)][InlineData(false,true)][InlineData(true,false)]public async Task Replay_fails_closed_unless_development_and_explicitly_enabled(bool development,bool enabled){var service=HistoricalPredictionReplayService.Create(development,enabled,Snapshot,Bundle);await Assert.ThrowsAsync<InvalidOperationException>(()=>service.GetLaunchesAsync());}
    [Fact]public async Task Verified_snapshot_catalog_and_replay_are_deterministic_and_match_r2b_anchor()
    {
        var service=HistoricalPredictionReplayService.Create(true,true,Snapshot,Bundle);var launches=await service.GetLaunchesAsync();Assert.Equal(48,launches.Count);Assert.Equal(launches.OrderBy(x=>x.GenericLaunchId),launches);var quarters=await service.GetQuartersAsync(291);Assert.Equal(quarters.Order(),quarters);
        var result=await service.ReplayAsync(new(291,20244));Assert.Equal(HistoricalReplayMode.Name,result.Mode);Assert.Equal(20251,result.TargetQuarter);Assert.Equal(51,result.TotalEligibleJurisdictions);Assert.Equal(Enumerable.Range(1,51),result.RankedStates.Select(x=>x.Rank));Assert.Equal(result.RankedStates.OrderByDescending(x=>x.Probability).ThenBy(x=>x.StateId),result.RankedStates);Assert.Equal(.08,result.SelectedThreshold);Assert.False(result.ProductionApproved);Assert.False(result.Champion);Assert.Equal(ModelApprovalStatus.ValidationSelected,result.GovernanceStatus);
        var anchor=File.ReadLines(Path.Combine(Root,"artifacts","recovery","next-state-entry-r2b","prediction-comparison.csv")).Skip(1).Select(x=>x.Split(',')).Where(x=>x[1]=="291"&&x[3]=="20244").ToDictionary(x=>int.Parse(x[2],CultureInfo.InvariantCulture),x=>float.Parse(x[6],CultureInfo.InvariantCulture));Assert.Equal(51,anchor.Count);Assert.All(result.RankedStates,x=>Assert.Equal(anchor[x.StateId],x.Probability));
    }
    [Fact]public void External_threshold_uses_probability_not_serialized_predicted_label(){Assert.True(HistoricalReplayMode.MeetsThreshold(.10f));Assert.False(HistoricalReplayMode.MeetsThreshold(.05f));}
    [Fact]public async Task Unavailable_selection_fails_cleanly(){var service=HistoricalPredictionReplayService.Create(true,true,Snapshot,Bundle);await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.GetQuartersAsync(-1));await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.ReplayAsync(new(291,19991)));}
    [Fact]public async Task Snapshot_tampering_fails_closed(){var path=Path.Combine(Environment.GetEnvironmentVariable("TEMP")??Path.GetTempPath(),$"snapshot-{Guid.NewGuid():N}.csv");File.Copy(Snapshot,path);try{File.AppendAllText(path,"tamper");var service=HistoricalPredictionReplayService.Create(true,true,path,Bundle);await Assert.ThrowsAsync<InvalidDataException>(()=>service.GetLaunchesAsync());}finally{File.Delete(path);}}
    [Theory][InlineData("syntheticDevelopmentData\": false","syntheticDevelopmentData\": true")][InlineData("CD0ADF754622B41A3091A8C47519511F4546A09C26F974412E12C3A4E28D2ACE","000ADF754622B41A3091A8C47519511F4546A09C26F974412E12C3A4E28D2ACE")][InlineData("BE2EBF510D5E610DD4F54D4E62BB6F9BDB47EACFB496B6739659C7E6AA6C595E","000EBF510D5E610DD4F54D4E62BB6F9BDB47EACFB496B6739659C7E6AA6C595E")]
    public async Task Bundle_synthetic_r2b_or_schema_mismatch_fails_closed(string find,string replace){var root=Path.Combine(Environment.GetEnvironmentVariable("TEMP")??Path.GetTempPath(),$"bundle-{Guid.NewGuid():N}");Directory.CreateDirectory(root);try{foreach(var file in Directory.GetFiles(Bundle))File.Copy(file,Path.Combine(root,Path.GetFileName(file)));var manifest=Path.Combine(root,"manifest.json");File.WriteAllText(manifest,File.ReadAllText(manifest).Replace(find,replace));var service=HistoricalPredictionReplayService.Create(true,true,Snapshot,root);await Assert.ThrowsAsync<InvalidDataException>(()=>service.ReplayAsync(new(291,20244)));}finally{Directory.Delete(root,true);}}
    [Fact]public async Task Artifact_tampering_fails_closed(){var root=Path.Combine(Environment.GetEnvironmentVariable("TEMP")??Path.GetTempPath(),$"bundle-{Guid.NewGuid():N}");Directory.CreateDirectory(root);try{foreach(var file in Directory.GetFiles(Bundle))File.Copy(file,Path.Combine(root,Path.GetFileName(file)));File.AppendAllText(Path.Combine(root,"model.zip"),"tamper");var service=HistoricalPredictionReplayService.Create(true,true,Snapshot,root);await Assert.ThrowsAsync<InvalidDataException>(()=>service.ReplayAsync(new(291,20244)));}finally{Directory.Delete(root,true);}}
    private static string FindRoot(){var value=AppContext.BaseDirectory;while(value is not null&&!File.Exists(Path.Combine(value,"PharmaAccess.sln")))value=Directory.GetParent(value)?.FullName;return value??throw new DirectoryNotFoundException();}
}
