using PharmaAccess.Application.MachineLearning;
using PharmaAccess.ML;
using Xunit;
using System.Text.Json;
namespace PharmaAccess.ML.Tests;
public sealed class PortableExplorerGuardTests
{
 [Theory][InlineData(false,false)][InlineData(false,true)][InlineData(true,false)]public async Task Historical_replay_fails_closed_before_touching_external_files(bool development,bool enabled){var service=HistoricalPredictionReplayService.Create(development,enabled,"missing-synthetic-test-snapshot.csv","missing-synthetic-test-bundle");await Assert.ThrowsAsync<InvalidOperationException>(()=>service.GetLaunchesAsync());}
 [Theory][InlineData(false,false)][InlineData(false,true)][InlineData(true,false)]public async Task Dynamic_mode_fails_closed_before_sqlcmd_or_private_files(bool development,bool enabled){await using var service=new DynamicAsOfPredictionService(development,enabled,"missing-snapshot.csv","missing-comparison.csv","missing-bundle");await Assert.ThrowsAsync<InvalidOperationException>(()=>service.GetLaunchesAsync());}
 [Fact]public void External_threshold_is_portable_and_uses_probability(){Assert.True(HistoricalReplayMode.MeetsThreshold(.10f));Assert.False(HistoricalReplayMode.MeetsThreshold(.05f));Assert.True(ServingDecisionPolicy.IsPredicted(.10f,.08));Assert.False(ServingDecisionPolicy.IsPredicted(.05f,.08));}
 [Fact]public void Clearly_synthetic_test_bundle_is_rejected_without_real_artifacts(){var root=Path.Combine(Path.GetTempPath(),$"synthetic-serving-fixture-{Guid.NewGuid():N}");var bundle=Path.Combine(root,"synthetic-test-only");Directory.CreateDirectory(bundle);try{var manifest=new{syntheticDevelopmentData=true,bundleVersion="synthetic-test-only",task="NextQuarterStateEntry",trainer="FastTree",dataset="synthetic-test-dataset",datasetVersionId=1,datasetHash=new string('A',64),featureSet="synthetic-test-features",featureSetVersionId=1,featureSetDefinitionHash=new string('B',64),modelInputSchemaHash=new string('C',64),artifactHash=new string('D',64),artifactSizeBytes=1,selectedThreshold=.08,probabilityOutput="serialized ML.NET calibrated Probability",serializedPredictedLabelThreshold=.5,servingDecisionRule="Probability >= 0.08",governanceStatus="ValidationSelected",r2aSnapshotHash=new string('E',64),r2bVerificationHash=new string('F',64)};var path=Path.Combine(bundle,"manifest.json");File.WriteAllText(path,JsonSerializer.Serialize(manifest));var registry=new LocalServingModelBundleRegistry(root,new("synthetic-test-dataset",1,new string('A',64),"synthetic-test-features",1,new string('B',64),new string('C',64)));Assert.Contains("Synthetic development",Assert.Throws<InvalidDataException>(()=>registry.LoadAndVerify(path)).Message);}finally{Directory.Delete(root,true);}}
}
