using System.Net;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using PharmaAccess.Application.MachineLearning;
using Xunit;

namespace PharmaAccess.Api.IntegrationTests;

public sealed class HistoricalReplayEndpointTests
{
    [Fact]public async Task Development_enabled_exposes_catalog_and_safe_replay_only(){using var host=await Host("Development",true);using var client=host.GetTestClient();var launches=await client.GetAsync("/api/v1/drug-state-prediction-explorer/launches");Assert.Equal(HttpStatusCode.OK,launches.StatusCode);using var catalog=JsonDocument.Parse(await launches.Content.ReadAsStringAsync());Assert.Equal(48,catalog.RootElement.GetArrayLength());var response=await client.PostAsync("/api/v1/drug-state-prediction-explorer/historical-replay",new StringContent("{\"genericLaunchId\":291,\"asOfQuarter\":20244}",Encoding.UTF8,"application/json"));var body=await response.Content.ReadAsStringAsync();Assert.Equal(HttpStatusCode.OK,response.StatusCode);Assert.Contains("ResearchDevelopmentHistoricalReplay",body);using var result=JsonDocument.Parse(body);var state=result.RootElement.GetProperty("RankedStates")[0];Assert.True(state.TryGetProperty("StateCode",out _));Assert.True(state.TryGetProperty("StateName",out _));Assert.False(state.TryGetProperty("Label",out _));Assert.False(state.TryGetProperty("Features",out _));Assert.False(result.RootElement.TryGetProperty("ArtifactPath",out _));}
    [Theory][InlineData("Development",false)][InlineData("Production",true)][InlineData("Production",false)]public async Task Disabled_or_non_development_fails_closed(string environment,bool enabled){using var host=await Host(environment,enabled);using var client=host.GetTestClient();Assert.Equal(HttpStatusCode.NotFound,(await client.GetAsync("/api/v1/drug-state-prediction-explorer/launches")).StatusCode);}
    [Theory][InlineData("Development",false)][InlineData("Production",true)]public async Task Explanation_inherits_research_mode_guard(string environment,bool enabled){using var host=await Host(environment,enabled);using var client=host.GetTestClient();var response=await client.PostAsync("/api/v1/drug-state-prediction-explorer/historical-replay/explain",new StringContent("{\"genericLaunchId\":291,\"asOfQuarter\":20244,\"probability\":1,\"rank\":999,\"states\":[{\"stateCode\":\"XX\"}]}",Encoding.UTF8,"application/json"));Assert.Equal(HttpStatusCode.ServiceUnavailable,response.StatusCode);}
    [Fact]public async Task Gemini_unavailable_uses_safe_fallback_and_does_not_break_scoring(){using var host=await Host("Development",true);using var client=host.GetTestClient();var request=new StringContent("{\"genericLaunchId\":291,\"asOfQuarter\":20244}",Encoding.UTF8,"application/json");Assert.Equal(HttpStatusCode.OK,(await client.PostAsync("/api/v1/drug-state-prediction-explorer/historical-replay",request)).StatusCode);var explanation=await client.PostAsync("/api/v1/drug-state-prediction-explorer/historical-replay/explain",new StringContent("{\"genericLaunchId\":291,\"asOfQuarter\":20244}",Encoding.UTF8,"application/json"));var body=await explanation.Content.ReadAsStringAsync();Assert.Equal(HttpStatusCode.OK,explanation.StatusCode);Assert.Contains("highest-ranked jurisdiction",body,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("Grounding JSON",body,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("Feature",body,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("Label",body,StringComparison.OrdinalIgnoreCase);}
    [Theory][InlineData("Development",false)][InlineData("Production",true)]public async Task Dynamic_mode_and_explanation_fail_closed(string environment,bool enabled){using var host=await Host(environment,enabled);using var client=host.GetTestClient();Assert.Equal(HttpStatusCode.NotFound,(await client.GetAsync("/api/v1/drug-state-prediction-explorer/dynamic/launches")).StatusCode);var body=new StringContent("{\"genericLaunchId\":291,\"asOfQuarter\":20244,\"features\":[1],\"probability\":1,\"rank\":1}",Encoding.UTF8,"application/json");Assert.Equal(HttpStatusCode.ServiceUnavailable,(await client.PostAsync("/api/v1/drug-state-prediction-explorer/dynamic-as-of/explain",body)).StatusCode);}
    [Fact]public async Task Malformed_and_unavailable_requests_fail_cleanly(){using var host=await Host("Development",true);using var client=host.GetTestClient();Assert.Equal(HttpStatusCode.BadRequest,(await client.PostAsync("/api/v1/drug-state-prediction-explorer/historical-replay",new StringContent("{}",Encoding.UTF8,"application/json"))).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await client.PostAsync("/api/v1/drug-state-prediction-explorer/historical-replay",new StringContent("{\"genericLaunchId\":999999,\"asOfQuarter\":20244}",Encoding.UTF8,"application/json"))).StatusCode);}
    [Fact]public async Task Market_context_endpoint_returns_verified_identity_and_handles_invalid_or_unavailable_history(){using var host=await Host("Development",true);using var client=host.GetTestClient();var valid=await client.PostAsync("/api/v1/drug-state-prediction-explorer/state-market-context",new StringContent("{\"genericLaunchId\":291,\"asOfQuarter\":20244}",Encoding.UTF8,"application/json"));var body=await valid.Content.ReadAsStringAsync();Assert.Equal(HttpStatusCode.OK,valid.StatusCode);using var json=JsonDocument.Parse(body);var state=json.RootElement.GetProperty("States")[0];Assert.Equal("TX",state.GetProperty("StateCode").GetString());Assert.Equal("Texas",state.GetProperty("StateName").GetString());Assert.Equal("Large & Growing",state.GetProperty("MarketProfile").GetString());Assert.Equal(HttpStatusCode.BadRequest,(await client.PostAsync("/api/v1/drug-state-prediction-explorer/state-market-context",new StringContent("{}",Encoding.UTF8,"application/json"))).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await client.PostAsync("/api/v1/drug-state-prediction-explorer/state-market-context",new StringContent("{\"genericLaunchId\":999,\"asOfQuarter\":20244}",Encoding.UTF8,"application/json"))).StatusCode);}
    private static async Task<IHost> Host(string environment,bool enabled){var values=new Dictionary<string,string?>{{"ModelServing:ResearchDevelopmentModeEnabled",enabled.ToString()},{"ModelServing:ResearchReplaySnapshotPath","synthetic-test-snapshot"},{"ModelServing:R2bVerificationPath","synthetic-test-r2b"},{"ModelServing:ServingBundlePath","synthetic-test-bundle"},{"ConnectionStrings:PharmaAccess",""}};return await new HostBuilder().ConfigureAppConfiguration(c=>c.AddInMemoryCollection(values)).ConfigureWebHost(w=>{w.UseEnvironment(environment).UseTestServer().UseStartup<Api.Startup>();if(environment=="Development"&&enabled)w.ConfigureTestServices(s=>{s.RemoveAll<IHistoricalPredictionReplayService>();s.RemoveAll<IDynamicAsOfPredictionService>();s.RemoveAll<IStateMarketContextService>();s.AddSingleton<IHistoricalPredictionReplayService,ReplayFake>();s.AddSingleton<IDynamicAsOfPredictionService,DynamicFake>();s.AddSingleton<IStateMarketContextService,MarketFake>();});}).StartAsync();}
    private static string FindRoot(){var value=AppContext.BaseDirectory;while(value is not null&&!File.Exists(Path.Combine(value,"PharmaAccess.sln")))value=Directory.GetParent(value)?.FullName;return value??throw new DirectoryNotFoundException();}
    private sealed class ReplayFake:IHistoricalPredictionReplayService
    {public Task<IReadOnlyList<HistoricalReplayLaunch>> GetLaunchesAsync(CancellationToken t=default)=>Task.FromResult<IReadOnlyList<HistoricalReplayLaunch>>(Enumerable.Range(1,47).Select(x=>new HistoricalReplayLaunch(x,$"Synthetic test launch {x}")).Append(new(291,"Synthetic test launch 291")).ToArray());public Task<IReadOnlyList<int>> GetQuartersAsync(int id,CancellationToken t=default)=>id==291?Task.FromResult<IReadOnlyList<int>>([20244]):throw new KeyNotFoundException();public Task<HistoricalReplayResponse> ReplayAsync(HistoricalReplayRequest r,CancellationToken t=default){if(r.GenericLaunchId<=0||r.AsOfQuarter<=0)throw new ArgumentException();if(r.GenericLaunchId!=291||r.AsOfQuarter!=20244)throw new KeyNotFoundException();return Task.FromResult(new HistoricalReplayResponse(HistoricalReplayMode.Name,291,"Synthetic test launch 291",20244,20251,"synthetic-test-model","synthetic-test-hash","synthetic-test-dataset",2,"synthetic-test-features",1,.08,2,[new(48,"TX","Texas",.10f,true,1),new(12,"FL","Florida",.05f,false,2)],["Synthetic portable test fixture."],ModelApprovalStatus.ValidationSelected,false,false));}}
    private sealed class DynamicFake:IDynamicAsOfPredictionService
    {public Task<IReadOnlyList<HistoricalReplayLaunch>> GetLaunchesAsync(CancellationToken t=default)=>Task.FromResult<IReadOnlyList<HistoricalReplayLaunch>>([new(291,"Synthetic test launch 291")]);public Task<IReadOnlyList<int>> GetQuartersAsync(int id,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<int>>([20244]);public Task<DynamicAsOfResponse> ScoreAsync(DynamicAsOfRequest r,CancellationToken t=default){if(r.GenericLaunchId<=0||r.AsOfQuarter<=0)throw new ArgumentException();return Task.FromResult(new DynamicAsOfResponse(DynamicAsOfMode.Name,r.GenericLaunchId,"Synthetic test launch",r.AsOfQuarter,20251,1,[new(48,"TX","Texas",.10f,true,1)],"synthetic-test-model","synthetic-test-hash","synthetic-test-dataset","synthetic-test-features",.08,ModelApprovalStatus.ValidationSelected,false,false,["Synthetic portable test fixture."]));}}
    private sealed class MarketFake:IStateMarketContextService
    {public Task<StateMarketContextResponse> GetAsync(StateMarketContextRequest r,CancellationToken t=default){if(r.GenericLaunchId<=0||r.AsOfQuarter<=0)throw new ArgumentException();if(r.GenericLaunchId!=291)throw new InvalidOperationException("InsufficientHistoricalContext");return Task.FromResult(new StateMarketContextResponse(291,20244,51,[new(48,"TX","Texas",20244,1200,90,1000,.04m,.2m,90,1200,1000,8,1,MarketDataSupport.High,"Large & Growing")],[]));}}
}
