using System.Net;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Xunit;

namespace PharmaAccess.Api.IntegrationTests;

public sealed class SecurityObservabilityTests
{
    [Fact]public async Task Anonymous_users_can_access_public_read_only_and_liveness_endpoints(){using var host=await Host();using var client=host.GetTestClient();Assert.Equal(HttpStatusCode.OK,(await client.GetAsync("/health/live")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await client.GetAsync("/api/v1/model-governance/drift-reports")).StatusCode);}
    [Fact]public async Task Anonymous_users_cannot_generate_drift_or_register_comparison(){using var host=await Host();using var client=host.GetTestClient();Assert.Equal(HttpStatusCode.Unauthorized,(await client.PostAsync("/api/v1/model-governance/drift-reports",Json(DriftJson))).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await client.PostAsync("/api/v1/model-governance/comparisons",Json(ComparisonJson))).StatusCode);}
    [Fact]public async Task Reviewer_can_generate_drift_and_register_but_cannot_approve(){using var host=await Host();using var client=Client(host,"reviewer","ModelGovernanceReviewer");Assert.Equal(HttpStatusCode.OK,(await client.PostAsync("/api/v1/model-governance/drift-reports",Json(DriftJson))).StatusCode);var comparison=await Register(client);Assert.Equal(HttpStatusCode.Forbidden,(await client.PostAsync("/api/v1/model-governance/promotions/approve",Json(Action(comparison,"spoofed")))).StatusCode);}
    [Fact]public async Task Approver_identity_comes_from_claims_and_body_spoofing_is_ignored(){using var host=await Host();using var reviewer=Client(host,"submitter","ModelGovernanceReviewer");var id=await Register(reviewer);using var approver=Client(host,"claims-approver","ModelGovernanceApprover");var response=await approver.PostAsync("/api/v1/model-governance/promotions/approve",Json(Action(id,"spoofed-body-user")));var body=await response.Content.ReadAsStringAsync();Assert.Equal(HttpStatusCode.OK,response.StatusCode);Assert.Contains("claims-approver",body);Assert.DoesNotContain("spoofed-body-user",body);}
    [Fact]public async Task Submitter_cannot_self_approve_even_with_approver_role(){using var host=await Host();using var submitter=Client(host,"same-user","ModelGovernanceReviewer,ModelGovernanceApprover");var id=await Register(submitter);var response=await submitter.PostAsync("/api/v1/model-governance/promotions/approve",Json(Action(id,"ignored")));Assert.Equal(HttpStatusCode.Conflict,response.StatusCode);}
    [Fact]public async Task Authorized_reviewer_can_reject_and_actor_is_claim_derived(){using var host=await Host();using var submitter=Client(host,"submitter","ModelGovernanceReviewer");var id=await Register(submitter);using var reviewer=Client(host,"rejector","ModelGovernanceReviewer");var response=await reviewer.PostAsync("/api/v1/model-governance/promotions/reject",Json(Action(id,"spoof")));var body=await response.Content.ReadAsStringAsync();Assert.Equal(HttpStatusCode.OK,response.StatusCode);Assert.Contains("rejector",body);Assert.DoesNotContain("spoof",body);}
    [Fact]public async Task Rate_limit_returns_429_and_safe_retry_header(){using var host=await Host(new Dictionary<string,string?>{{"RateLimiting:ResearchAssistantPermitLimit","1"}});using var client=host.GetTestClient();Assert.Equal(HttpStatusCode.OK,(await client.PostAsync("/api/v1/assistant/ask",Json("{\"question\":\"ROC AUC?\"}"))).StatusCode);var limited=await client.PostAsync("/api/v1/assistant/ask",Json("{\"question\":\"PR AUC?\"}"));Assert.Equal(HttpStatusCode.TooManyRequests,limited.StatusCode);Assert.True(limited.Headers.Contains("Retry-After"));}
    [Fact]public async Task Oversized_requests_are_rejected(){using var host=await Host();using var client=host.GetTestClient();var response=await client.PostAsync("/api/v1/assistant/ask",Json("{\"question\":\""+new string('x',17000)+"\"}"));Assert.Equal(HttpStatusCode.RequestEntityTooLarge,response.StatusCode);}
    [Fact]public async Task Invalid_administrative_request_returns_safe_problem_details(){using var host=await Host();using var client=Client(host,"reviewer","ModelGovernanceReviewer");var response=await client.PostAsync("/api/v1/model-governance/drift-reports",Json("{}"));var body=await response.Content.ReadAsStringAsync();Assert.Equal(HttpStatusCode.BadRequest,response.StatusCode);Assert.Equal("application/problem+json",response.Content.Headers.ContentType!.MediaType);Assert.DoesNotContain("System.",body);Assert.DoesNotContain("Server=",body);}
    [Fact]public async Task Security_headers_and_correlation_id_are_propagated(){using var host=await Host();using var client=host.GetTestClient();using var request=new HttpRequestMessage(HttpMethod.Get,"/health/live");request.Headers.Add("X-Correlation-ID","test-correlation-123");var response=await client.SendAsync(request);Assert.Equal("test-correlation-123",response.Headers.GetValues("X-Correlation-ID").Single());Assert.Equal("nosniff",response.Headers.GetValues("X-Content-Type-Options").Single());Assert.Contains("frame-ancestors 'none'",response.Headers.GetValues("Content-Security-Policy").Single());}
    [Fact]public async Task Logs_do_not_contain_questions_secrets_or_authorization_headers(){var provider=new CaptureLoggerProvider();using var host=await Host(logger:provider);using var client=host.GetTestClient();client.DefaultRequestHeaders.Authorization=new("Bearer","secret-token-value");await client.PostAsync("/api/v1/assistant/ask",Json("{\"question\":\"secret-prompt-value\"}"));var logs=string.Join('\n',provider.Messages);Assert.DoesNotContain("secret-token-value",logs);Assert.DoesNotContain("secret-prompt-value",logs);Assert.DoesNotContain("Authorization",logs);}
    [Fact]public async Task Liveness_does_not_require_sql_or_gemini_and_readiness_is_safely_degraded(){using var host=await Host();using var client=host.GetTestClient();var live=await client.GetAsync("/health/live");Assert.Equal(HttpStatusCode.OK,live.StatusCode);using var liveJson=JsonDocument.Parse(await live.Content.ReadAsStringAsync());Assert.Equal("Healthy",liveJson.RootElement.GetProperty("status").GetString());var ready=await client.GetAsync("/health/ready");var body=await ready.Content.ReadAsStringAsync();Assert.Equal(HttpStatusCode.OK,ready.StatusCode);using var readyJson=JsonDocument.Parse(body);Assert.Equal("Degraded",readyJson.RootElement.GetProperty("status").GetString());var dependencies=readyJson.RootElement.GetProperty("dependencies");Assert.Equal("NotConfigured",dependencies.GetProperty("sql").GetString());Assert.Equal("OptionalUnavailable",dependencies.GetProperty("gemini").GetString());Assert.DoesNotContain("ConnectionStrings",body);}
    [Fact]public async Task Startup_does_not_register_automatic_migration_execution(){using var host=await Host();Assert.DoesNotContain(host.Services.GetServices<IHostedService>(),x=>x.GetType().Name.Contains("Migration",StringComparison.OrdinalIgnoreCase));}
    [Fact]public async Task Version_endpoint_exposes_only_safe_build_metadata(){using var host=await Host();using var client=host.GetTestClient();var response=await client.GetAsync("/version");var body=await response.Content.ReadAsStringAsync();Assert.Equal(HttpStatusCode.OK,response.StatusCode);Assert.Contains("ApplicationVersion",body);Assert.Contains("CommitHash",body);Assert.Contains("BuildTimestamp",body);Assert.DoesNotContain("ConnectionStrings",body);Assert.DoesNotContain("\\",body);}

    private static async Task<IHost> Host(Dictionary<string,string?>? values=null,CaptureLoggerProvider? logger=null)=>await new HostBuilder().ConfigureAppConfiguration(c=>IntegrationTestConfiguration.Apply(c,values)).ConfigureLogging(l=>{l.ClearProviders();if(logger is not null)l.AddProvider(logger);}).ConfigureWebHost(w=>w.UseEnvironment("Development").UseTestServer().UseStartup<Api.Startup>()).StartAsync();
    private static HttpClient Client(IHost host,string user,string roles){var client=host.GetTestClient();client.DefaultRequestHeaders.Add("X-Development-User",user);client.DefaultRequestHeaders.Add("X-Development-Roles",roles);return client;}
    private static StringContent Json(string value)=>new(value,Encoding.UTF8,"application/json");
    private static async Task<Guid> Register(HttpClient client){var response=await client.PostAsync("/api/v1/model-governance/comparisons",Json(ComparisonJson));response.EnsureSuccessStatusCode();using var json=JsonDocument.Parse(await response.Content.ReadAsStringAsync());return json.RootElement.GetProperty("Id").GetGuid();}
    private static string Action(Guid id,string actor)=>JsonSerializer.Serialize(new{comparisonId=id,approverIdentifier=actor,approvalTimestampUtc=DateTime.UtcNow,reason="reviewed evidence"});
    private const string DriftJson="""{"championVersion":"fasttree-published","evaluationWindow":"2026-Q3","numericFeatures":[{"name":"Volume","reference":[0.1,0.2],"current":[0.1,0.2]}],"categoricalFeatures":[],"referencePredictions":[0.1,0.2],"currentPredictions":[0.1,0.2]}""";
    private static readonly string ComparisonJson=JsonSerializer.Serialize(new{champion=Model("fasttree-published-threshold-0.08"),challenger=Model("challenger-v1")});
    private static object Model(string version)=>new{version,artifactSha256=new string('a',64),artifactHashValid=true,featureSchemaHash="schema",evaluationCohortHash="cohort",datasetHash="dataset",reproducibilityHash="repro",leakageChecksPassed=true,metrics=new Dictionary<string,double>{{"ROC_AUC",.82},{"PR_AUC",.11},{"Brier",.08},{"CalibrationError",.02}},importantSubgroupPrAuc=new Dictionary<string,double>{{"North",.10}}};
    private sealed class CaptureLoggerProvider:ILoggerProvider{public List<string> Messages{get;}=[];public ILogger CreateLogger(string categoryName)=>new CaptureLogger(Messages);public void Dispose(){}private sealed class CaptureLogger(List<string> messages):ILogger{public IDisposable? BeginScope<TState>(TState state)where TState:notnull=>null;public bool IsEnabled(LogLevel level)=>true;public void Log<TState>(LogLevel level,EventId id,TState state,Exception? exception,Func<TState,Exception?,string> formatter)=>messages.Add(formatter(state,exception));}}
}
